import {
  NACE_MAX_HARDNESS_HRC,
  STEEL_DENSITY_KG_CM3,
  STEEL_DENSITY_KG_M3,
  STEEL_DENSITY_KG_MM3,
} from "@annix/product-data/steel";

export { NACE_MAX_HARDNESS_HRC, STEEL_DENSITY_KG_CM3, STEEL_DENSITY_KG_M3, STEEL_DENSITY_KG_MM3 };

export type { ButtWeldConfig, FilletWeldConfig, TackWeldConfig } from "@annix/product-data/pipe";
export {
  ANSI_PRESSURE_CLASSES,
  BS_4504_PRESSURE_CLASSES,
  BS_4504_PRESSURE_PN,
  BUTT_WELD_CONFIG,
  CALCULATION_DEFAULTS,
  CLOSURE_LENGTH_CONFIG,
  closureLengthLimits,
  closureWeight,
  DEFAULT_NOMINAL_BORES,
  DEFAULT_PIPE_LENGTH_M,
  FILLET_WELD_CONFIG,
  FLANGE_OD,
  IMPERIAL_PIPE_LENGTHS_M,
  METRIC_PIPE_LENGTHS_M,
  PRESSURE_CALCULATION_CONSTANTS,
  PUDDLE_PIPE_LENGTHS_M,
  RETAINING_RING_CONFIG,
  SABS_1123_PRESSURE_CLASSES,
  SABS_1123_PRESSURE_KPA,
  STANDARD_PIPE_LENGTHS_M,
  SURFACE_AREA_CONSTANTS,
  TACK_WELD_CONFIG,
  TEMPERATURE_CATEGORIES,
  tackWeldConfig,
  tackWeldWeight,
  WELD_INCREMENT_MM,
  WORKING_PRESSURE_BAR,
  WORKING_TEMPERATURE_CELSIUS,
} from "@annix/product-data/pipe";

export const steelDensity = {
  kgPerM3: STEEL_DENSITY_KG_M3,
  kgPerMm3: STEEL_DENSITY_KG_MM3,
  kgPerCm3: STEEL_DENSITY_KG_CM3,
  toKg: (volumeMm3: number) => volumeMm3 * STEEL_DENSITY_KG_MM3,
  toKgFromCm3: (volumeCm3: number) => volumeCm3 * STEEL_DENSITY_KG_CM3,
  toKgFromM3: (volumeM3: number) => volumeM3 * STEEL_DENSITY_KG_M3,
} as const;
