export {
  compareStandards,
  defaultStandardForRegion,
  FUSION_PROCEDURES,
  type FusionProcedureParameters,
  type FusionProcedureType,
  MACHINE_COMPLIANCE_STANDARDS,
  type MachineCompliance,
  type StandardParameterComparison,
  standardByCode,
  standardsForRegion,
  WELDER_QUALIFICATIONS,
  WELDING_STANDARD_LIST,
  WELDING_STANDARDS,
  type WelderQualification,
  type WeldingStandard,
  type WeldingStandardCode,
  type WeldingStandardRegion,
} from "@annix/product-data/hdpe/welding-standards";
