export type RubberSupplier =
  | "REMA TIP TOP"
  | "AU Industries"
  | "S&N Rubber"
  | "Weir Minerals"
  | "Impilo"
  | "Truco"
  | "Zenith"
  | "Rubber Inc"
  | "Generic";

export type PolymerBase =
  | "NR"
  | "NR/SBR"
  | "SBR"
  | "IIR"
  | "BIIR"
  | "CR"
  | "NBR"
  | "NBR-BR"
  | "CSM"
  | "EPDM"
  | "FKM"
  | "PU";

export type SANS1198Type = 1 | 2 | 3 | 4 | 5 | 6;

export type SANS1198Grade = "A" | "B" | "C";

export type HardnessClass = 35 | 40 | 50 | 60 | 70;

export type AbrasionResistance = "wet-slurry" | "dry" | "general";

export type CureMethod = "autoclave" | "cold-vulcanization" | "factory-vulcanized" | "hot-press";

export type AdhesiveSystem =
  | "chemosil"
  | "cilbond"
  | "megum"
  | "thixon"
  | "generic-rubber-adhesive";

export interface SANS1198Classification {
  type: SANS1198Type;
  grade: SANS1198Grade;
  hardnessClass: HardnessClass;
}

export interface RubberProduct {
  id: string;
  compoundCode: string;
  salesCode: string;
  name: string;
  supplier: RubberSupplier;
  polymerBase: PolymerBase;
  colour: string;
  description: string;
  typicalUses: string[];
  limitations: string[];
  hardnessShoreA: number;
  hardnessTolerance: number;
  maxOperatingTempC: number;
  minOperatingTempC: number;
  density: number;
  tensileMPa: number;
  elongationPercent: number;
  abrasionLossMm3: number;
  sans1198: SANS1198Classification | null;
  abrasionResistance: AbrasionResistance;
  suppliedAs: string;
  cureSystem: string;
  recommendedCureMethod: CureMethod | null;
  compatibleAdhesives: AdhesiveSystem[];
  minimumBendRadiusMm: number | null;
  substrateRequirements: string[];
  antiStatic: boolean;
  thicknessRange: { minMm: number; maxMm: number };
  revisionDate: string;
  features: string[];
}

export const rubberProducts: RubberProduct[] = [
  {
    id: "rema-sr1038-pink-nr",
    compoundCode: "SR1038",
    salesCode: "SC401AR",
    name: "Premium Pink Natural Rubber",
    supplier: "REMA TIP TOP",
    polymerBase: "NR",
    colour: "Pink",
    description:
      "A premium quality low modulus pink natural rubber with exceptional resistance to wet slurry abrasion.",
    typicalUses: [
      "Lining of tanks",
      "Chutes",
      "Pipes",
      "Fittings",
      "Valves",
      "Wet abrasion applications",
    ],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.01,
    tensileMPa: 20,
    elongationPercent: 650,
    abrasionLossMm3: 150,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Vulcanised or unvulcanised sheeting from 3mm gauge",
    cureSystem: "Steam at ±300KPa",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2020-07-16",
    features: [
      "Premium quality",
      "Low modulus",
      "Exceptional wet slurry abrasion resistance",
      "SANS 1198 Type 1 Grade A compliant",
    ],
  },
  {
    id: "rema-sr1077-green-nr",
    compoundCode: "SR1077",
    salesCode: "SC401AG",
    name: "Green Natural Rubber",
    supplier: "REMA TIP TOP",
    polymerBase: "NR",
    colour: "Green",
    description: "Green natural rubber with good resistance to abrasion.",
    typicalUses: ["Lining of tanks", "Launders", "Chutes", "General abrasion applications"],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.0,
    tensileMPa: 20,
    elongationPercent: 600,
    abrasionLossMm3: 180,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "general",
    suppliedAs: "Vulcanised or unvulcanised sheeting from 3mm gauge",
    cureSystem: "Steam at ±300KPa",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2020-01-10",
    features: ["Good abrasion resistance", "SANS 1198 Type 1 Grade A compliant", "General purpose"],
  },
  {
    id: "rema-sr1078-black-nr",
    compoundCode: "SR1078",
    salesCode: "SC401AB",
    name: "Premium Black Natural Rubber",
    supplier: "REMA TIP TOP",
    polymerBase: "NR",
    colour: "Black",
    description:
      "A premium quality black natural rubber with exceptional resistance to wet slurry abrasion.",
    typicalUses: [
      "Lining of tanks",
      "Chutes",
      "Pipes",
      "Fittings",
      "Valves",
      "Wet abrasion applications",
    ],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 35,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.01,
    tensileMPa: 20,
    elongationPercent: 650,
    abrasionLossMm3: 150,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Vulcanised or unvulcanised sheeting from 3mm gauge",
    cureSystem: "Steam at ±300KPa",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2020-01-10",
    features: [
      "Premium quality",
      "Softer compound (35 Shore A)",
      "Exceptional wet slurry abrasion resistance",
      "Can meet SANS 1198 Type 1 Grade A",
    ],
  },
  {
    id: "rema-sr1280-yellow-nr-sbr",
    compoundCode: "SR1280",
    salesCode: "SC401AY",
    name: "Yellow Natural & Styrene Butadiene Rubber",
    supplier: "REMA TIP TOP",
    polymerBase: "NR/SBR",
    colour: "Yellow",
    description:
      "Yellow natural and styrene butadiene rubber blend with superior resistance to dry abrasion.",
    typicalUses: [
      "Lining of tanks",
      "Chutes",
      "Pipes",
      "Fittings",
      "Valves",
      "Cyclones",
      "Dry abrasion applications",
    ],
    limitations: ["Oils", "Greases"],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.09,
    tensileMPa: 15,
    elongationPercent: 650,
    abrasionLossMm3: 150,
    sans1198: { type: 1, grade: "B", hardnessClass: 40 },
    abrasionResistance: "dry",
    suppliedAs: "Vulcanised or unvulcanised sheeting from 3mm gauge",
    cureSystem: "Steam at ±300KPa",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2020-01-10",
    features: [
      "Superior dry abrasion resistance",
      "NR/SBR blend",
      "Ideal for cyclones",
      "SANS 1198 Type 1 Grade B compliant",
    ],
  },
  {
    id: "au-a40-bsc",
    compoundCode: "AU-A40-BSC",
    salesCode: "AU-A40-BSC",
    name: "40 Shore Black Steam Cured",
    supplier: "AU Industries",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Steam cured 40 shore black natural rubber ideal for general-purpose lining. Exceptional for wet slurry abrasion applications.",
    typicalUses: [
      "Lining of tanks",
      "Chutes",
      "Launders",
      "Pulleys",
      "Pipes",
      "Hoses",
      "Wet slurry abrasion",
    ],
    limitations: ["Oils", "Acids", "Hydrocarbon solvents", "Strong oxidizing agents"],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.05,
    tensileMPa: 20,
    elongationPercent: 600,
    abrasionLossMm3: 150,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Uncured sheeting from 3mm gauge",
    cureSystem: "Autoclave at 300KPa for 90 mins",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-10-28",
    features: [
      "General purpose",
      "Exceptional wet slurry abrasion",
      "SANS 1198 Type 1 Grade A compliant",
      "74% rebound resilience",
    ],
  },
  {
    id: "au-a60-bsc",
    compoundCode: "AU-A60-BSC",
    salesCode: "AU-A60-BSC",
    name: "60 Shore Black Steam Cured",
    supplier: "AU Industries",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Steam cured 60 shore black natural rubber. Silica reinforced for cut and tear resistance in coarse abrasive sharp particle slurries.",
    typicalUses: [
      "Lining of tanks",
      "Chutes",
      "Launders",
      "Pulleys",
      "Pipes",
      "Hoses",
      "Coarse particle slurries",
    ],
    limitations: ["Oils", "Acids", "Hydrocarbon solvents", "Strong oxidizing agents"],
    hardnessShoreA: 60,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.08,
    tensileMPa: 18,
    elongationPercent: 400,
    abrasionLossMm3: 200,
    sans1198: { type: 1, grade: "A", hardnessClass: 60 },
    abrasionResistance: "general",
    suppliedAs: "Uncured sheeting from 3mm gauge",
    cureSystem: "Autoclave at 300KPa for 90 mins",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2025-08-14",
    features: [
      "Silica reinforced",
      "Cut and tear resistant",
      "Coarse particle applications",
      "SANS 1198 Type 1 Grade A compliant",
    ],
  },
  {
    id: "au-c50-nbr-br",
    compoundCode: "AU-C50-NBRBR",
    salesCode: "AU-C50-NBRBR",
    name: "50 Shore Nitrile-Butadiene Black Steam Cured",
    supplier: "AU Industries",
    polymerBase: "NBR-BR",
    colour: "Black",
    description:
      "Steam cured Nitrile-Butadiene blend for oil, fuel and hydrocarbon resistance with good abrasion resistance.",
    typicalUses: [
      "Lining of tanks",
      "Chutes",
      "Launders",
      "Pulleys",
      "Pipes",
      "Hoses",
      "Oil/fuel exposure applications",
    ],
    limitations: ["Phenols", "Ketones", "Carboxylates acid", "Nitrogen derivatives"],
    hardnessShoreA: 50,
    hardnessTolerance: 5,
    maxOperatingTempC: 120,
    minOperatingTempC: -20,
    density: 1.075,
    tensileMPa: 7,
    elongationPercent: 350,
    abrasionLossMm3: 180,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Uncured sheeting from 3mm gauge",
    cureSystem: "Autoclave at 300KPa for 90 mins",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2025-06-21",
    features: [
      "Oil resistant",
      "Fuel resistant",
      "Hydrocarbon resistant",
      "Higher temperature rating (120°C)",
    ],
  },
  {
    id: "au-c50-bbsc",
    compoundCode: "AU-C50-BBSC",
    salesCode: "AU-C50-BBSC",
    name: "50 Shore Bromobutyl Black Steam Cured",
    supplier: "AU Industries",
    polymerBase: "BIIR",
    colour: "Black",
    description:
      "Steam cured Bromobutyl rubber for chemical resistance. Excellent for mineral acids, aqueous solutions, saltwater and polar solvents. Low gas permeability.",
    typicalUses: [
      "Lining of pipes",
      "Tanks",
      "Chutes",
      "Pulleys",
      "Hoses",
      "Chemical resistance applications",
    ],
    limitations: ["Oils", "Greases", "Some solvents", "Limited abrasion resistance"],
    hardnessShoreA: 50,
    hardnessTolerance: 5,
    maxOperatingTempC: 120,
    minOperatingTempC: -40,
    density: 1.16,
    tensileMPa: 7,
    elongationPercent: 500,
    abrasionLossMm3: 250,
    sans1198: { type: 2, grade: "C", hardnessClass: 50 },
    abrasionResistance: "general",
    suppliedAs: "Uncured sheeting from 3mm gauge",
    cureSystem: "Autoclave at 300KPa for 90 mins",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-03-28",
    features: [
      "Chemical resistant",
      "Mineral acid resistant",
      "Low gas permeability",
      "Polar solvent resistant",
      "SANS 1198 Type 2 compliant",
    ],
  },
  {
    id: "sn-bl40",
    compoundCode: "SNBL40",
    salesCode: "SNBL40",
    name: "Premium Black NR/SBR",
    supplier: "S&N Rubber",
    polymerBase: "NR/SBR",
    colour: "Black",
    description:
      "Premium quality black NR/SBR based compound with exceptional wet slurry abrasion resistance.",
    typicalUses: [
      "Lining of pipes",
      "Tanks",
      "Chutes",
      "Fittings",
      "Valves",
      "Wet abrasion applications",
    ],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidizing agents"],
    hardnessShoreA: 35,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.05,
    tensileMPa: 20,
    elongationPercent: 600,
    abrasionLossMm3: 150,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Calendered rolls of uncured sheeting from 3mm",
    cureSystem: "Steam cure at ±300KPa",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-03-25",
    features: [
      "Premium quality",
      "Exceptional wet slurry abrasion",
      "74% min rebound resilience",
      "SANS 1198 Type 1 Grade A compliant",
      "21 day shelf life",
    ],
  },
  {
    id: "sn-iir50",
    compoundCode: "SNIIR50",
    salesCode: "SNIIR50",
    name: "Bromobutyl Chemical Resistant",
    supplier: "S&N Rubber",
    polymerBase: "BIIR",
    colour: "Black",
    description:
      "Bromobutyl compound (BIIR) for chemical resistance with limited abrasion resistance. Resists polar solvents, mineral acids, bases and aqueous phases.",
    typicalUses: ["Lining of tanks", "Chutes", "Pipes", "Chemical resistance applications"],
    limitations: ["Oils", "Grease", "Solvents", "Limited abrasion resistance"],
    hardnessShoreA: 50,
    hardnessTolerance: 5,
    maxOperatingTempC: 120,
    minOperatingTempC: -40,
    density: 1.16,
    tensileMPa: 7,
    elongationPercent: 500,
    abrasionLossMm3: 250,
    sans1198: { type: 2, grade: "C", hardnessClass: 50 },
    abrasionResistance: "general",
    suppliedAs: "Calendered rolls of uncured sheeting from 3mm",
    cureSystem: "Steam cure at ±300KPa",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-04-23",
    features: [
      "Chemical resistant",
      "Polar solvent resistant",
      "Mineral acid resistant",
      "SANS 1198 Type 2 Grade C compliant",
    ],
  },
  {
    id: "weir-linacure-40",
    compoundCode: "Linacure 40",
    salesCode: "WMD0119",
    name: "Linacure 40",
    supplier: "Weir Minerals",
    polymerBase: "NR",
    colour: "Red",
    description:
      "Premium wear resistant uncured natural rubber for fine slurry applications. Uses Linatex formulation principles for superior wear performance.",
    typicalUses: ["Pipelines", "Chutes", "Tank linings", "Hoses", "Fine slurry applications"],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidizing agents"],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -40,
    density: 0.96,
    tensileMPa: 21.5,
    elongationPercent: 730,
    abrasionLossMm3: 120,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Uncured sheeting from 3mm to 12mm",
    cureSystem: "Hot bonding / autoclave",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 12 },
    revisionDate: "2023-05-08",
    features: [
      "Superior fine slurry wear performance",
      "Linatex formulation",
      "83% resilience",
      "6 month shelf life",
      "Lowest cost of ownership",
    ],
  },
  {
    id: "impilo-cc40a-nr",
    compoundCode: "CC40A NR",
    salesCode: "CC40A",
    name: "Chemical Cure 40A Natural Rubber",
    supplier: "Impilo",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Excellent grade chemical cure 40 Shore A natural rubber for moderate to aggressive wet/slurry abrasion and wear applications.",
    typicalUses: [
      "Lining of tanks",
      "Launders",
      "Underpans",
      "Pipes",
      "Chutes",
      "Wet/slurry abrasion",
    ],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidizing agents"],
    hardnessShoreA: 40,
    hardnessTolerance: 10,
    maxOperatingTempC: 70,
    minOperatingTempC: -5,
    density: 1.14,
    tensileMPa: 18,
    elongationPercent: 600,
    abrasionLossMm3: 160,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Calendered rolls from 1.5mm to 10mm",
    cureSystem: "Chemical cure at 23°C (10-14 days)",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 1.5, maxMm: 10 },
    revisionDate: "2024-05-14",
    features: [
      "Chemical cure (no autoclave required)",
      "6 week shelf life",
      "SANS 1198 Type 1 Grade A compliant",
      "SANS 1201:2005 lining compliant",
    ],
  },
  {
    id: "truco-trucotex",
    compoundCode: "TRUCOTEX",
    salesCode: "TRUCOTEX",
    name: "Trucotex Premium Latex",
    supplier: "Truco",
    polymerBase: "NR",
    colour: "Pink",
    description:
      "95% pure natural rubber with exceptional wet slurry abrasion resistance. Premium latex compound for severe wet abrasion applications.",
    typicalUses: ["Chutes", "Pipes", "Cyclones", "Skirts", "Scrapers", "Wet slurry applications"],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 35,
    hardnessTolerance: 5,
    maxOperatingTempC: 80,
    minOperatingTempC: -40,
    density: 0.96,
    tensileMPa: 26.5,
    elongationPercent: 788,
    abrasionLossMm3: 100,
    sans1198: { type: 1, grade: "A", hardnessClass: 35 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Vulcanised or unvulcanised sheeting",
    cureSystem: "Autoclave vulcanisation",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "95% pure natural rubber",
      "Exceptional wet slurry abrasion",
      "High tensile strength (26.5 MPa)",
      "788% elongation at break",
      "Premium latex formulation",
    ],
  },
  {
    id: "truco-trucoline",
    compoundCode: "TRUCOLINE",
    salesCode: "TRUCOLINE",
    name: "Trucoline Natural Rubber",
    supplier: "Truco",
    polymerBase: "NR",
    colour: "Black",
    description:
      "High natural rubber content compound with good abrasion resistance for general lining applications.",
    typicalUses: [
      "Chutes",
      "Pipes",
      "Cyclones",
      "Skirts",
      "Scrapers",
      "General abrasion applications",
    ],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 80,
    minOperatingTempC: -40,
    density: 1.0,
    tensileMPa: 15,
    elongationPercent: 650,
    abrasionLossMm3: 150,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "general",
    suppliedAs: "Vulcanised or unvulcanised sheeting",
    cureSystem: "Autoclave vulcanisation",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "High NR content",
      "Good abrasion resistance",
      "General purpose",
      "SANS 1198 Type 1 Grade A compliant",
    ],
  },
  {
    id: "truco-trucotuff",
    compoundCode: "TRUCOTUFF",
    salesCode: "TRUCOTUFF",
    name: "Trucotuff Heavy Duty",
    supplier: "Truco",
    polymerBase: "NR/SBR",
    colour: "Black",
    description:
      "Silica-reinforced NR/SBR blend with excellent resistance to cutting and slashing by dry, sharp-edged particles. Heavy-duty compound for severe dry abrasion.",
    typicalUses: [
      "Screen decks",
      "Chutes",
      "Transfer points",
      "Dry abrasion applications",
      "Sharp particle handling",
    ],
    limitations: ["Oils", "Hydrocarbon solvents"],
    hardnessShoreA: 70,
    hardnessTolerance: 5,
    maxOperatingTempC: 80,
    minOperatingTempC: -40,
    density: 1.15,
    tensileMPa: 20.5,
    elongationPercent: 440,
    abrasionLossMm3: 120,
    sans1198: { type: 1, grade: "A", hardnessClass: 70 },
    abrasionResistance: "dry",
    suppliedAs: "Vulcanised or unvulcanised sheeting",
    cureSystem: "Autoclave vulcanisation",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 6, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "Silica reinforced",
      "Cut and slash resistant",
      "Heavy duty applications",
      "Dry sharp particle abrasion",
      "High hardness (70 Shore A)",
    ],
  },
  {
    id: "truco-t36-latex",
    compoundCode: "T36",
    salesCode: "T36-LATEX",
    name: "T36 Premium Latex",
    supplier: "Truco",
    polymerBase: "NR",
    colour: "Pink",
    description:
      "Premium latex rubber with exceptional abrasion resistance for fine material in wet conditions. Low specific gravity for reduced weight.",
    typicalUses: ["Cyclones", "Pipes", "Chutes", "Fine wet slurry handling", "Pump linings"],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 36,
    hardnessTolerance: 3,
    maxOperatingTempC: 70,
    minOperatingTempC: -40,
    density: 0.96,
    tensileMPa: 23,
    elongationPercent: 810,
    abrasionLossMm3: 90,
    sans1198: { type: 1, grade: "A", hardnessClass: 35 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Vulcanised sheeting",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 20 },
    revisionDate: "2024-01-01",
    features: [
      "Premium latex formulation",
      "Exceptional fine slurry abrasion",
      "Low specific gravity (0.96)",
      "810% elongation at break",
      "Lightweight construction",
    ],
  },
  {
    id: "truco-epdm-70",
    compoundCode: "EPDM70",
    salesCode: "EPDM70",
    name: "EPDM 70 Shore Heat Resistant",
    supplier: "Truco",
    polymerBase: "EPDM",
    colour: "Black",
    description:
      "EPDM rubber for hot water, steam and chemical resistance. Excellent ozone and weathering resistance. Not suitable for oil or hydrocarbon exposure.",
    typicalUses: [
      "Hot water systems",
      "Steam applications",
      "Chemical tanks",
      "Weather exposed applications",
      "Outdoor installations",
    ],
    limitations: ["Oils", "Fuels", "Hydrocarbon solvents", "Aromatic compounds"],
    hardnessShoreA: 70,
    hardnessTolerance: 5,
    maxOperatingTempC: 130,
    minOperatingTempC: -20,
    density: 1.15,
    tensileMPa: 5,
    elongationPercent: 300,
    abrasionLossMm3: 300,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 12 },
    revisionDate: "2024-01-01",
    features: [
      "Hot water resistant",
      "Steam resistant",
      "Ozone resistant",
      "Weather resistant",
      "High temperature rating (130°C)",
    ],
  },
  {
    id: "truco-butyl-60",
    compoundCode: "BUTYL60",
    salesCode: "BUTYL60",
    name: "Butyl 60 Shore Chemical Resistant",
    supplier: "Truco",
    polymerBase: "IIR",
    colour: "Black",
    description:
      "Butyl rubber with excellent chemical and acid resistance. High temperature capability up to 140°C. Low gas permeability.",
    typicalUses: [
      "Chemical tanks",
      "Acid storage",
      "Gas barrier applications",
      "High temperature chemical exposure",
    ],
    limitations: ["Oils", "Fuels", "Hydrocarbon solvents", "Limited abrasion resistance"],
    hardnessShoreA: 60,
    hardnessTolerance: 5,
    maxOperatingTempC: 140,
    minOperatingTempC: -20,
    density: 1.15,
    tensileMPa: 5,
    elongationPercent: 300,
    abrasionLossMm3: 280,
    sans1198: { type: 2, grade: "B", hardnessClass: 60 },
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 12 },
    revisionDate: "2024-01-01",
    features: [
      "Chemical resistant",
      "Acid resistant",
      "Low gas permeability",
      "High temperature (140°C)",
      "SANS 1198 Type 2 compliant",
    ],
  },
  {
    id: "zenith-abrasuper-40",
    compoundCode: "ABRASUPER40",
    salesCode: "ABRASUPER40",
    name: "AbraSuper 40 Premium Abrasion",
    supplier: "Zenith",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Premium resistance to abrasion with excellent tensile strength and high elasticity. High grade natural rubber for slurry chutes, pipes, tanks, and cyclones.",
    typicalUses: ["Slurry chutes", "Pipes", "Tanks", "Cyclones", "Wet abrasion applications"],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 90,
    minOperatingTempC: -50,
    density: 1.05,
    tensileMPa: 20,
    elongationPercent: 600,
    abrasionLossMm3: 130,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Vulcanised sheeting from 3mm",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "Premium abrasion resistance",
      "High elasticity",
      "High tensile strength",
      "SANS 1198 Type 1 Grade A compliant",
      "Wide temperature range (-50 to 90°C)",
    ],
  },
  {
    id: "zenith-antiabrasive-60",
    compoundCode: "ANTIABR60",
    salesCode: "ANTIABR60",
    name: "Anti-Abrasive 60 Shore",
    supplier: "Zenith",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Abrasion resistant rubber compounded from high grade natural rubber for best resistance to cut, wear and abrasion. Sustained performance for industrial applications.",
    typicalUses: [
      "Chutes",
      "Conveyors",
      "Screen decks",
      "Transfer points",
      "Dry abrasion applications",
    ],
    limitations: ["Oils", "Hydrocarbon solvents", "Strong oxidising agents"],
    hardnessShoreA: 60,
    hardnessTolerance: 5,
    maxOperatingTempC: 90,
    minOperatingTempC: -50,
    density: 1.1,
    tensileMPa: 18,
    elongationPercent: 500,
    abrasionLossMm3: 150,
    sans1198: { type: 1, grade: "A", hardnessClass: 60 },
    abrasionResistance: "dry",
    suppliedAs: "Vulcanised sheeting from 3mm",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "Cut resistant",
      "Wear resistant",
      "High grade natural rubber",
      "SANS 1198 Type 1 Grade A compliant",
      "Sustained performance",
    ],
  },
  {
    id: "zenith-zenaflex-nrsbr-65",
    compoundCode: "NR/SBR65135",
    salesCode: "ZENAFLEX65",
    name: "Zena-Flex NR/SBR 65 Shore",
    supplier: "Zenith",
    polymerBase: "NR/SBR",
    colour: "Black",
    description:
      "NR/SBR blend providing superior resilience, tensile, elongation, good low temperature flexibility and excellent adhesion to fabric and metals.",
    typicalUses: [
      "General purpose seals",
      "Gaskets",
      "Washers",
      "Packing materials",
      "Vibration dampeners",
    ],
    limitations: ["Oils", "Hydrocarbon solvents"],
    hardnessShoreA: 65,
    hardnessTolerance: 5,
    maxOperatingTempC: 80,
    minOperatingTempC: -40,
    density: 1.35,
    tensileMPa: 5,
    elongationPercent: 250,
    abrasionLossMm3: 200,
    sans1198: { type: 1, grade: "B", hardnessClass: 60 },
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 1, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "Superior resilience",
      "Excellent metal adhesion",
      "Low temperature flexibility",
      "General purpose",
      "NR/SBR blend",
    ],
  },
  {
    id: "generic-fkm-75-chemical",
    compoundCode: "FKM75",
    salesCode: "FKM75",
    name: "Viton FKM 75 Shore Chemical Resistant",
    supplier: "Generic",
    polymerBase: "FKM",
    colour: "Black",
    description:
      "Fluoroelastomer (Viton type) with outstanding resistance to oils, fuels, and chemicals. Excellent high temperature performance up to 200°C continuous.",
    typicalUses: [
      "Chemical processing equipment",
      "Fuel system seals",
      "Hydraulic system seals",
      "Oil resistant linings",
      "High temperature gaskets",
    ],
    limitations: [
      "Ketones",
      "Esters",
      "Amines",
      "Hot water/steam",
      "Low temperature applications below -15°C",
    ],
    hardnessShoreA: 75,
    hardnessTolerance: 5,
    maxOperatingTempC: 200,
    minOperatingTempC: -15,
    density: 1.85,
    tensileMPa: 10,
    elongationPercent: 200,
    abrasionLossMm3: 150,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting from 1mm",
    cureSystem: "Bisphenol or peroxide cured",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 1, maxMm: 12 },
    revisionDate: "2024-01-01",
    features: [
      "Outstanding chemical resistance",
      "Excellent oil/fuel resistance",
      "High temperature capability to 200°C",
      "Low permeability",
      "Ozone/weathering resistant",
    ],
  },
  {
    id: "generic-fkm-65-soft",
    compoundCode: "FKM65",
    salesCode: "FKM65",
    name: "Viton FKM 65 Shore Soft Grade",
    supplier: "Generic",
    polymerBase: "FKM",
    colour: "Black",
    description:
      "Softer fluoroelastomer grade for sealing applications requiring flexibility while maintaining chemical resistance.",
    typicalUses: [
      "O-rings and seals",
      "Gaskets",
      "Diaphragms",
      "Flexible linings",
      "Expansion joints",
    ],
    limitations: [
      "Ketones",
      "Esters",
      "Amines",
      "Hot water/steam",
      "Low temperature applications below -15°C",
    ],
    hardnessShoreA: 65,
    hardnessTolerance: 5,
    maxOperatingTempC: 200,
    minOperatingTempC: -15,
    density: 1.82,
    tensileMPa: 8,
    elongationPercent: 250,
    abrasionLossMm3: 180,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting from 0.5mm",
    cureSystem: "Bisphenol cured",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 0.5, maxMm: 10 },
    revisionDate: "2024-01-01",
    features: [
      "Softer compound for sealing",
      "Excellent chemical resistance",
      "High temperature capability",
      "Low compression set",
      "Good flexibility",
    ],
  },
  {
    id: "generic-fkm-90-high-temp",
    compoundCode: "FKM90HT",
    salesCode: "FKM90HT",
    name: "Viton FKM 90 Shore High Temperature",
    supplier: "Generic",
    polymerBase: "FKM",
    colour: "Brown",
    description:
      "Hard fluoroelastomer grade for extreme temperature applications up to 250°C with excellent compression set resistance.",
    typicalUses: [
      "High temperature seals",
      "Engine components",
      "Aerospace applications",
      "Industrial ovens",
      "Exhaust system seals",
    ],
    limitations: [
      "Ketones",
      "Esters",
      "Amines",
      "Low temperature flexibility",
      "Cost-sensitive applications",
    ],
    hardnessShoreA: 90,
    hardnessTolerance: 5,
    maxOperatingTempC: 250,
    minOperatingTempC: -10,
    density: 1.9,
    tensileMPa: 12,
    elongationPercent: 150,
    abrasionLossMm3: 120,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting from 1mm",
    cureSystem: "Peroxide cured",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 1, maxMm: 15 },
    revisionDate: "2024-01-01",
    features: [
      "Extreme temperature resistance to 250°C",
      "Low compression set",
      "Excellent chemical resistance",
      "Hard compound for wear resistance",
      "Aerospace grade available",
    ],
  },
  {
    id: "generic-pu-85-abrasion",
    compoundCode: "PU85AR",
    salesCode: "PU85AR",
    name: "Polyurethane 85 Shore Abrasion Resistant",
    supplier: "Generic",
    polymerBase: "PU",
    colour: "Natural/Amber",
    description:
      "High performance cast polyurethane with exceptional abrasion resistance. Ester-based for superior mechanical properties.",
    typicalUses: [
      "Chute and hopper linings",
      "Conveyor belt scrapers",
      "Cyclone linings",
      "Screen deck panels",
      "Pipe linings for slurry",
    ],
    limitations: [
      "Hydrolysis in hot water/steam",
      "Strong acids and alkalis",
      "Prolonged UV exposure",
      "Temperatures above 80°C",
    ],
    hardnessShoreA: 85,
    hardnessTolerance: 5,
    maxOperatingTempC: 80,
    minOperatingTempC: -30,
    density: 1.15,
    tensileMPa: 35,
    elongationPercent: 450,
    abrasionLossMm3: 25,
    sans1198: null,
    abrasionResistance: "dry",
    suppliedAs: "Cast sheets and moulded components",
    cureSystem: "MDI/TDI prepolymer cured",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 50 },
    revisionDate: "2024-01-01",
    features: [
      "Exceptional abrasion resistance",
      "High tensile strength",
      "Good load bearing capacity",
      "Oil and solvent resistant",
      "Cast to custom shapes",
    ],
  },
  {
    id: "generic-pu-70-flexible",
    compoundCode: "PU70FL",
    salesCode: "PU70FL",
    name: "Polyurethane 70 Shore Flexible",
    supplier: "Generic",
    polymerBase: "PU",
    colour: "Natural/Amber",
    description:
      "Flexible polyurethane elastomer for applications requiring resilience and impact absorption.",
    typicalUses: [
      "Impact pads",
      "Vibration dampeners",
      "Flexible couplings",
      "Suspension bushings",
      "Buffer pads",
    ],
    limitations: [
      "Hydrolysis in hot water/steam",
      "Strong acids and alkalis",
      "Prolonged UV exposure",
      "Temperatures above 70°C",
    ],
    hardnessShoreA: 70,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -35,
    density: 1.12,
    tensileMPa: 25,
    elongationPercent: 550,
    abrasionLossMm3: 40,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Cast sheets and moulded components",
    cureSystem: "MDI prepolymer cured",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 2, maxMm: 40 },
    revisionDate: "2024-01-01",
    features: [
      "High resilience",
      "Excellent impact absorption",
      "Good tear resistance",
      "Oil resistant",
      "Flexible at low temperatures",
    ],
  },
  {
    id: "generic-pu-95-hard",
    compoundCode: "PU95HD",
    salesCode: "PU95HD",
    name: "Polyurethane 95 Shore Hard Wearing",
    supplier: "Generic",
    polymerBase: "PU",
    colour: "Natural/Amber",
    description:
      "Very hard polyurethane for severe sliding abrasion applications. Excellent cut and gouge resistance.",
    typicalUses: [
      "Liner plates for high wear zones",
      "Mill linings",
      "Hydrocyclone apex inserts",
      "Pump impellers",
      "Wear rings",
    ],
    limitations: [
      "Hydrolysis in hot water/steam",
      "Strong acids and alkalis",
      "Reduced flexibility",
      "Temperatures above 85°C",
    ],
    hardnessShoreA: 95,
    hardnessTolerance: 3,
    maxOperatingTempC: 85,
    minOperatingTempC: -25,
    density: 1.18,
    tensileMPa: 40,
    elongationPercent: 350,
    abrasionLossMm3: 18,
    sans1198: null,
    abrasionResistance: "dry",
    suppliedAs: "Cast sheets and moulded components",
    cureSystem: "MDI prepolymer cured",
    recommendedCureMethod: null,
    compatibleAdhesives: [],
    minimumBendRadiusMm: null,
    substrateRequirements: [],
    antiStatic: false,
    thicknessRange: { minMm: 5, maxMm: 75 },
    revisionDate: "2024-01-01",
    features: [
      "Superior cut resistance",
      "Exceptional abrasion resistance",
      "High load bearing",
      "Machinable",
      "Very hard compound",
    ],
  },
  {
    id: "rubber-inc-premium-nr-40",
    compoundCode: "RI-NR40",
    salesCode: "RIPNR40",
    name: "Rubber Inc Premium NR 40 Shore",
    supplier: "Rubber Inc",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Premium natural rubber compound with excellent wet slurry abrasion resistance. Autoclave cured for maximum bond strength.",
    typicalUses: ["Pipe linings", "Chute linings", "Pump linings", "Valve linings", "Tank linings"],
    limitations: [
      "Oils and solvents",
      "Ozone degradation",
      "UV exposure",
      "Temperatures above 80°C",
    ],
    hardnessShoreA: 40,
    hardnessTolerance: 5,
    maxOperatingTempC: 80,
    minOperatingTempC: -40,
    density: 1.02,
    tensileMPa: 22,
    elongationPercent: 700,
    abrasionLossMm3: 110,
    sans1198: { type: 1, grade: "A", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Uncured sheeting from 3mm",
    cureSystem: "Autoclave at 300KPa",
    recommendedCureMethod: "autoclave",
    compatibleAdhesives: ["chemosil", "cilbond"],
    minimumBendRadiusMm: 50,
    substrateRequirements: ["Sa 2.5 blast", "Anchor pattern 50-75 micron"],
    antiStatic: false,
    thicknessRange: { minMm: 3, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "Premium NR formulation",
      "Exceptional wet slurry abrasion",
      "SANS 1198 Type 1 Grade A compliant",
      "High tensile strength",
      "Autoclave cured",
    ],
  },
  {
    id: "rubber-inc-nrsbr-65",
    compoundCode: "RI-NRSBR65",
    salesCode: "RINRSBR65",
    name: "Rubber Inc NR/SBR 65 Shore Heavy Duty",
    supplier: "Rubber Inc",
    polymerBase: "NR/SBR",
    colour: "Black",
    description:
      "Heavy duty NR/SBR blend for dry abrasion and cut resistance. Silica reinforced for coarse particle applications.",
    typicalUses: [
      "Cyclone linings",
      "Screen decks",
      "Transfer chutes",
      "Impact zones",
      "Coarse particle handling",
    ],
    limitations: [
      "Oils and solvents",
      "Ozone degradation",
      "UV exposure",
      "Temperatures above 85°C",
    ],
    hardnessShoreA: 65,
    hardnessTolerance: 5,
    maxOperatingTempC: 85,
    minOperatingTempC: -35,
    density: 1.12,
    tensileMPa: 18,
    elongationPercent: 450,
    abrasionLossMm3: 140,
    sans1198: { type: 1, grade: "A", hardnessClass: 60 },
    abrasionResistance: "dry",
    suppliedAs: "Uncured or vulcanised sheeting",
    cureSystem: "Autoclave or hot press",
    recommendedCureMethod: "autoclave",
    compatibleAdhesives: ["chemosil", "cilbond", "megum"],
    minimumBendRadiusMm: 75,
    substrateRequirements: ["Sa 2.5 blast", "Anchor pattern 50-75 micron"],
    antiStatic: false,
    thicknessRange: { minMm: 6, maxMm: 30 },
    revisionDate: "2024-01-01",
    features: [
      "Silica reinforced",
      "Cut and slash resistant",
      "Heavy duty applications",
      "SANS 1198 Type 1 Grade A compliant",
      "Dry sharp particle abrasion",
    ],
  },
  {
    id: "rubber-inc-cold-cure-nr",
    compoundCode: "RI-CCNR",
    salesCode: "RICCNR",
    name: "Rubber Inc Cold Cure NR",
    supplier: "Rubber Inc",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Cold vulcanising natural rubber for field application where autoclave curing is not possible. Chemical cure system.",
    typicalUses: [
      "Field repairs",
      "On-site lining",
      "Large vessels",
      "Immovable equipment",
      "Patch repairs",
    ],
    limitations: [
      "Oils and solvents",
      "Lower bond strength than autoclave",
      "Longer cure time required",
      "Temperature sensitive cure",
    ],
    hardnessShoreA: 45,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -30,
    density: 1.1,
    tensileMPa: 16,
    elongationPercent: 550,
    abrasionLossMm3: 170,
    sans1198: { type: 1, grade: "B", hardnessClass: 40 },
    abrasionResistance: "wet-slurry",
    suppliedAs: "Uncured sheeting with activator",
    cureSystem: "Chemical cure at ambient (14-21 days)",
    recommendedCureMethod: "cold-vulcanization",
    compatibleAdhesives: ["chemosil", "generic-rubber-adhesive"],
    minimumBendRadiusMm: 40,
    substrateRequirements: [
      "Sa 2.5 blast",
      "Anchor pattern 50-75 micron",
      "Apply within 4 hours of blasting",
    ],
    antiStatic: false,
    thicknessRange: { minMm: 2, maxMm: 15 },
    revisionDate: "2024-01-01",
    features: [
      "No autoclave required",
      "Field application possible",
      "Self-levelling properties",
      "Good wet abrasion",
      "Patch repair capability",
    ],
  },
  {
    id: "generic-antistatic-nr-45",
    compoundCode: "AS-NR45",
    salesCode: "ASNR45",
    name: "Anti-Static Natural Rubber 45 Shore",
    supplier: "Generic",
    polymerBase: "NR",
    colour: "Black",
    description:
      "Conductive natural rubber compound for applications requiring static dissipation. Carbon black loaded for conductivity.",
    typicalUses: [
      "Explosive handling areas",
      "Dust collection systems",
      "Grain handling",
      "Pharmaceutical processing",
      "ATEX zones",
    ],
    limitations: [
      "Oils and solvents",
      "Lower abrasion resistance than standard NR",
      "UV exposure",
      "Temperatures above 70°C",
    ],
    hardnessShoreA: 45,
    hardnessTolerance: 5,
    maxOperatingTempC: 70,
    minOperatingTempC: -35,
    density: 1.15,
    tensileMPa: 15,
    elongationPercent: 500,
    abrasionLossMm3: 200,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: "factory-vulcanized",
    compatibleAdhesives: ["chemosil", "cilbond"],
    minimumBendRadiusMm: 50,
    substrateRequirements: ["Sa 2.5 blast", "Conductive primer required"],
    antiStatic: true,
    thicknessRange: { minMm: 3, maxMm: 20 },
    revisionDate: "2024-01-01",
    features: [
      "Static dissipative (10^4 to 10^8 ohms)",
      "ATEX compliant",
      "Explosion protection",
      "Carbon black conductive filler",
      "Grounding required",
    ],
  },
  {
    id: "generic-antistatic-nrsbr-60",
    compoundCode: "AS-NRSBR60",
    salesCode: "ASNRSBR60",
    name: "Anti-Static NR/SBR 60 Shore",
    supplier: "Generic",
    polymerBase: "NR/SBR",
    colour: "Black",
    description:
      "Conductive NR/SBR blend combining static dissipation with improved abrasion resistance for industrial applications.",
    typicalUses: [
      "Coal handling",
      "Mining conveyors",
      "Chemical plants",
      "Solvent handling",
      "Hazardous material transfer",
    ],
    limitations: ["Oils and solvents", "UV exposure", "Temperatures above 75°C"],
    hardnessShoreA: 60,
    hardnessTolerance: 5,
    maxOperatingTempC: 75,
    minOperatingTempC: -30,
    density: 1.18,
    tensileMPa: 16,
    elongationPercent: 450,
    abrasionLossMm3: 180,
    sans1198: null,
    abrasionResistance: "general",
    suppliedAs: "Vulcanised sheeting",
    cureSystem: "Factory vulcanised",
    recommendedCureMethod: "factory-vulcanized",
    compatibleAdhesives: ["chemosil", "cilbond", "megum"],
    minimumBendRadiusMm: 60,
    substrateRequirements: ["Sa 2.5 blast", "Conductive primer required", "Earth bonding point"],
    antiStatic: true,
    thicknessRange: { minMm: 4, maxMm: 25 },
    revisionDate: "2024-01-01",
    features: [
      "Static dissipative (10^5 to 10^9 ohms)",
      "ATEX Zone 21/22 suitable",
      "Better abrasion than pure NR anti-static",
      "NR/SBR blend",
      "Industrial grade conductivity",
    ],
  },
];

export function rubberProductsBySupplier(supplier: RubberSupplier): RubberProduct[] {
  return rubberProducts.filter((p) => p.supplier === supplier);
}

export function rubberProductsByPolymer(polymer: PolymerBase): RubberProduct[] {
  return rubberProducts.filter((p) => p.polymerBase === polymer);
}

export function rubberProductsForTemperature(maxTempC: number): RubberProduct[] {
  return rubberProducts.filter((p) => p.maxOperatingTempC >= maxTempC);
}

export function rubberProductsForAbrasion(type: AbrasionResistance): RubberProduct[] {
  return rubberProducts.filter(
    (p) => p.abrasionResistance === type || p.abrasionResistance === "general",
  );
}

export function rubberProductsBySANS1198Type(type: SANS1198Type): RubberProduct[] {
  return rubberProducts.filter((p) => p.sans1198?.type === type);
}

export function rubberProductsBySANS1198Grade(grade: SANS1198Grade): RubberProduct[] {
  return rubberProducts.filter((p) => p.sans1198?.grade === grade);
}

export function rubberProductsByHardness(
  minHardness: number,
  maxHardness: number,
): RubberProduct[] {
  return rubberProducts.filter(
    (p) =>
      p.hardnessShoreA >= minHardness - p.hardnessTolerance &&
      p.hardnessShoreA <= maxHardness + p.hardnessTolerance,
  );
}

export function bestAbrasionResistantProducts(): RubberProduct[] {
  return [...rubberProducts].sort((a, b) => a.abrasionLossMm3 - b.abrasionLossMm3);
}

export function highTensileProducts(minMPa: number): RubberProduct[] {
  return rubberProducts.filter((p) => p.tensileMPa >= minMPa);
}
