import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";
import { RubberCompoundStock } from "./rubber-compound-stock.entity";

export enum RubberCompoundOrderStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  ORDERED = "ORDERED",
  RECEIVED = "RECEIVED",
  CANCELLED = "CANCELLED",
}

@Entity("rubber_compound_orders")
export class RubberCompoundOrder {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ name: "firebase_uid", type: "varchar", length: 100, unique: true })
  firebaseUid: string;

  @Column({ name: "order_number", type: "varchar", length: 50 })
  orderNumber: string;

  @Column({ name: "compound_stock_id", type: "int" })
  compoundStockId: number;

  @ManyToOne(() => RubberCompoundStock)
  @JoinColumn({ name: "compound_stock_id" })
  compoundStock: RubberCompoundStock;

  @Column({
    name: "quantity_kg",
    type: "decimal",
    precision: 12,
    scale: 3,
  })
  quantityKg: number;

  @Column({
    name: "status",
    type: "enum",
    enum: RubberCompoundOrderStatus,
    default: RubberCompoundOrderStatus.PENDING,
  })
  status: RubberCompoundOrderStatus;

  @Column({ name: "is_auto_generated", type: "boolean", default: false })
  isAutoGenerated: boolean;

  @Column({ name: "supplier_name", type: "varchar", length: 200, nullable: true })
  supplierName: string | null;

  @Column({ name: "expected_delivery", type: "date", nullable: true })
  expectedDelivery: Date | null;

  @Column({ name: "notes", type: "text", nullable: true })
  notes: string | null;

  @Column({ name: "created_by", type: "varchar", length: 100, nullable: true })
  createdBy: string | null;

  @CreateDateColumn({ name: "created_at" })
  createdAt: Date;

  @UpdateDateColumn({ name: "updated_at" })
  updatedAt: Date;
}
