import { RubberCompoundStock } from "./rubber-compound-stock.entity";

export enum RubberCompoundOrderStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  ORDERED = "ORDERED",
  RECEIVED = "RECEIVED",
  CANCELLED = "CANCELLED",
}

export class RubberCompoundOrder {
  id: number;

  firebaseUid: string;

  orderNumber: string;

  compoundStockId: number;

  compoundStock: RubberCompoundStock;

  quantityKg: number;

  status: RubberCompoundOrderStatus;

  isAutoGenerated: boolean;

  supplierName: string | null;

  expectedDelivery: Date | null;

  notes: string | null;

  createdBy: string | null;

  createdAt: Date;

  updatedAt: Date;
}
