export type RubberPriceProductFamily = "plate" | "pipe";

export interface RubberPriceProductSeed {
  code: string;
  supplier: string | null;
  bondingType: string | null;
  colour: string | null;
  shoreHardness: number | null;
  specificGravity: number | null;
  costPerKg: number | null;
  family: RubberPriceProductFamily;
}

export const RUBBER_PLATE_PRICE_PRODUCTS: RubberPriceProductSeed[] = [
  {
    code: "1078",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 38,
    specificGravity: 1.01,
    costPerKg: 114.6,
    family: "plate",
  },
  {
    code: "572",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.11,
    costPerKg: 75.08,
    family: "plate",
  },
  {
    code: "951",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.23,
    costPerKg: 65.87,
    family: "plate",
  },
  {
    code: "565",
    supplier: "Rema",
    bondingType: "Chemical",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.25,
    costPerKg: 64.81,
    family: "plate",
  },
  {
    code: "509",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.25,
    costPerKg: 68.06,
    family: "plate",
  },
  {
    code: "546",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.13,
    costPerKg: 100.99,
    family: "plate",
  },
  {
    code: "1058",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.1,
    costPerKg: 110.48,
    family: "plate",
  },
  {
    code: "1038",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.01,
    costPerKg: 131.79,
    family: "plate",
  },
  {
    code: "1077",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Green",
    shoreHardness: 40,
    specificGravity: 0.97,
    costPerKg: 137.22,
    family: "plate",
  },
  {
    code: "CO15",
    supplier: "Rema",
    bondingType: "Chemical",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.24,
    costPerKg: 70.68,
    family: "plate",
  },
  {
    code: "537",
    supplier: "Rema",
    bondingType: "Chemical",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.14,
    costPerKg: 89.34,
    family: "plate",
  },
  {
    code: "5073",
    supplier: "Rema",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 70,
    specificGravity: 1.17,
    costPerKg: 105.35,
    family: "plate",
  },
  {
    code: "5053",
    supplier: "Rema",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.23,
    costPerKg: 101.16,
    family: "plate",
  },
  {
    code: "1328",
    supplier: "Rema",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 55,
    specificGravity: 1.24,
    costPerKg: 98.0,
    family: "plate",
  },
  {
    code: "1084",
    supplier: "Rema",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.29,
    costPerKg: 103.18,
    family: "plate",
  },
  {
    code: "CO13",
    supplier: "Rema",
    bondingType: "Chemical",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.43,
    costPerKg: 57.47,
    family: "plate",
  },
  {
    code: "1280",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Yellow",
    shoreHardness: 38,
    specificGravity: 1.09,
    costPerKg: 138.04,
    family: "plate",
  },
  {
    code: "Remaline 35",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Yellow",
    shoreHardness: 40,
    specificGravity: 1.01,
    costPerKg: 105.93,
    family: "plate",
  },
  {
    code: "300",
    supplier: "Rema",
    bondingType: "Neoprene",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.28,
    costPerKg: 203.45,
    family: "plate",
  },
  {
    code: "1200",
    supplier: "Rema",
    bondingType: "EPDM",
    colour: "Black",
    shoreHardness: 55,
    specificGravity: 1.22,
    costPerKg: 123.33,
    family: "plate",
  },
  {
    code: "Linacure 40",
    supplier: "Weir",
    bondingType: "Natural",
    colour: "Linacure",
    shoreHardness: 40,
    specificGravity: 0.98,
    costPerKg: 246.03,
    family: "plate",
  },
  {
    code: "Linacure 60",
    supplier: "Weir",
    bondingType: "Natural",
    colour: "Linacure",
    shoreHardness: 60,
    specificGravity: 1.1,
    costPerKg: 226.24,
    family: "plate",
  },
  {
    code: "Linard 60",
    supplier: "Weir",
    bondingType: "Cured",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.1,
    costPerKg: 241.73,
    family: "plate",
  },
  {
    code: "Linatex",
    supplier: "Weir",
    bondingType: "Cured",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 0.96,
    costPerKg: 424.02,
    family: "plate",
  },
  {
    code: "Trucotex 40",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.01,
    costPerKg: 115.0,
    family: "plate",
  },
  {
    code: "Trucoline 40",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.12,
    costPerKg: 92.0,
    family: "plate",
  },
  {
    code: "Trucotex 60 Red",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.14,
    costPerKg: 104.05,
    family: "plate",
  },
  {
    code: "Trucotex 60 Black",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.18,
    costPerKg: 83.35,
    family: "plate",
  },
  {
    code: "Truco 40 Chem",
    supplier: "Truco",
    bondingType: "Chemical",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.14,
    costPerKg: 78.68,
    family: "plate",
  },
  {
    code: "Truco 40 Chem",
    supplier: "Truco",
    bondingType: "Chemical",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.19,
    costPerKg: 67.6,
    family: "plate",
  },
  {
    code: "Truco SC Bromobutyl",
    supplier: "Truco",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.11,
    costPerKg: 103.64,
    family: "plate",
  },
  {
    code: "T36",
    supplier: "Truco",
    bondingType: "Cured",
    colour: "Red",
    shoreHardness: null,
    specificGravity: null,
    costPerKg: null,
    family: "plate",
  },
  {
    code: "SC Heroline",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 38,
    specificGravity: 1.0,
    costPerKg: 112.1,
    family: "plate",
  },
  {
    code: "SC40A NR",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.13,
    costPerKg: 75.95,
    family: "plate",
  },
  {
    code: "SC 50B",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.23,
    costPerKg: 71.83,
    family: "plate",
  },
  {
    code: "SC 50C",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 55,
    specificGravity: 1.23,
    costPerKg: 62.59,
    family: "plate",
  },
  {
    code: "SC 60A",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.14,
    costPerKg: 74.67,
    family: "plate",
  },
  {
    code: "SC Heroline",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 38,
    specificGravity: 1.0,
    costPerKg: 123.75,
    family: "plate",
  },
  {
    code: "Bromobutyl 50A",
    supplier: "Impilo",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.17,
    costPerKg: 118.76,
    family: "plate",
  },
  {
    code: "Nitrile 60A",
    supplier: "Impilo",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.25,
    costPerKg: 130.16,
    family: "plate",
  },
  {
    code: "SC60 EPDM",
    supplier: "Impilo",
    bondingType: "EPDM",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.12,
    costPerKg: 125.43,
    family: "plate",
  },
  {
    code: "SC60A Neo",
    supplier: "Impilo",
    bondingType: "Neoprene",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.3,
    costPerKg: 183.31,
    family: "plate",
  },
  {
    code: "CC40A",
    supplier: "Impilo",
    bondingType: "Chemical",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.12,
    costPerKg: 73.02,
    family: "plate",
  },
  {
    code: "CC60A",
    supplier: "Impilo",
    bondingType: "Chemical",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.2,
    costPerKg: 68.77,
    family: "plate",
  },
  {
    code: "CC40",
    supplier: "Impilo",
    bondingType: "Chemical",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.24,
    costPerKg: 80.94,
    family: "plate",
  },
  {
    code: "IMP FRAS 60",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.37,
    costPerKg: 128.8,
    family: "plate",
  },
  {
    code: "A40-RSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.05,
    costPerKg: 110.13,
    family: "plate",
  },
  {
    code: "A40-YSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Yellow",
    shoreHardness: 40,
    specificGravity: 1.05,
    costPerKg: 126.19,
    family: "plate",
  },
  {
    code: "A40-GSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Green",
    shoreHardness: 40,
    specificGravity: 1.05,
    costPerKg: 110.92,
    family: "plate",
  },
  {
    code: "A40-BSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.04,
    costPerKg: null,
    family: "plate",
  },
  {
    code: "A38-PSC",
    supplier: "AU",
    bondingType: "Premium Natural",
    colour: "Pink",
    shoreHardness: 38,
    specificGravity: 0.98,
    costPerKg: 168.77,
    family: "plate",
  },
  {
    code: "A60P-PSC",
    supplier: "AU",
    bondingType: "Premium Natural",
    colour: "Pink",
    shoreHardness: 60,
    specificGravity: 1.14,
    costPerKg: 154.11,
    family: "plate",
  },
  {
    code: "A38P-BSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 38,
    specificGravity: 1.04,
    costPerKg: 98.41,
    family: "plate",
  },
  {
    code: "TE-A40-YSC",
    supplier: "AU",
    bondingType: "Premium Natural",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.0,
    costPerKg: 158.72,
    family: "plate",
  },
  {
    code: "A58-BSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 58,
    specificGravity: 1.08,
    costPerKg: 95.95,
    family: "plate",
  },
  {
    code: "A60-RSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.14,
    costPerKg: 103.4,
    family: "plate",
  },
  {
    code: "C60-NBSC",
    supplier: "AU",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.21,
    costPerKg: 135.74,
    family: "plate",
  },
  {
    code: "C60-NBRBSC",
    supplier: "AU",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.08,
    costPerKg: 185.91,
    family: "plate",
  },
  {
    code: "C50-NEOSC",
    supplier: "AU",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.4,
    costPerKg: 219.57,
    family: "plate",
  },
  {
    code: "C60-HYPSC",
    supplier: "AU",
    bondingType: "Chemical",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.25,
    costPerKg: 290.71,
    family: "plate",
  },
  {
    code: "C50-EPDMSC",
    supplier: "AU",
    bondingType: "EPDM",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.1,
    costPerKg: 137.52,
    family: "plate",
  },
  {
    code: "Bromobutyl 50",
    supplier: "AU",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.08,
    costPerKg: 134.05,
    family: "plate",
  },
];

export const RUBBER_PIPE_PRICE_PRODUCTS: RubberPriceProductSeed[] = [
  {
    code: "1078",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.01,
    costPerKg: 114.59,
    family: "pipe",
  },
  {
    code: "951",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.23,
    costPerKg: 65.87,
    family: "pipe",
  },
  {
    code: "509",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.25,
    costPerKg: 68.06,
    family: "pipe",
  },
  {
    code: "546",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.13,
    costPerKg: 100.99,
    family: "pipe",
  },
  {
    code: "1058",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.1,
    costPerKg: 110.48,
    family: "pipe",
  },
  {
    code: "1038",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.01,
    costPerKg: 131.78,
    family: "pipe",
  },
  {
    code: "1077",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Green",
    shoreHardness: 40,
    specificGravity: 0.97,
    costPerKg: 131.78,
    family: "pipe",
  },
  {
    code: "5073",
    supplier: "Rema",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 70,
    specificGravity: 1.17,
    costPerKg: 123.65,
    family: "pipe",
  },
  {
    code: "5053",
    supplier: "Rema",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.23,
    costPerKg: 127.92,
    family: "pipe",
  },
  {
    code: "1329",
    supplier: "Rema",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.24,
    costPerKg: 116.67,
    family: "pipe",
  },
  {
    code: "1084",
    supplier: "Rema",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.29,
    costPerKg: 123.82,
    family: "pipe",
  },
  {
    code: "1280",
    supplier: "Rema",
    bondingType: "Natural",
    colour: "Yellow",
    shoreHardness: 40,
    specificGravity: 1.09,
    costPerKg: 138.04,
    family: "pipe",
  },
  {
    code: "300",
    supplier: "Rema",
    bondingType: "Neoprene",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.28,
    costPerKg: 203.45,
    family: "pipe",
  },
  {
    code: "1200",
    supplier: "Rema",
    bondingType: "EPDM",
    colour: "Black",
    shoreHardness: 55,
    specificGravity: 1.22,
    costPerKg: 123.33,
    family: "pipe",
  },
  {
    code: "Linacure 40",
    supplier: "Weir",
    bondingType: "Natural",
    colour: "Linacure",
    shoreHardness: 40,
    specificGravity: 0.98,
    costPerKg: 246.03,
    family: "pipe",
  },
  {
    code: "Linacure 60",
    supplier: "Weir",
    bondingType: "Natural",
    colour: "Linacure",
    shoreHardness: 60,
    specificGravity: 1.1,
    costPerKg: 226.24,
    family: "pipe",
  },
  {
    code: "Trucoline 40",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.09,
    costPerKg: 82.0,
    family: "pipe",
  },
  {
    code: "Trucotex 60 Red",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.14,
    costPerKg: 104.05,
    family: "pipe",
  },
  {
    code: "Trucotex 60 Black",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.18,
    costPerKg: 83.35,
    family: "pipe",
  },
  {
    code: "Truco SC Bromobutyl",
    supplier: "Truco",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.11,
    costPerKg: 103.64,
    family: "pipe",
  },
  {
    code: "SC Heroline",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.08,
    costPerKg: 95.31,
    family: "pipe",
  },
  {
    code: "SC 50A",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 55,
    specificGravity: 1.2,
    costPerKg: 71.83,
    family: "pipe",
  },
  {
    code: "Heroline 50",
    supplier: "Impilo",
    bondingType: "Premium Natural",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.08,
    costPerKg: 96.29,
    family: "pipe",
  },
  {
    code: "SC 50B",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.23,
    costPerKg: 65.0,
    family: "pipe",
  },
  {
    code: "SC 60A",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.14,
    costPerKg: 70.91,
    family: "pipe",
  },
  {
    code: "SC Heroline",
    supplier: "Impilo",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.0,
    costPerKg: 116.67,
    family: "pipe",
  },
  {
    code: "Bromobutyl 50A",
    supplier: "Impilo",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.17,
    costPerKg: 128.5,
    family: "pipe",
  },
  {
    code: "Nitrile 60A",
    supplier: "Impilo",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.25,
    costPerKg: 122.27,
    family: "pipe",
  },
  {
    code: "A38-PSC",
    supplier: "AU",
    bondingType: "Premium Natural",
    colour: "Pink",
    shoreHardness: 38,
    specificGravity: 0.98,
    costPerKg: 185.65,
    family: "pipe",
  },
  {
    code: "A38-BSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 38,
    specificGravity: 1.04,
    costPerKg: 98.41,
    family: "pipe",
  },
  {
    code: "A40-RSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 40,
    specificGravity: 1.05,
    costPerKg: 110.13,
    family: "pipe",
  },
  {
    code: "A40-YSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Yellow",
    shoreHardness: 40,
    specificGravity: 1.03,
    costPerKg: 126.19,
    family: "pipe",
  },
  {
    code: "A40-GSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Green",
    shoreHardness: 40,
    specificGravity: 1.01,
    costPerKg: 110.92,
    family: "pipe",
  },
  {
    code: "A40-BSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 40,
    specificGravity: 1.04,
    costPerKg: null,
    family: "pipe",
  },
  {
    code: "A60P-PSC",
    supplier: "AU",
    bondingType: "Premium Natural",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.15,
    costPerKg: null,
    family: "pipe",
  },
  {
    code: "A58-BSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Black",
    shoreHardness: 58,
    specificGravity: 1.08,
    costPerKg: 95.95,
    family: "pipe",
  },
  {
    code: "A60-RSC",
    supplier: "AU",
    bondingType: "Natural",
    colour: "Red",
    shoreHardness: 60,
    specificGravity: 1.14,
    costPerKg: 103.4,
    family: "pipe",
  },
  {
    code: "C60-NBSC",
    supplier: "AU",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 60,
    specificGravity: 1.21,
    costPerKg: 135.74,
    family: "pipe",
  },
  {
    code: "C50-NBRBSC",
    supplier: "AU",
    bondingType: "Nitrile",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.08,
    costPerKg: 185.91,
    family: "pipe",
  },
  {
    code: "C50-NEOSC",
    supplier: "AU",
    bondingType: "Neoprene",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.4,
    costPerKg: 173.21,
    family: "pipe",
  },
  {
    code: "C50-EPDMSC",
    supplier: "AU",
    bondingType: "EPDM",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.1,
    costPerKg: 98.23,
    family: "pipe",
  },
  {
    code: "C50-BBSC",
    supplier: "AU",
    bondingType: "Butyl",
    colour: "Black",
    shoreHardness: 50,
    specificGravity: 1.16,
    costPerKg: 116.23,
    family: "pipe",
  },
];

export const RUBBER_PRICE_PRODUCTS: RubberPriceProductSeed[] = [
  ...RUBBER_PLATE_PRICE_PRODUCTS,
  ...RUBBER_PIPE_PRICE_PRODUCTS,
];
