export const PIPE_END_OPTIONS = [
  {
    value: "PE",
    label: "PE - Plain ended (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
  },
  {
    value: "TOE_NPT",
    label: "TOE NPT - Threaded one end NPT (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    threadType: "NPT",
    threadedEnds: 1,
  },
  {
    value: "TBE_NPT",
    label: "TBE NPT - Threaded both ends NPT (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    threadType: "NPT",
    threadedEnds: 2,
  },
  {
    value: "TOE_BSP",
    label: "TOE BSP - Threaded one end BSP (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    threadType: "BSP",
    threadedEnds: 1,
  },
  {
    value: "TBE_BSP",
    label: "TBE BSP - Threaded both ends BSP (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    threadType: "BSP",
    threadedEnds: 2,
  },
  {
    value: "GOE",
    label: "GOE - Grooved one end (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    groovedEnds: 1,
  },
  {
    value: "GBE",
    label: "GBE - Grooved both ends (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    groovedEnds: 2,
  },
  {
    value: "FOE_GOE",
    label: "FOE + GOE - Flanged one end + grooved (1 weld)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 0,
    flangeCount: 1,
    groovedEnds: 1,
  },
  {
    value: "FOE_TOE",
    label: "FOE + TOE - Flanged one end + threaded (1 weld)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 0,
    flangeCount: 1,
    threadedEnds: 1,
  },
  {
    value: "FOE",
    label: "FOE - Flanged one end (1 weld)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 0,
    flangeCount: 1,
  },
  {
    value: "FBE",
    label: "FBE - Flanged both ends (2 flange welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
  },
  {
    value: "FOE_LF",
    label: "FOE + L/F - Flanged one end + loose flange (1 flange weld + tack)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 1,
    flangeCount: 2,
  },
  {
    value: "FOE_RF",
    label: "FOE + R/F - Flanged one end + rotating flange (2 flange welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
  },
  {
    value: "2X_RF",
    label: "2 x R/F - Rotating flanges both ends (2 flange welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
  },
] as const;

export const BEND_END_OPTIONS = [
  {
    value: "PE",
    label: "PE - Plain ended (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
  },
  {
    value: "FOE",
    label: "FOE - Flanged one end (1 weld)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 0,
    flangeCount: 1,
  },
  {
    value: "FBE",
    label: "FBE - Flanged both ends (2 flange welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
  },
  {
    value: "FOE_LF",
    label: "FOE + L/F - Flanged one end + loose flange (1 flange weld + tack)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 1,
    flangeCount: 2,
  },
  {
    value: "2xLF",
    label: "L/F Both Ends - Loose flanges both ends (tack welds only)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 2,
    flangeCount: 2,
  },
  {
    value: "FOE_RF",
    label: "FOE + R/F - Flanged one end + rotating flange (2 flange welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
  },
  {
    value: "2X_RF",
    label: "2 x R/F - Rotating flanges both ends (2 flange welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
  },
] as const;

export const REDUCER_END_OPTIONS = [
  {
    value: "PE",
    label: "PE - Plain ended (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    hasLargeEnd: false,
    hasSmallEnd: false,
  },
  {
    value: "FOE",
    label: "FOE - Flanged one end (1 weld)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 0,
    flangeCount: 1,
    hasLargeEnd: true,
    hasSmallEnd: false,
  },
  {
    value: "FBE",
    label: "FBE - Flanged both ends (2 welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
    hasLargeEnd: true,
    hasSmallEnd: true,
  },
  {
    value: "2X_RF",
    label: "R/F x 2 - Rotating flanges both ends (2 welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
    hasLargeEnd: true,
    hasSmallEnd: true,
  },
  {
    value: "2X_LF",
    label: "L/F x 2 - Loose flanges both ends (tack welds only)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 2,
    flangeCount: 2,
    hasLargeEnd: true,
    hasSmallEnd: true,
  },
  {
    value: "FOE_RF",
    label: "FOE + R/F - Fixed + rotating flange (2 welds)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
    hasLargeEnd: true,
    hasSmallEnd: true,
  },
  {
    value: "FOE_LF",
    label: "FOE + L/F - Fixed + loose flange (1 weld + tack)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 1,
    flangeCount: 2,
    hasLargeEnd: true,
    hasSmallEnd: true,
  },
  {
    value: "RF_LF",
    label: "R/F + L/F - Rotating + loose flange (1 weld + tack)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 1,
    flangeCount: 2,
    hasLargeEnd: true,
    hasSmallEnd: true,
  },
] as const;

export const FITTING_END_OPTIONS = [
  {
    value: "PE",
    label: "PE - Plain ended (0 welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 0,
    flangeCount: 0,
    hasInlet: false,
    hasOutlet: false,
    hasBranch: false,
    inletType: null,
    outletType: null,
    branchType: null,
  },
  {
    value: "FAE",
    label: "FAE - Flanged All Ends (3 welds)",
    weldCount: 3,
    flangeWeldCount: 3,
    tackWeldEnds: 0,
    flangeCount: 3,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: true,
    inletType: "fixed",
    outletType: "fixed",
    branchType: "fixed",
  },
  {
    value: "F2E",
    label: "F2E - Flanged 2 ends (2 welds) - Main pipe flanged, Tee OE",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 0,
    flangeCount: 2,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: false,
    inletType: "fixed",
    outletType: "fixed",
    branchType: null,
  },
  {
    value: "F2E_LF",
    label: "F2E + L/F - Flanged 2 ends + L/F on inlet, Tee flanged (2 welds + tack)",
    weldCount: 2,
    flangeWeldCount: 2,
    tackWeldEnds: 1,
    flangeCount: 3,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: true,
    inletType: "loose",
    outletType: "fixed",
    branchType: "fixed",
  },
  {
    value: "F2E_RF",
    label: "F2E + R/F - Flanged 2 ends + R/F on Tee Section B (3 welds)",
    weldCount: 3,
    flangeWeldCount: 3,
    tackWeldEnds: 0,
    flangeCount: 3,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: true,
    inletType: "fixed",
    outletType: "fixed",
    branchType: "rotating",
  },
  {
    value: "3X_RF",
    label: "3 x R/F - Rotating flanges all 3 ends (3 welds)",
    weldCount: 3,
    flangeWeldCount: 3,
    tackWeldEnds: 0,
    flangeCount: 3,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: true,
    inletType: "rotating",
    outletType: "rotating",
    branchType: "rotating",
  },
  {
    value: "3X_LF",
    label: "3 x L/F - Loose flanges all 3 ends (3 tack welds)",
    weldCount: 0,
    flangeWeldCount: 0,
    tackWeldEnds: 3,
    flangeCount: 3,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: true,
    inletType: "loose",
    outletType: "loose",
    branchType: "loose",
  },
  {
    value: "2X_LF_FOE",
    label: "2 x L/F + FOE - 2 loose flanges + 1 fixed (1 weld + 2 tacks)",
    weldCount: 1,
    flangeWeldCount: 1,
    tackWeldEnds: 2,
    flangeCount: 3,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: true,
    inletType: "dynamic",
    outletType: "dynamic",
    branchType: "dynamic",
  },
  {
    value: "2X_RF_FOE",
    label: "2 x R/F + FOE - R/F main pipe, FOE on Tee Section B (3 welds)",
    weldCount: 3,
    flangeWeldCount: 3,
    tackWeldEnds: 0,
    flangeCount: 3,
    hasInlet: true,
    hasOutlet: true,
    hasBranch: true,
    inletType: "rotating",
    outletType: "rotating",
    branchType: "fixed",
  },
] as const;

export type FlangeType = "fixed" | "loose" | "rotating" | "dynamic" | null;

export type PipeEndOption = (typeof PIPE_END_OPTIONS)[number];
export type BendEndOption = (typeof BEND_END_OPTIONS)[number];
export type FittingEndOption = (typeof FITTING_END_OPTIONS)[number];
export type ReducerEndOption = (typeof REDUCER_END_OPTIONS)[number];
