packages:
  - annix-backend
  - annix-frontend
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - sharp
  - tesseract.js
  - unrs-resolver

onlyBuiltDependencies:
  - '@annix/claude-swarm'
  - puppeteer
patchedDependencies:
  '@tanstack/query-core@5.90.20': patches/@tanstack__query-core@5.90.20.patch
