#!/usr/bin/env bash
set -euo pipefail

# Fetches production database credentials from Fly.io and writes .env.prod-db
# Usage: ./setup-prod-db.sh

echo "Fetching production database credentials from Fly.io..."

DB_PASSWORD=$(fly ssh console -a annix-app -C "printenv DATABASE_PASSWORD" 2>/dev/null | tail -1 | tr -d '\r\n')

if [ -z "$DB_PASSWORD" ]; then
  echo "Failed to fetch DATABASE_PASSWORD from Fly.io. Make sure you are authenticated with 'fly auth login'."
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/annix-backend/.env.prod-db"

cat > "$ENV_FILE" <<EOF
# Production database overrides (auto-generated by setup-prod-db.sh)
# WARNING: This connects to the LIVE production database. Be careful!
DATABASE_HOST=ep-polished-shape-abxr8muc.eu-west-2.aws.neon.tech
DATABASE_PORT=5432
DATABASE_USERNAME=neondb_owner
DATABASE_PASSWORD=$DB_PASSWORD
DATABASE_NAME=neondb
DATABASE_SSL=true
EOF

echo "Production DB config written to annix-backend/.env.prod-db"
echo "WARNING: You are now configured to connect to the LIVE production database!"
