# Fetches production database credentials from Fly.io and writes .env.prod-db
# Usage: .\setup-prod-db.ps1

Write-Host "Fetching production database credentials from Fly.io..." -ForegroundColor Cyan

$output = fly ssh console -a annix-app -C "printenv DATABASE_PASSWORD" 2>&1
$dbPassword = ($output | Where-Object { $_ -notmatch "^(Connecting|Warning|Error)" } | Select-Object -Last 1)
if ($dbPassword) { $dbPassword = $dbPassword.ToString().Trim() }

if (-not $dbPassword) {
    Write-Host "Failed to fetch DATABASE_PASSWORD from Fly.io. Make sure you are authenticated with 'fly auth login'." -ForegroundColor Red
    exit 1
}

$envContent = @"
# Production database overrides (auto-generated by setup-prod-db.ps1)
# WARNING: This connects to the LIVE production database. Be careful!
DATABASE_HOST=ep-polished-shape-abxr8muc.eu-west-2.aws.neon.tech
DATABASE_PORT=5432
DATABASE_USERNAME=neondb_owner
DATABASE_PASSWORD=$dbPassword
DATABASE_NAME=neondb
DATABASE_SSL=true
"@

$envPath = Join-Path $PSScriptRoot "annix-backend\.env.prod-db"
Set-Content -Path $envPath -Value $envContent -Encoding UTF8

Write-Host "Production DB config written to annix-backend\.env.prod-db" -ForegroundColor Green
Write-Host "WARNING: You are now configured to connect to the LIVE production database!" -ForegroundColor Yellow
