export const AUTH_CONSTANTS = {
  MAX_LOGIN_ATTEMPTS: 5,
  LOGIN_LOCKOUT_MINUTES: 15,
  SESSION_EXPIRY_HOURS: 1,
  REFRESH_TOKEN_EXPIRY_DAYS: 7,
  EMAIL_VERIFICATION_EXPIRY_HOURS: 24,
  ACCESS_TOKEN_EXPIRY: "1h",
  REFRESH_TOKEN_EXPIRY: "7d",
  ADMIN_ACCESS_TOKEN_EXPIRY: "4h",
  ADMIN_SESSION_EXPIRY_DAYS: 7,
} as const;
