export type {
  AdhesiveRecommendation,
  CureMethodRecommendation,
  DamageMechanismProfile,
  EquipmentGeometry,
  RecommendedRubberLining,
  RubberLiningRequirements,
  SANS1198ComplianceResult,
  SANS1198Requirements,
  SubstrateCondition,
  ThicknessOptimization,
  WearConditions,
  WearLifeEstimate,
} from "./rubberLiningRecommendations";
export {
  allRubberProducts,
  checkSANS1198Compliance,
  checkSANS1201Compliance,
  estimateWearLife,
  optimizeThickness,
  recommendCureMethod,
  recommendForCyclones,
  recommendForDryAbrasion,
  recommendForPipesAndChutes,
  recommendForWetSlurry,
  recommendRubberLining,
  rubberProductByCompoundCode,
  rubberProductById,
  selectAdhesiveSystem,
} from "./rubberLiningRecommendations";
export type {
  AbrasionResistance,
  HardnessClass,
  PolymerBase,
  RubberProduct,
  RubberSupplier,
  SANS1198Classification,
  SANS1198Grade,
  SANS1198Type,
} from "./rubberProducts";
export {
  bestAbrasionResistantProducts,
  highTensileProducts,
  rubberProducts,
  rubberProductsByHardness,
  rubberProductsByPolymer,
  rubberProductsBySANS1198Grade,
  rubberProductsBySANS1198Type,
  rubberProductsBySupplier,
  rubberProductsForAbrasion,
  rubberProductsForTemperature,
} from "./rubberProducts";
