export type ConsolidationContext = {
  consolidatedPipes: Map<string, any>;
  consolidatedBends: Map<string, any>;
  consolidatedFittings: Map<string, any>;
  consolidatedFlanges: Map<string, any>;
  consolidatedBnwSets: Map<string, any>;
  consolidatedGaskets: Map<string, any>;
  consolidatedBlankFlanges: Map<string, any>;
  consolidatedValves: Map<string, any>;
  consolidatedTanks: Map<string, any>;
  consolidatedFasteners: Map<string, any>;
  consolidatedUnidentified: Map<string, any>;
  consolidatedHdpeOther: Map<string, any>;
  consolidatedSteelOther: Map<string, any>;
  consolidatedPvcOther: Map<string, any>;
  consolidatedHdpeStubs: Map<string, any>;
  consolidatedPvcStubs: Map<string, any>;
  steelSpecLookup: any;
  flangeSpecLookup: any;
  globalHdpeSdr: any;
  globalHdpePressureRating: any;
  allWeights: any[];
  allBnwSets: any[];
  allGaskets: any[];
  globalSpecs: any;
  masterData: any;
  addHdpeStubItem: (...args: any[]) => void;
  addPvcStubItem: (...args: any[]) => void;
};
