import { MigrationInterface, QueryRunner } from 'typeorm';

export class UpdateSupplierCapabilitiesEnum1767900000000
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Add new enum values to match the frontend PRODUCTS_AND_SERVICES
    // The enum type name is auto-generated by TypeORM based on table and column name
    const enumTypeName = 'supplier_capabilities_product_category_enum';

    // Add new values to the enum
    await queryRunner.query(`
      ALTER TYPE ${enumTypeName} ADD VALUE IF NOT EXISTS 'fabricated_steel';
    `);
    await queryRunner.query(`
      ALTER TYPE ${enumTypeName} ADD VALUE IF NOT EXISTS 'fasteners_gaskets';
    `);
    await queryRunner.query(`
      ALTER TYPE ${enumTypeName} ADD VALUE IF NOT EXISTS 'surface_protection';
    `);
    await queryRunner.query(`
      ALTER TYPE ${enumTypeName} ADD VALUE IF NOT EXISTS 'transport_install';
    `);
    // pvc is already in the entity but might be missing from migration
    await queryRunner.query(`
      ALTER TYPE ${enumTypeName} ADD VALUE IF NOT EXISTS 'pvc';
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Note: PostgreSQL doesn't support removing enum values directly
    // To remove, you'd need to create a new enum without the values and migrate data
    // This is intentionally left as a no-op for safety
    console.log(
      'Note: Enum values cannot be easily removed in PostgreSQL. Manual intervention required if needed.',
    );
  }
}
