import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateMaterialPropertiesAndMtcTables1796200000000 implements MigrationInterface {
  name = "CreateMaterialPropertiesAndMtcTables1796200000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
			CREATE TABLE IF NOT EXISTS material_mechanical_properties (
				id SERIAL PRIMARY KEY,
				specification_code VARCHAR(50) NOT NULL,
				grade VARCHAR(20) NOT NULL,
				uns_number VARCHAR(10),
				p_number VARCHAR(10),
				group_number VARCHAR(10),
				smys_mpa INT,
				smts_mpa INT,
				elongation_pct_min DECIMAL(4,1),
				carbon_equivalent_max DECIMAL(4,3),
				ce_formula VARCHAR(10),
				impact_test_temp_c INT,
				min_impact_j INT,
				hardness_max_hrc INT,
				hardness_max_hv INT,
				applicable_standards TEXT,
				notes TEXT,
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				UNIQUE(specification_code, grade)
			)
		`);

    await queryRunner.query(`
			CREATE TABLE IF NOT EXISTS impact_test_results (
				id SERIAL PRIMARY KEY,
				heat_number VARCHAR(50),
				mtc_reference VARCHAR(100),
				test_temp_c INT NOT NULL,
				specimen_size VARCHAR(20),
				specimen_orientation VARCHAR(5),
				impact_value_1_j DECIMAL(6,1) NOT NULL,
				impact_value_2_j DECIMAL(6,1) NOT NULL,
				impact_value_3_j DECIMAL(6,1) NOT NULL,
				impact_average_j DECIMAL(6,1) NOT NULL,
				required_avg_j INT,
				required_min_j INT,
				passed BOOLEAN DEFAULT TRUE,
				rfq_item_id INT REFERENCES rfq_items(id) ON DELETE SET NULL,
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
			)
		`);

    await queryRunner.query(`
			CREATE TABLE IF NOT EXISTS hardness_test_results (
				id SERIAL PRIMARY KEY,
				heat_number VARCHAR(50),
				mtc_reference VARCHAR(100),
				test_location VARCHAR(30),
				hardness_hrc DECIMAL(4,1),
				hardness_hv INT,
				hardness_hb INT,
				max_allowed_hrc DECIMAL(4,1),
				max_allowed_hv INT,
				passed BOOLEAN DEFAULT TRUE,
				rfq_item_id INT REFERENCES rfq_items(id) ON DELETE SET NULL,
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
			)
		`);

    await queryRunner.query(`
			CREATE TABLE IF NOT EXISTS material_test_certificates (
				id SERIAL PRIMARY KEY,
				mtc_number VARCHAR(100) NOT NULL,
				mtc_type VARCHAR(5),
				manufacturer VARCHAR(100),
				heat_number VARCHAR(50) NOT NULL,
				lot_number VARCHAR(50),
				specification VARCHAR(50) NOT NULL,
				grade VARCHAR(20) NOT NULL,
				size VARCHAR(50),
				quantity INT,
				c_pct DECIMAL(5,3),
				mn_pct DECIMAL(5,3),
				p_pct DECIMAL(5,4),
				s_pct DECIMAL(5,4),
				si_pct DECIMAL(5,3),
				cr_pct DECIMAL(5,3),
				mo_pct DECIMAL(5,3),
				ni_pct DECIMAL(5,3),
				v_pct DECIMAL(5,4),
				cu_pct DECIMAL(5,3),
				nb_pct DECIMAL(5,4),
				ti_pct DECIMAL(5,4),
				al_pct DECIMAL(5,4),
				n_pct DECIMAL(5,4),
				b_pct DECIMAL(6,5),
				carbon_equivalent DECIMAL(4,3),
				ce_formula_used VARCHAR(10),
				yield_strength_mpa DECIMAL(7,2),
				tensile_strength_mpa DECIMAL(7,2),
				elongation_pct DECIMAL(5,2),
				reduction_area_pct DECIMAL(5,2),
				impact_test_temp_c INT,
				impact_specimen_size VARCHAR(20),
				impact_values_j JSONB,
				impact_average_j DECIMAL(6,1),
				hardness_hrc DECIMAL(4,1),
				hardness_hv INT,
				hardness_hb INT,
				ndt_methods_performed JSONB,
				ndt_results TEXT,
				hydro_test_pressure_bar DECIMAL(7,2),
				hydro_test_result VARCHAR(20),
				psl_level VARCHAR(5),
				nace_compliant BOOLEAN,
				dnv_compliant BOOLEAN,
				third_party_inspection BOOLEAN,
				inspector_name VARCHAR(100),
				certificate_date DATE,
				rfq_item_id INT REFERENCES rfq_items(id) ON DELETE SET NULL,
				created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
				updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
			)
		`);

    await queryRunner.query(`
			CREATE INDEX IF NOT EXISTS idx_impact_test_heat_number ON impact_test_results(heat_number);
			CREATE INDEX IF NOT EXISTS idx_impact_test_mtc_ref ON impact_test_results(mtc_reference);
			CREATE INDEX IF NOT EXISTS idx_hardness_test_heat_number ON hardness_test_results(heat_number);
			CREATE INDEX IF NOT EXISTS idx_hardness_test_mtc_ref ON hardness_test_results(mtc_reference);
			CREATE INDEX IF NOT EXISTS idx_mtc_number ON material_test_certificates(mtc_number);
			CREATE INDEX IF NOT EXISTS idx_mtc_heat_number ON material_test_certificates(heat_number);
			CREATE INDEX IF NOT EXISTS idx_mtc_lot_number ON material_test_certificates(lot_number);
		`);

    await this.seedMaterialMechanicalProperties(queryRunner);
    console.log("Material properties and MTC tables created successfully.");
  }

  private async seedMaterialMechanicalProperties(queryRunner: QueryRunner): Promise<void> {
    const materials = [
      {
        specificationCode: "ASTM_A106",
        grade: "A",
        unsNumber: "K02501",
        pNumber: "1",
        groupNumber: "1",
        smysMpa: 205,
        smtsMpa: 330,
        elongationPctMin: 25,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3, ASME B31.1",
      },
      {
        specificationCode: "ASTM_A106",
        grade: "B",
        unsNumber: "K03006",
        pNumber: "1",
        groupNumber: "2",
        smysMpa: 240,
        smtsMpa: 415,
        elongationPctMin: 21,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3, ASME B31.1",
      },
      {
        specificationCode: "ASTM_A106",
        grade: "C",
        unsNumber: "K03501",
        pNumber: "1",
        groupNumber: "2",
        smysMpa: 275,
        smtsMpa: 485,
        elongationPctMin: 18,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3, ASME B31.1",
      },
      {
        specificationCode: "ASTM_A333",
        grade: "6",
        unsNumber: "K03006",
        pNumber: "1",
        groupNumber: "1",
        smysMpa: 240,
        smtsMpa: 415,
        elongationPctMin: 21,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: -45,
        minImpactJ: 18,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3 Low-Temp Service",
      },
      {
        specificationCode: "ASTM_A312",
        grade: "TP304",
        unsNumber: "S30400",
        pNumber: "8",
        groupNumber: "1",
        smysMpa: 205,
        smtsMpa: 515,
        elongationPctMin: 35,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3",
      },
      {
        specificationCode: "ASTM_A312",
        grade: "TP304L",
        unsNumber: "S30403",
        pNumber: "8",
        groupNumber: "1",
        smysMpa: 170,
        smtsMpa: 485,
        elongationPctMin: 35,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3",
      },
      {
        specificationCode: "ASTM_A312",
        grade: "TP316",
        unsNumber: "S31600",
        pNumber: "8",
        groupNumber: "1",
        smysMpa: 205,
        smtsMpa: 515,
        elongationPctMin: 35,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3",
      },
      {
        specificationCode: "ASTM_A312",
        grade: "TP316L",
        unsNumber: "S31603",
        pNumber: "8",
        groupNumber: "1",
        smysMpa: 170,
        smtsMpa: 485,
        elongationPctMin: 35,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3",
      },
      {
        specificationCode: "ASTM_A335",
        grade: "P11",
        unsNumber: "K11597",
        pNumber: "4",
        groupNumber: "1",
        smysMpa: 205,
        smtsMpa: 415,
        elongationPctMin: 22,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3, High Temp Service",
      },
      {
        specificationCode: "ASTM_A335",
        grade: "P22",
        unsNumber: "K21590",
        pNumber: "5A",
        groupNumber: "1",
        smysMpa: 205,
        smtsMpa: 415,
        elongationPctMin: 22,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: null,
        minImpactJ: null,
        hardnessMaxHrc: null,
        hardnessMaxHv: null,
        applicableStandards: "ASME B31.3, High Temp Service",
      },
      {
        specificationCode: "ASTM_A790",
        grade: "S31803",
        unsNumber: "S31803",
        pNumber: "10H",
        groupNumber: "1",
        smysMpa: 450,
        smtsMpa: 620,
        elongationPctMin: 25,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: -40,
        minImpactJ: 45,
        hardnessMaxHrc: 28,
        hardnessMaxHv: 290,
        applicableStandards: "ASME B31.3, Duplex 2205",
      },
      {
        specificationCode: "ASTM_A790",
        grade: "S32205",
        unsNumber: "S32205",
        pNumber: "10H",
        groupNumber: "1",
        smysMpa: 450,
        smtsMpa: 655,
        elongationPctMin: 25,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: -40,
        minImpactJ: 45,
        hardnessMaxHrc: 28,
        hardnessMaxHv: 290,
        applicableStandards: "ASME B31.3, Duplex 2205",
      },
      {
        specificationCode: "ASTM_A790",
        grade: "S32750",
        unsNumber: "S32750",
        pNumber: "10H",
        groupNumber: "1",
        smysMpa: 550,
        smtsMpa: 795,
        elongationPctMin: 15,
        carbonEquivalentMax: null,
        ceFormula: null,
        impactTestTempC: -40,
        minImpactJ: 45,
        hardnessMaxHrc: 32,
        hardnessMaxHv: 310,
        applicableStandards: "ASME B31.3, Super Duplex 2507",
      },
      {
        specificationCode: "API_5L",
        grade: "B_PSL2",
        unsNumber: null,
        pNumber: "1",
        groupNumber: "2",
        smysMpa: 245,
        smtsMpa: 415,
        elongationPctMin: 21,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: 0,
        minImpactJ: 27,
        hardnessMaxHrc: 22,
        hardnessMaxHv: 248,
        applicableStandards: "API 5L, NACE MR0175 (sour service)",
      },
      {
        specificationCode: "API_5L",
        grade: "X42_PSL2",
        unsNumber: null,
        pNumber: "1",
        groupNumber: "2",
        smysMpa: 290,
        smtsMpa: 415,
        elongationPctMin: 21,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: 0,
        minImpactJ: 27,
        hardnessMaxHrc: 22,
        hardnessMaxHv: 248,
        applicableStandards: "API 5L, NACE MR0175 (sour service)",
      },
      {
        specificationCode: "API_5L",
        grade: "X52_PSL2",
        unsNumber: null,
        pNumber: "1",
        groupNumber: "2",
        smysMpa: 360,
        smtsMpa: 460,
        elongationPctMin: 21,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: 0,
        minImpactJ: 27,
        hardnessMaxHrc: 22,
        hardnessMaxHv: 248,
        applicableStandards: "API 5L, NACE MR0175 (sour service)",
      },
      {
        specificationCode: "API_5L",
        grade: "X60_PSL2",
        unsNumber: null,
        pNumber: "1",
        groupNumber: "3",
        smysMpa: 415,
        smtsMpa: 520,
        elongationPctMin: 19,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: 0,
        minImpactJ: 27,
        hardnessMaxHrc: 22,
        hardnessMaxHv: 248,
        applicableStandards: "API 5L, NACE MR0175 (sour service)",
      },
      {
        specificationCode: "API_5L",
        grade: "X65_PSL2",
        unsNumber: null,
        pNumber: "1",
        groupNumber: "3",
        smysMpa: 450,
        smtsMpa: 535,
        elongationPctMin: 18,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: 0,
        minImpactJ: 27,
        hardnessMaxHrc: 22,
        hardnessMaxHv: 248,
        applicableStandards: "API 5L, NACE MR0175 (sour service)",
      },
      {
        specificationCode: "API_5L",
        grade: "X70_PSL2",
        unsNumber: null,
        pNumber: "1",
        groupNumber: "3",
        smysMpa: 485,
        smtsMpa: 570,
        elongationPctMin: 17,
        carbonEquivalentMax: 0.43,
        ceFormula: "IIW",
        impactTestTempC: 0,
        minImpactJ: 40,
        hardnessMaxHrc: 22,
        hardnessMaxHv: 248,
        applicableStandards: "API 5L, NACE MR0175 (sour service)",
      },
    ];

    for (const mat of materials) {
      await queryRunner.query(`
				INSERT INTO material_mechanical_properties
					(specification_code, grade, uns_number, p_number, group_number, smys_mpa, smts_mpa,
					 elongation_pct_min, carbon_equivalent_max, ce_formula, impact_test_temp_c, min_impact_j,
					 hardness_max_hrc, hardness_max_hv, applicable_standards)
				VALUES
					('${mat.specificationCode}', '${mat.grade}', ${mat.unsNumber ? `'${mat.unsNumber}'` : "NULL"},
					 ${mat.pNumber ? `'${mat.pNumber}'` : "NULL"}, ${mat.groupNumber ? `'${mat.groupNumber}'` : "NULL"},
					 ${mat.smysMpa}, ${mat.smtsMpa}, ${mat.elongationPctMin},
					 ${mat.carbonEquivalentMax ?? "NULL"}, ${mat.ceFormula ? `'${mat.ceFormula}'` : "NULL"},
					 ${mat.impactTestTempC ?? "NULL"}, ${mat.minImpactJ ?? "NULL"},
					 ${mat.hardnessMaxHrc ?? "NULL"}, ${mat.hardnessMaxHv ?? "NULL"},
					 '${mat.applicableStandards}')
				ON CONFLICT (specification_code, grade) DO NOTHING
			`);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("DROP TABLE IF EXISTS material_test_certificates");
    await queryRunner.query("DROP TABLE IF EXISTS hardness_test_results");
    await queryRunner.query("DROP TABLE IF EXISTS impact_test_results");
    await queryRunner.query("DROP TABLE IF EXISTS material_mechanical_properties");
  }
}
