import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateSteelStandardsTables1796000000000 implements MigrationInterface {
  name = "CreateSteelStandardsTables1796000000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS api5l_grades (
        id SERIAL PRIMARY KEY,
        grade VARCHAR(10) NOT NULL,
        psl_level VARCHAR(5) NOT NULL,
        smys_mpa INT NOT NULL,
        smts_mpa INT NOT NULL,
        elongation_pct_min DECIMAL(4,1) NOT NULL,
        cvn_temp_c INT,
        cvn_avg_j INT,
        cvn_min_j INT,
        carbon_max_pct DECIMAL(4,3) NOT NULL,
        manganese_max_pct DECIMAL(4,2) NOT NULL,
        phosphorus_max_pct DECIMAL(5,4) NOT NULL,
        sulfur_max_pct DECIMAL(5,4) NOT NULL,
        ceq_max DECIMAL(4,3),
        ndt_coverage_pct INT NOT NULL,
        heat_traceability_required BOOLEAN DEFAULT FALSE,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(grade, psl_level)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS pipe_tolerances (
        id SERIAL PRIMARY KEY,
        standard VARCHAR(20) NOT NULL,
        nps_min_mm INT NOT NULL,
        nps_max_mm INT NOT NULL,
        od_tolerance_pct DECIMAL(4,2) NOT NULL,
        od_tolerance_mm_max DECIMAL(5,2),
        wall_tolerance_pct_under DECIMAL(4,2) NOT NULL,
        wall_tolerance_pct_over DECIMAL(4,2),
        length_srl_plus_mm DECIMAL(6,1) NOT NULL,
        length_srl_minus_mm DECIMAL(6,1) NOT NULL,
        length_drl_plus_mm DECIMAL(6,1) NOT NULL,
        length_drl_minus_mm DECIMAL(6,1) NOT NULL,
        straightness_ratio INT NOT NULL,
        weight_tolerance_pct DECIMAL(4,2) NOT NULL,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(standard, nps_min_mm, nps_max_mm)
      )
    `);

    await queryRunner.query("DROP TABLE IF EXISTS pipe_end_preparations");

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS pipe_end_preparations (
        id SERIAL PRIMARY KEY,
        prep_type VARCHAR(20) NOT NULL,
        display_name VARCHAR(50) NOT NULL,
        bevel_angle_deg DECIMAL(4,1) NOT NULL,
        bevel_angle_tol_deg DECIMAL(3,1) NOT NULL,
        secondary_angle_deg DECIMAL(4,1),
        root_face_mm DECIMAL(4,2) NOT NULL,
        root_face_tol_mm DECIMAL(4,2) NOT NULL,
        root_gap_mm_min DECIMAL(4,2) NOT NULL,
        root_gap_mm_max DECIMAL(4,2) NOT NULL,
        land_mm DECIMAL(4,2),
        wall_thickness_min_mm DECIMAL(5,2) NOT NULL,
        wall_thickness_max_mm DECIMAL(5,2) NOT NULL,
        applicable_codes VARCHAR(100),
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(prep_type, wall_thickness_min_mm)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS weld_defect_acceptance (
        id SERIAL PRIMARY KEY,
        code VARCHAR(20) NOT NULL,
        code_display_name VARCHAR(50) NOT NULL,
        defect_type VARCHAR(30) NOT NULL,
        defect_display_name VARCHAR(50) NOT NULL,
        max_dimension_mm DECIMAL(5,2),
        max_dimension_pct_t DECIMAL(5,2),
        spacing_requirement VARCHAR(100),
        cumulative_limit VARCHAR(100),
        repair_limit INT,
        permitted BOOLEAN DEFAULT TRUE,
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(code, defect_type)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS hydrotest_requirements (
        id SERIAL PRIMARY KEY,
        code VARCHAR(20) NOT NULL UNIQUE,
        code_display_name VARCHAR(100) NOT NULL,
        test_pressure_multiplier DECIMAL(4,2) NOT NULL,
        test_pressure_formula VARCHAR(100) NOT NULL,
        hold_time_minutes INT NOT NULL,
        hold_time_per_mm_wall DECIMAL(4,2),
        volume_loss_max_pct DECIMAL(4,2) NOT NULL,
        temperature_min_c INT NOT NULL,
        medium VARCHAR(20) NOT NULL,
        pneumatic_allowed BOOLEAN DEFAULT FALSE,
        pneumatic_multiplier DECIMAL(4,2),
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS ndt_method_requirements (
        id SERIAL PRIMARY KEY,
        method VARCHAR(10) NOT NULL,
        method_display_name VARCHAR(50) NOT NULL,
        astm_standard VARCHAR(20) NOT NULL,
        application VARCHAR(20) NOT NULL,
        application_display_name VARCHAR(50) NOT NULL,
        coverage_psl1_pct INT NOT NULL,
        coverage_psl2_pct INT NOT NULL,
        acceptance_criteria_ref VARCHAR(100) NOT NULL,
        equipment_requirements TEXT,
        operator_cert_level VARCHAR(20) NOT NULL,
        defects_detected VARCHAR(200),
        notes TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(method, application)
      )
    `);

    await this.seedApi5lGrades(queryRunner);
    await this.seedPipeTolerances(queryRunner);
    await this.seedPipeEndPreparations(queryRunner);
    await this.seedWeldDefectAcceptance(queryRunner);
    await this.seedHydrotestRequirements(queryRunner);
    await this.seedNdtMethodRequirements(queryRunner);

    console.log("Steel standards tables created and seeded successfully.");
  }

  private async seedApi5lGrades(queryRunner: QueryRunner): Promise<void> {
    const grades = [
      {
        grade: "B",
        pslLevel: "PSL1",
        smysMpa: 245,
        smtsMpa: 415,
        elongPct: 21,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.2,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "B",
        pslLevel: "PSL2",
        smysMpa: 245,
        smtsMpa: 415,
        elongPct: 21,
        cvnTempC: 0,
        cvnAvgJ: 27,
        cvnMinJ: 20,
        carbonMax: 0.18,
        mnMax: 1.2,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X42",
        pslLevel: "PSL1",
        smysMpa: 290,
        smtsMpa: 415,
        elongPct: 21,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.3,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X42",
        pslLevel: "PSL2",
        smysMpa: 290,
        smtsMpa: 415,
        elongPct: 21,
        cvnTempC: 0,
        cvnAvgJ: 27,
        cvnMinJ: 20,
        carbonMax: 0.18,
        mnMax: 1.3,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X46",
        pslLevel: "PSL1",
        smysMpa: 320,
        smtsMpa: 435,
        elongPct: 21,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.4,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X46",
        pslLevel: "PSL2",
        smysMpa: 320,
        smtsMpa: 435,
        elongPct: 21,
        cvnTempC: 0,
        cvnAvgJ: 27,
        cvnMinJ: 20,
        carbonMax: 0.18,
        mnMax: 1.4,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X52",
        pslLevel: "PSL1",
        smysMpa: 360,
        smtsMpa: 460,
        elongPct: 21,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.4,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X52",
        pslLevel: "PSL2",
        smysMpa: 360,
        smtsMpa: 460,
        elongPct: 21,
        cvnTempC: 0,
        cvnAvgJ: 27,
        cvnMinJ: 20,
        carbonMax: 0.18,
        mnMax: 1.4,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X56",
        pslLevel: "PSL1",
        smysMpa: 390,
        smtsMpa: 490,
        elongPct: 19,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.4,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X56",
        pslLevel: "PSL2",
        smysMpa: 390,
        smtsMpa: 490,
        elongPct: 19,
        cvnTempC: 0,
        cvnAvgJ: 27,
        cvnMinJ: 20,
        carbonMax: 0.22,
        mnMax: 1.4,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X60",
        pslLevel: "PSL1",
        smysMpa: 415,
        smtsMpa: 520,
        elongPct: 19,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.4,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X60",
        pslLevel: "PSL2",
        smysMpa: 415,
        smtsMpa: 520,
        elongPct: 19,
        cvnTempC: 0,
        cvnAvgJ: 27,
        cvnMinJ: 20,
        carbonMax: 0.22,
        mnMax: 1.4,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X65",
        pslLevel: "PSL1",
        smysMpa: 450,
        smtsMpa: 535,
        elongPct: 18,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.45,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X65",
        pslLevel: "PSL2",
        smysMpa: 450,
        smtsMpa: 535,
        elongPct: 18,
        cvnTempC: 0,
        cvnAvgJ: 27,
        cvnMinJ: 20,
        carbonMax: 0.22,
        mnMax: 1.45,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X70",
        pslLevel: "PSL1",
        smysMpa: 485,
        smtsMpa: 570,
        elongPct: 17,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.65,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X70",
        pslLevel: "PSL2",
        smysMpa: 485,
        smtsMpa: 570,
        elongPct: 17,
        cvnTempC: 0,
        cvnAvgJ: 40,
        cvnMinJ: 30,
        carbonMax: 0.22,
        mnMax: 1.65,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
      {
        grade: "X80",
        pslLevel: "PSL1",
        smysMpa: 555,
        smtsMpa: 625,
        elongPct: 16,
        cvnTempC: null,
        cvnAvgJ: null,
        cvnMinJ: null,
        carbonMax: 0.28,
        mnMax: 1.85,
        pMax: 0.03,
        sMax: 0.03,
        ceqMax: null,
        ndtPct: 10,
        heatTrace: false,
      },
      {
        grade: "X80",
        pslLevel: "PSL2",
        smysMpa: 555,
        smtsMpa: 625,
        elongPct: 16,
        cvnTempC: -10,
        cvnAvgJ: 40,
        cvnMinJ: 30,
        carbonMax: 0.22,
        mnMax: 1.85,
        pMax: 0.015,
        sMax: 0.015,
        ceqMax: 0.43,
        ndtPct: 100,
        heatTrace: true,
      },
    ];

    for (const g of grades) {
      await queryRunner.query(`
        INSERT INTO api5l_grades (grade, psl_level, smys_mpa, smts_mpa, elongation_pct_min, cvn_temp_c, cvn_avg_j, cvn_min_j, carbon_max_pct, manganese_max_pct, phosphorus_max_pct, sulfur_max_pct, ceq_max, ndt_coverage_pct, heat_traceability_required)
        VALUES ('${g.grade}', '${g.pslLevel}', ${g.smysMpa}, ${g.smtsMpa}, ${g.elongPct}, ${g.cvnTempC ?? "NULL"}, ${g.cvnAvgJ ?? "NULL"}, ${g.cvnMinJ ?? "NULL"}, ${g.carbonMax}, ${g.mnMax}, ${g.pMax}, ${g.sMax}, ${g.ceqMax ?? "NULL"}, ${g.ndtPct}, ${g.heatTrace})
      `);
    }
  }

  private async seedPipeTolerances(queryRunner: QueryRunner): Promise<void> {
    const tolerances = [
      {
        standard: "ASME B36.10M",
        npsMin: 15,
        npsMax: 450,
        odPct: 0.4,
        odMmMax: null,
        wallUnder: 12.5,
        wallOver: null,
        srlPlus: 152.4,
        srlMinus: 0,
        drlPlus: 76.2,
        drlMinus: 0,
        straightness: 2000,
        weightPct: 3.5,
      },
      {
        standard: "ASME B36.10M",
        npsMin: 500,
        npsMax: 1500,
        odPct: 0.8,
        odMmMax: 12.5,
        wallUnder: 12.5,
        wallOver: null,
        srlPlus: 76.2,
        srlMinus: 0,
        drlPlus: 76.2,
        drlMinus: 0,
        straightness: 2000,
        weightPct: 3.5,
      },
      {
        standard: "ASME B36.19M",
        npsMin: 15,
        npsMax: 300,
        odPct: 0.5,
        odMmMax: null,
        wallUnder: 12.5,
        wallOver: 12.5,
        srlPlus: 152.4,
        srlMinus: 0,
        drlPlus: 76.2,
        drlMinus: 0,
        straightness: 2000,
        weightPct: 5.0,
      },
      {
        standard: "ASME B36.19M",
        npsMin: 350,
        npsMax: 750,
        odPct: 1.0,
        odMmMax: null,
        wallUnder: 12.5,
        wallOver: 12.5,
        srlPlus: 152.4,
        srlMinus: 0,
        drlPlus: 76.2,
        drlMinus: 0,
        straightness: 2000,
        weightPct: 5.0,
      },
      {
        standard: "API 5L",
        npsMin: 15,
        npsMax: 450,
        odPct: 0.5,
        odMmMax: null,
        wallUnder: 12.5,
        wallOver: 15.0,
        srlPlus: 152.4,
        srlMinus: 0,
        drlPlus: 152.4,
        drlMinus: 0,
        straightness: 2000,
        weightPct: 3.5,
      },
      {
        standard: "API 5L",
        npsMin: 500,
        npsMax: 1500,
        odPct: 0.75,
        odMmMax: 9.5,
        wallUnder: 12.5,
        wallOver: 15.0,
        srlPlus: 152.4,
        srlMinus: 0,
        drlPlus: 152.4,
        drlMinus: 0,
        straightness: 2000,
        weightPct: 3.5,
      },
    ];

    for (const t of tolerances) {
      await queryRunner.query(`
        INSERT INTO pipe_tolerances (standard, nps_min_mm, nps_max_mm, od_tolerance_pct, od_tolerance_mm_max, wall_tolerance_pct_under, wall_tolerance_pct_over, length_srl_plus_mm, length_srl_minus_mm, length_drl_plus_mm, length_drl_minus_mm, straightness_ratio, weight_tolerance_pct)
        VALUES ('${t.standard}', ${t.npsMin}, ${t.npsMax}, ${t.odPct}, ${t.odMmMax ?? "NULL"}, ${t.wallUnder}, ${t.wallOver ?? "NULL"}, ${t.srlPlus}, ${t.srlMinus}, ${t.drlPlus}, ${t.drlMinus}, ${t.straightness}, ${t.weightPct})
      `);
    }
  }

  private async seedPipeEndPreparations(queryRunner: QueryRunner): Promise<void> {
    const preps = [
      {
        prepType: "SQUARE",
        displayName: "Square End (Thin Wall)",
        bevelAngle: 0,
        bevelTol: 0,
        secondaryAngle: null,
        rootFace: 0,
        rootFaceTol: 0,
        rootGapMin: 1.6,
        rootGapMax: 2.4,
        land: null,
        wallMin: 0,
        wallMax: 3.0,
        codes: "ASME B31.3, AWS D1.1",
      },
      {
        prepType: "V_BEVEL",
        displayName: "V-Bevel (Standard)",
        bevelAngle: 37.5,
        bevelTol: 2.5,
        secondaryAngle: null,
        rootFace: 1.6,
        rootFaceTol: 0.8,
        rootGapMin: 1.6,
        rootGapMax: 3.2,
        land: null,
        wallMin: 3.0,
        wallMax: 22.0,
        codes: "ASME B31.3, API 1104",
      },
      {
        prepType: "V_BEVEL_30",
        displayName: "V-Bevel (30 Degree)",
        bevelAngle: 30.0,
        bevelTol: 5.0,
        secondaryAngle: null,
        rootFace: 1.6,
        rootFaceTol: 0.8,
        rootGapMin: 1.6,
        rootGapMax: 3.2,
        land: null,
        wallMin: 3.0,
        wallMax: 22.0,
        codes: "API 1104",
      },
      {
        prepType: "COMPOUND",
        displayName: "Compound Bevel",
        bevelAngle: 37.5,
        bevelTol: 2.5,
        secondaryAngle: 10.0,
        rootFace: 1.6,
        rootFaceTol: 0.8,
        rootGapMin: 2.4,
        rootGapMax: 4.0,
        land: null,
        wallMin: 22.0,
        wallMax: 50.0,
        codes: "ASME B31.3",
      },
      {
        prepType: "J_PREP",
        displayName: "J-Prep (Heavy Wall)",
        bevelAngle: 37.5,
        bevelTol: 2.5,
        secondaryAngle: 10.0,
        rootFace: 3.2,
        rootFaceTol: 1.6,
        rootGapMin: 2.4,
        rootGapMax: 4.0,
        land: 3.2,
        wallMin: 25.0,
        wallMax: 100.0,
        codes: "ASME B31.3",
      },
      {
        prepType: "U_PREP",
        displayName: "U-Prep (Very Heavy Wall)",
        bevelAngle: 20.0,
        bevelTol: 2.5,
        secondaryAngle: null,
        rootFace: 3.2,
        rootFaceTol: 1.6,
        rootGapMin: 2.4,
        rootGapMax: 4.0,
        land: 6.4,
        wallMin: 50.0,
        wallMax: 200.0,
        codes: "ASME B31.3",
      },
    ];

    for (const p of preps) {
      await queryRunner.query(`
        INSERT INTO pipe_end_preparations (prep_type, display_name, bevel_angle_deg, bevel_angle_tol_deg, secondary_angle_deg, root_face_mm, root_face_tol_mm, root_gap_mm_min, root_gap_mm_max, land_mm, wall_thickness_min_mm, wall_thickness_max_mm, applicable_codes)
        VALUES ('${p.prepType}', '${p.displayName}', ${p.bevelAngle}, ${p.bevelTol}, ${p.secondaryAngle ?? "NULL"}, ${p.rootFace}, ${p.rootFaceTol}, ${p.rootGapMin}, ${p.rootGapMax}, ${p.land ?? "NULL"}, ${p.wallMin}, ${p.wallMax}, '${p.codes}')
      `);
    }
  }

  private async seedWeldDefectAcceptance(queryRunner: QueryRunner): Promise<void> {
    const defects = [
      {
        code: "API_1104",
        codeDisplay: "API 1104",
        defectType: "UNDERCUT",
        defectDisplay: "Undercut",
        maxMm: 0.8,
        maxPctT: 12.5,
        spacing: null,
        cumulative: "Aggregate length <= 50mm in any 300mm",
        repairLimit: 2,
        permitted: true,
      },
      {
        code: "API_1104",
        codeDisplay: "API 1104",
        defectType: "POROSITY",
        defectDisplay: "Porosity",
        maxMm: 3.2,
        maxPctT: 25,
        spacing: "6x diameter minimum spacing",
        cumulative: "Train <= 25% circumference",
        repairLimit: 2,
        permitted: true,
      },
      {
        code: "API_1104",
        codeDisplay: "API 1104",
        defectType: "SLAG",
        defectDisplay: "Slag Inclusion",
        maxMm: 3.2,
        maxPctT: null,
        spacing: "50mm minimum spacing",
        cumulative: "Aggregate <= 50mm in any 300mm",
        repairLimit: 2,
        permitted: true,
      },
      {
        code: "API_1104",
        codeDisplay: "API 1104",
        defectType: "CRACK",
        defectDisplay: "Crack",
        maxMm: null,
        maxPctT: null,
        spacing: null,
        cumulative: null,
        repairLimit: null,
        permitted: false,
      },
      {
        code: "API_1104",
        codeDisplay: "API 1104",
        defectType: "INCOMPLETE_FUSION",
        defectDisplay: "Incomplete Fusion",
        maxMm: 25.0,
        maxPctT: null,
        spacing: "50mm minimum spacing",
        cumulative: "Aggregate <= 25mm in any 300mm",
        repairLimit: 2,
        permitted: true,
      },
      {
        code: "API_1104",
        codeDisplay: "API 1104",
        defectType: "INCOMPLETE_PENETRATION",
        defectDisplay: "Incomplete Penetration",
        maxMm: 25.0,
        maxPctT: null,
        spacing: "50mm minimum spacing",
        cumulative: "Aggregate <= 25mm in any 300mm",
        repairLimit: 2,
        permitted: true,
      },
      {
        code: "API_1104",
        codeDisplay: "API 1104",
        defectType: "BURN_THROUGH",
        defectDisplay: "Burn-Through",
        maxMm: 6.0,
        maxPctT: null,
        spacing: null,
        cumulative: null,
        repairLimit: 2,
        permitted: true,
      },
      {
        code: "ASME_B31.3",
        codeDisplay: "ASME B31.3",
        defectType: "UNDERCUT",
        defectDisplay: "Undercut",
        maxMm: 0.8,
        maxPctT: 10,
        spacing: null,
        cumulative: null,
        repairLimit: null,
        permitted: true,
      },
      {
        code: "ASME_B31.3",
        codeDisplay: "ASME B31.3",
        defectType: "POROSITY",
        defectDisplay: "Porosity",
        maxMm: 1.6,
        maxPctT: null,
        spacing: "6x diameter minimum spacing",
        cumulative: "Scattered only",
        repairLimit: null,
        permitted: true,
      },
      {
        code: "ASME_B31.3",
        codeDisplay: "ASME B31.3",
        defectType: "SLAG",
        defectDisplay: "Slag Inclusion",
        maxMm: null,
        maxPctT: null,
        spacing: null,
        cumulative: "Occasional isolated",
        repairLimit: null,
        permitted: true,
      },
      {
        code: "ASME_B31.3",
        codeDisplay: "ASME B31.3",
        defectType: "CRACK",
        defectDisplay: "Crack",
        maxMm: null,
        maxPctT: null,
        spacing: null,
        cumulative: null,
        repairLimit: null,
        permitted: false,
      },
      {
        code: "ASME_B31.3",
        codeDisplay: "ASME B31.3",
        defectType: "INCOMPLETE_FUSION",
        defectDisplay: "Incomplete Fusion",
        maxMm: null,
        maxPctT: null,
        spacing: null,
        cumulative: null,
        repairLimit: null,
        permitted: false,
      },
      {
        code: "ASME_B31.3",
        codeDisplay: "ASME B31.3",
        defectType: "INCOMPLETE_PENETRATION",
        defectDisplay: "Incomplete Penetration",
        maxMm: null,
        maxPctT: null,
        spacing: null,
        cumulative: null,
        repairLimit: null,
        permitted: false,
      },
      {
        code: "AWS_D1.1",
        codeDisplay: "AWS D1.1",
        defectType: "UNDERCUT",
        defectDisplay: "Undercut",
        maxMm: 1.0,
        maxPctT: null,
        spacing: null,
        cumulative: "50mm aggregate per 300mm",
        repairLimit: null,
        permitted: true,
      },
      {
        code: "AWS_D1.1",
        codeDisplay: "AWS D1.1",
        defectType: "POROSITY",
        defectDisplay: "Porosity",
        maxMm: null,
        maxPctT: null,
        spacing: null,
        cumulative: "Sum <= 10mm in any 25mm",
        repairLimit: null,
        permitted: true,
      },
      {
        code: "AWS_D1.1",
        codeDisplay: "AWS D1.1",
        defectType: "CRACK",
        defectDisplay: "Crack",
        maxMm: null,
        maxPctT: null,
        spacing: null,
        cumulative: null,
        repairLimit: null,
        permitted: false,
      },
    ];

    for (const d of defects) {
      await queryRunner.query(`
        INSERT INTO weld_defect_acceptance (code, code_display_name, defect_type, defect_display_name, max_dimension_mm, max_dimension_pct_t, spacing_requirement, cumulative_limit, repair_limit, permitted)
        VALUES ('${d.code}', '${d.codeDisplay}', '${d.defectType}', '${d.defectDisplay}', ${d.maxMm ?? "NULL"}, ${d.maxPctT ?? "NULL"}, ${d.spacing ? `'${d.spacing}'` : "NULL"}, ${d.cumulative ? `'${d.cumulative}'` : "NULL"}, ${d.repairLimit ?? "NULL"}, ${d.permitted})
      `);
    }
  }

  private async seedHydrotestRequirements(queryRunner: QueryRunner): Promise<void> {
    const requirements = [
      {
        code: "ASME_B31.3",
        codeDisplay: "ASME B31.3 Process Piping",
        multiplier: 1.5,
        formula: "1.5 x Design Pressure at test temperature",
        holdMin: 10,
        holdPerMm: null,
        lossMax: 1.5,
        tempMin: 16,
        medium: "WATER",
        pneumaticAllowed: true,
        pneumaticMult: 1.1,
      },
      {
        code: "ASME_B31.8",
        codeDisplay: "ASME B31.8 Gas Transmission",
        multiplier: 1.25,
        formula: "1.25 x MAOP",
        holdMin: 480,
        holdPerMm: null,
        lossMax: 0,
        tempMin: 16,
        medium: "WATER",
        pneumaticAllowed: false,
        pneumaticMult: null,
      },
      {
        code: "API_1104",
        codeDisplay: "API 1104 Pipeline Welding",
        multiplier: 1.25,
        formula: "Per project specification (typically 1.25x)",
        holdMin: 240,
        holdPerMm: null,
        lossMax: 0,
        tempMin: 16,
        medium: "WATER",
        pneumaticAllowed: false,
        pneumaticMult: null,
      },
      {
        code: "ASME_B31.1",
        codeDisplay: "ASME B31.1 Power Piping",
        multiplier: 1.5,
        formula: "1.5 x Design Pressure",
        holdMin: 10,
        holdPerMm: null,
        lossMax: 0,
        tempMin: 21,
        medium: "WATER",
        pneumaticAllowed: true,
        pneumaticMult: 1.25,
      },
      {
        code: "ASME_B31.4",
        codeDisplay: "ASME B31.4 Liquid Transportation",
        multiplier: 1.25,
        formula: "1.25 x Internal Design Pressure",
        holdMin: 240,
        holdPerMm: null,
        lossMax: 0,
        tempMin: 16,
        medium: "WATER",
        pneumaticAllowed: false,
        pneumaticMult: null,
      },
      {
        code: "EN_13480",
        codeDisplay: "EN 13480 Metallic Industrial Piping",
        multiplier: 1.43,
        formula: "1.43 x Design Pressure (hydraulic)",
        holdMin: 30,
        holdPerMm: 1,
        lossMax: 0,
        tempMin: 5,
        medium: "WATER",
        pneumaticAllowed: true,
        pneumaticMult: 1.1,
      },
    ];

    for (const r of requirements) {
      await queryRunner.query(`
        INSERT INTO hydrotest_requirements (code, code_display_name, test_pressure_multiplier, test_pressure_formula, hold_time_minutes, hold_time_per_mm_wall, volume_loss_max_pct, temperature_min_c, medium, pneumatic_allowed, pneumatic_multiplier)
        VALUES ('${r.code}', '${r.codeDisplay}', ${r.multiplier}, '${r.formula}', ${r.holdMin}, ${r.holdPerMm ?? "NULL"}, ${r.lossMax}, ${r.tempMin}, '${r.medium}', ${r.pneumaticAllowed}, ${r.pneumaticMult ?? "NULL"})
      `);
    }
  }

  private async seedNdtMethodRequirements(queryRunner: QueryRunner): Promise<void> {
    const methods = [
      {
        method: "RT",
        methodDisplay: "Radiographic Testing",
        astm: "ASTM E142",
        application: "BUTT_WELD",
        appDisplay: "Butt Welds",
        psl1Pct: 10,
        psl2Pct: 100,
        acceptRef: "API 1104 Section 9 / ASME B31.3 Table 341.3.2",
        equipment: "Industrial X-ray source, film/digital detector, IQI",
        certLevel: "Level II",
        defects: "Porosity, Slag, Cracks, Incomplete Fusion, Incomplete Penetration",
      },
      {
        method: "RT",
        methodDisplay: "Radiographic Testing",
        astm: "ASTM E142",
        application: "FILLET_WELD",
        appDisplay: "Fillet Welds",
        psl1Pct: 0,
        psl2Pct: 10,
        acceptRef: "ASME B31.3 Table 341.3.2",
        equipment: "Industrial X-ray source, film/digital detector",
        certLevel: "Level II",
        defects: "Porosity, Slag, Cracks",
      },
      {
        method: "UT",
        methodDisplay: "Ultrasonic Testing",
        astm: "ASTM A388",
        application: "BUTT_WELD",
        appDisplay: "Butt Welds",
        psl1Pct: 10,
        psl2Pct: 100,
        acceptRef: "API 1104 Section 9 / ASME B31.3",
        equipment: "UT flaw detector, angle beam transducers, calibration blocks",
        certLevel: "Level II",
        defects: "Cracks, Incomplete Fusion, Laminations, Slag",
      },
      {
        method: "UT",
        methodDisplay: "Ultrasonic Testing",
        astm: "ASTM A388",
        application: "PIPE_BODY",
        appDisplay: "Pipe Body",
        psl1Pct: 10,
        psl2Pct: 100,
        acceptRef: "API 5L Table 19",
        equipment: "Automated UT system, calibration standard",
        certLevel: "Level II",
        defects: "Laminations, Inclusions, Seam defects",
      },
      {
        method: "MT",
        methodDisplay: "Magnetic Particle Testing",
        astm: "ASTM E709",
        application: "SURFACE",
        appDisplay: "Surface Inspection",
        psl1Pct: 0,
        psl2Pct: 100,
        acceptRef: "API 1104 Section 9.7",
        equipment: "Yoke or prods, wet/dry particles, UV light (fluorescent)",
        certLevel: "Level II",
        defects: "Surface cracks, Undercut, Incomplete fusion (surface-breaking)",
      },
      {
        method: "MT",
        methodDisplay: "Magnetic Particle Testing",
        astm: "ASTM E709",
        application: "BUTT_WELD",
        appDisplay: "Butt Welds",
        psl1Pct: 0,
        psl2Pct: 50,
        acceptRef: "ASME B31.3 Table 341.3.2",
        equipment: "Yoke, wet particles, white contrast paint",
        certLevel: "Level II",
        defects: "Surface and near-surface cracks",
      },
      {
        method: "PT",
        methodDisplay: "Liquid Penetrant Testing",
        astm: "ASTM E165",
        application: "SURFACE",
        appDisplay: "Surface Inspection",
        psl1Pct: 0,
        psl2Pct: 100,
        acceptRef: "API 1104 Section 9.7",
        equipment: "Penetrant, developer, cleaner, UV light (fluorescent)",
        certLevel: "Level II",
        defects: "Surface-breaking cracks, Porosity, Undercut",
      },
      {
        method: "PT",
        methodDisplay: "Liquid Penetrant Testing",
        astm: "ASTM E165",
        application: "FILLET_WELD",
        appDisplay: "Fillet Welds",
        psl1Pct: 0,
        psl2Pct: 25,
        acceptRef: "ASME B31.3 Table 341.3.2",
        equipment: "Penetrant kit (visible or fluorescent)",
        certLevel: "Level II",
        defects: "Surface cracks, Porosity",
      },
      {
        method: "VT",
        methodDisplay: "Visual Testing",
        astm: "AWS B1.11",
        application: "ALL",
        appDisplay: "All Welds",
        psl1Pct: 100,
        psl2Pct: 100,
        acceptRef: "API 1104 Section 9 / ASME B31.3",
        equipment: "Adequate lighting, measuring tools, magnification if needed",
        certLevel: "Level I",
        defects: "Surface defects, Undercut, Overlap, Spatter, Arc strikes",
      },
    ];

    for (const m of methods) {
      await queryRunner.query(`
        INSERT INTO ndt_method_requirements (method, method_display_name, astm_standard, application, application_display_name, coverage_psl1_pct, coverage_psl2_pct, acceptance_criteria_ref, equipment_requirements, operator_cert_level, defects_detected)
        VALUES ('${m.method}', '${m.methodDisplay}', '${m.astm}', '${m.application}', '${m.appDisplay}', ${m.psl1Pct}, ${m.psl2Pct}, '${m.acceptRef}', '${m.equipment}', '${m.certLevel}', '${m.defects}')
      `);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("DROP TABLE IF EXISTS ndt_method_requirements");
    await queryRunner.query("DROP TABLE IF EXISTS hydrotest_requirements");
    await queryRunner.query("DROP TABLE IF EXISTS weld_defect_acceptance");
    await queryRunner.query("DROP TABLE IF EXISTS pipe_end_preparations");
    await queryRunner.query("DROP TABLE IF EXISTS pipe_tolerances");
    await queryRunner.query("DROP TABLE IF EXISTS api5l_grades");
  }
}
