import { MigrationInterface, QueryRunner } from "typeorm";

const REQUIREMENTS = [
  {
    code: "CIPC_ANNUAL_RETURN",
    name: "CIPC Annual Return",
    description:
      "Annual return filing with the Companies and Intellectual Property Commission (CIPC). All registered companies must file an annual return to maintain their registration status.",
    regulator: "CIPC",
    category: "corporate",
    frequency: "annual",
    applicable_conditions: null,
    deadline_rule: { type: "anniversary_offset", field: "registrationDate", offset_days: 30 },
    penalty_description:
      "Deregistration after 2 years non-filing, bank account freezing, personal director liability",
    guidance_url: "https://annualreturns.cipc.co.za/",
    required_documents: null,
    checklist_steps: [
      "Check CIPC filing status",
      "Prepare financial statements summary",
      "Submit beneficial ownership declaration",
      "Pay annual return fee",
      "File annual return on BizPortal",
    ],
  },
  {
    code: "CIPC_BENEFICIAL_OWNERSHIP",
    name: "CIPC Beneficial Ownership Disclosure",
    description:
      "Mandatory disclosure of beneficial owners to CIPC. Since July 2024, companies cannot file annual returns without first completing beneficial ownership declarations.",
    regulator: "CIPC",
    category: "corporate",
    frequency: "ongoing",
    applicable_conditions: null,
    deadline_rule: { type: "ongoing" },
    penalty_description: "Cannot file annual returns until disclosed (hard stop since July 2024)",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Identify all beneficial owners (25%+ ownership or significant control)",
      "Gather ID documents for each beneficial owner",
      "Submit declaration on BizPortal",
      "Update within 5 business days of any changes",
    ],
  },
  {
    code: "SARS_INCOME_TAX",
    name: "Company Income Tax Return (ITR14)",
    description:
      "Annual company income tax return submission to SARS. Companies are taxed at 27% on taxable income.",
    regulator: "SARS",
    category: "tax",
    frequency: "annual",
    applicable_conditions: null,
    deadline_rule: { type: "fixed_dates", dates: [{ month: 12, day: 15 }] },
    penalty_description: "10% late payment penalty plus interest at prescribed rate",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Ensure accounting records are up to date",
      "Prepare annual financial statements",
      "Calculate taxable income (27% corporate rate)",
      "Submit ITR14 on eFiling",
      "Pay any outstanding tax",
    ],
  },
  {
    code: "SARS_PROVISIONAL_TAX",
    name: "Provisional Tax Payments",
    description: "Bi-annual provisional tax payments to SARS.",
    regulator: "SARS",
    category: "tax",
    frequency: "bi-annual",
    applicable_conditions: null,
    deadline_rule: {
      type: "fixed_dates",
      dates: [
        { month: 8, day: 31 },
        { month: 2, day: 28 },
      ],
    },
    penalty_description: "10% penalty on underpayment plus interest",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Estimate taxable income for the period",
      "Calculate provisional tax payment amount",
      "Submit IRP6 on eFiling",
      "Make payment by deadline",
    ],
  },
  {
    code: "SARS_VAT_REGISTRATION",
    name: "VAT Registration Assessment",
    description: "Assessment of mandatory VAT registration requirement.",
    regulator: "SARS",
    category: "tax",
    frequency: "ongoing",
    applicable_conditions: { annual_turnover_gte: 2300000 },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Penalties for trading without VAT registration when required",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Confirm taxable supplies exceed R2.3m threshold",
      "Register for VAT on SARS eFiling",
      "Obtain VAT number",
      "Update invoicing to include VAT",
    ],
  },
  {
    code: "SARS_VAT_RETURNS",
    name: "VAT Return Submissions",
    description: "Bi-monthly VAT return submissions to SARS.",
    regulator: "SARS",
    category: "tax",
    frequency: "bi-monthly",
    applicable_conditions: { vat_registered: true },
    deadline_rule: { type: "fixed_monthly", day: 25 },
    penalty_description: "10% late payment penalty plus interest",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Reconcile input and output VAT for the period",
      "Prepare VAT201 return",
      "Submit on eFiling by 25th",
      "Pay any VAT owing",
    ],
  },
  {
    code: "SARS_EMP201",
    name: "Monthly Employer Declarations (PAYE/UIF/SDL)",
    description: "Monthly employer declarations for PAYE, UIF, and SDL contributions to SARS.",
    regulator: "SARS",
    category: "tax",
    frequency: "monthly",
    applicable_conditions: { has_payroll: true },
    deadline_rule: { type: "fixed_monthly", day: 7 },
    penalty_description: "10% penalty plus interest on late payment",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Calculate PAYE for all employees",
      "Calculate UIF contributions (1% employer + 1% employee)",
      "Calculate SDL (1% of payroll if > R500k)",
      "Submit EMP201 on eFiling",
      "Make payment by 7th of month",
    ],
  },
  {
    code: "SARS_EMP501",
    name: "Bi-Annual Employer Reconciliation",
    description: "Bi-annual employer reconciliation submission to SARS.",
    regulator: "SARS",
    category: "tax",
    frequency: "bi-annual",
    applicable_conditions: { has_payroll: true },
    deadline_rule: {
      type: "fixed_dates",
      dates: [
        { month: 8, day: 31 },
        { month: 2, day: 28 },
      ],
    },
    penalty_description: "Penalties for non-submission, employees cannot file returns",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Reconcile all PAYE/UIF/SDL payments for the period",
      "Generate IRP5/IT3(a) certificates for all employees",
      "Submit EMP501 on eFiling",
      "Issue IRP5 certificates to employees",
    ],
  },
  {
    code: "SARS_TURNOVER_TAX",
    name: "Turnover Tax Assessment",
    description: "Assessment for the simplified turnover tax regime.",
    regulator: "SARS",
    category: "tax",
    frequency: "ongoing",
    applicable_conditions: { annual_turnover_lte: 2300000 },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Standard SARS penalties for non-compliance",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Confirm eligibility (turnover under R2.3m)",
      "Register for turnover tax on eFiling if beneficial",
      "Calculate tax using turnover tax tables",
      "First R600k is tax-free",
    ],
  },
  {
    code: "UIF_REGISTRATION",
    name: "UIF Employer Registration",
    description: "Registration as an employer with the Unemployment Insurance Fund.",
    regulator: "Department of Employment and Labour",
    category: "labour",
    frequency: "ongoing",
    applicable_conditions: { has_payroll: true },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Fines and penalties for non-registration",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Register with UIF within 30 days of first employee",
      "Obtain UIF reference number",
      "Deduct 1% from employee salaries",
      "Contribute 1% as employer",
      "Include in monthly EMP201 submission",
    ],
  },
  {
    code: "COIDA_REGISTRATION",
    name: "Compensation Fund Registration and Return of Earnings",
    description:
      "Registration with the Compensation Fund and annual submission of Return of Earnings.",
    regulator: "Department of Employment and Labour",
    category: "labour",
    frequency: "annual",
    applicable_conditions: { has_payroll: true },
    deadline_rule: { type: "fixed_dates", dates: [{ month: 3, day: 31 }] },
    penalty_description: "Fines, no coverage for workplace injuries, minimum assessment R1,621",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Register with Compensation Fund",
      "Calculate total employee earnings for the year",
      "Submit Return of Earnings by 31 March",
      "Pay assessment fee",
      "Obtain Letter of Good Standing",
    ],
  },
  {
    code: "SDL_ASSESSMENT",
    name: "Skills Development Levy Assessment",
    description: "Assessment and payment of the Skills Development Levy.",
    regulator: "SARS",
    category: "tax",
    frequency: "ongoing",
    applicable_conditions: { has_payroll: true },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Penalties for non-payment",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Determine if annual payroll exceeds R500,000",
      "If applicable, pay 1% of total payroll as SDL",
      "Include in monthly EMP201 submission",
      "Consider SETA grant applications to reclaim",
    ],
  },
  {
    code: "POPIA_INFORMATION_OFFICER",
    name: "Register Information Officer",
    description:
      "Appointment and registration of an Information Officer with the Information Regulator as required by POPIA.",
    regulator: "Information Regulator",
    category: "privacy",
    frequency: "ongoing",
    applicable_conditions: { handles_personal_data: true },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Up to R10 million fine and/or 10 years imprisonment",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Appoint Information Officer (typically a director)",
      "Register with Information Regulator",
      "Ensure officer understands POPIA duties",
      "Update registration if officer changes",
    ],
  },
  {
    code: "POPIA_PRIVACY_POLICY",
    name: "Develop and Maintain Privacy Policy",
    description:
      "Development and maintenance of a comprehensive privacy policy covering all data processing activities as required by POPIA.",
    regulator: "Information Regulator",
    category: "privacy",
    frequency: "ongoing",
    applicable_conditions: { handles_personal_data: true },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Up to R10 million fine",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Draft privacy policy covering all data processing activities",
      "Include purpose of processing, categories of data, retention periods",
      "Make policy available to data subjects",
      "Review and update annually",
      "Train staff on privacy policy",
    ],
  },
  {
    code: "POPIA_PAIA_MANUAL",
    name: "PAIA Manual Requirement",
    description:
      "Preparation and submission of a PAIA manual (Section 51 for private bodies) to the Information Regulator.",
    regulator: "Information Regulator",
    category: "privacy",
    frequency: "ongoing",
    applicable_conditions: null,
    deadline_rule: { type: "ongoing" },
    penalty_description: "Non-compliance with PAIA",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Prepare PAIA manual (Section 51 for private bodies)",
      "Include contact details, PAIA guide reference, records available",
      "Submit to Information Regulator",
      "Make available on company website",
      "Review annually",
    ],
  },
  {
    code: "BBEE_EME_AFFIDAVIT",
    name: "B-BBEE Affidavit for Exempted Micro Enterprise",
    description:
      "B-BBEE sworn affidavit for Exempted Micro Enterprises with annual turnover under R10 million.",
    regulator: "DTI",
    category: "corporate",
    frequency: "annual",
    applicable_conditions: { annual_turnover_lte: 10000000 },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Cannot participate in government tenders without valid affidavit",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Confirm annual turnover is under R10 million",
      "Determine black ownership percentage for automatic level",
      "Complete B-BBEE sworn affidavit",
      "Have affidavit signed before Commissioner of Oaths",
      "Keep original for tender submissions",
    ],
  },
  {
    code: "BBEE_QSE_AFFIDAVIT",
    name: "B-BBEE Affidavit for Qualifying Small Enterprise",
    description:
      "B-BBEE sworn affidavit for Qualifying Small Enterprises with annual turnover between R10 million and R50 million.",
    regulator: "DTI",
    category: "corporate",
    frequency: "annual",
    applicable_conditions: { annual_turnover_gte: 10000000, annual_turnover_lte: 50000000 },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Exclusion from government procurement",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Confirm turnover between R10m and R50m",
      "Determine black ownership percentage",
      "Complete QSE sworn affidavit",
      "Have affidavit signed before Commissioner of Oaths",
      "Consider voluntary verification for higher level",
    ],
  },
  {
    code: "BBEE_GENERIC_VERIFICATION",
    name: "Full B-BBEE Verification for Generic Enterprise",
    description:
      "Full B-BBEE verification by an accredited agency for Generic Enterprises with annual turnover exceeding R50 million.",
    regulator: "DTI",
    category: "corporate",
    frequency: "annual",
    applicable_conditions: { annual_turnover_gte: 50000000 },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Cannot participate in procurement without valid certificate",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Engage accredited B-BBEE verification agency",
      "Prepare documentation for all 5 scorecard elements",
      "Submit for verification",
      "Receive B-BBEE certificate",
      "Plan improvement strategy for next verification",
    ],
  },
  {
    code: "EE_REPORTING",
    name: "Employment Equity Reporting",
    description:
      "Annual Employment Equity reporting for designated employers with 50 or more employees.",
    regulator: "Department of Employment and Labour",
    category: "labour",
    frequency: "annual",
    applicable_conditions: { employee_count_gte: 50 },
    deadline_rule: { type: "fixed_dates", dates: [{ month: 1, day: 15 }] },
    penalty_description:
      "Up to R1.5 million or 2% of annual turnover, exclusion from state contracts",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Conduct workplace analysis",
      "Prepare Employment Equity Plan",
      "Consult with employee representatives",
      "Submit EEA2 and EEA4 reports online by 15 January",
      "Display summary of EE Act in workplace",
    ],
  },
  {
    code: "MINIMUM_WAGE",
    name: "National Minimum Wage Compliance",
    description: "Compliance with the National Minimum Wage Act.",
    regulator: "Department of Employment and Labour",
    category: "labour",
    frequency: "ongoing",
    applicable_conditions: { has_payroll: true },
    deadline_rule: { type: "ongoing" },
    penalty_description: "Criminal offence, compliance orders, fines",
    guidance_url: null,
    required_documents: null,
    checklist_steps: [
      "Ensure all employees paid at least R30.23/hour (from March 2026)",
      "Review overtime rates (1.5x for overtime)",
      "Keep accurate time and attendance records",
      "Display minimum wage notice in workplace",
    ],
  },
];

export class ComplySaSeedComplianceRequirements1807000000001 implements MigrationInterface {
  name = "ComplySaSeedComplianceRequirements1807000000001";

  async up(queryRunner: QueryRunner): Promise<void> {
    await Promise.all(
      REQUIREMENTS.map((req) =>
        queryRunner.query(
          `INSERT INTO comply_sa_compliance_requirements (
            code, name, description, regulator, category, frequency,
            applicable_conditions, deadline_rule, penalty_description,
            guidance_url, required_documents, checklist_steps, tier
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 1)
          ON CONFLICT (code) DO NOTHING`,
          [
            req.code,
            req.name,
            req.description,
            req.regulator,
            req.category,
            req.frequency,
            req.applicable_conditions !== null ? JSON.stringify(req.applicable_conditions) : null,
            req.deadline_rule !== null ? JSON.stringify(req.deadline_rule) : null,
            req.penalty_description,
            req.guidance_url,
            req.required_documents !== null ? JSON.stringify(req.required_documents) : null,
            req.checklist_steps !== null ? JSON.stringify(req.checklist_steps) : null,
          ],
        ),
      ),
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    const codes = REQUIREMENTS.map((r) => `'${r.code}'`).join(", ");
    await queryRunner.query(
      `DELETE FROM comply_sa_compliance_requirements WHERE code IN (${codes})`,
    );
  }
}
