export const CREDENTIAL_TYPES = [
  "medical",
  "mine_induction",
  "blasting",
  "eye_test",
  "lift_driver",
  "plant_operator",
  "tmm_licence",
  "crane_operator",
  "rigging",
  "drivers_licence",
  "prdp",
  "working_at_heights",
  "confined_space",
  "scaffolding",
  "h2s_awareness",
  "gas_testing",
  "first_aid",
  "fire_fighting",
  "hazmat",
  "welding",
  "other",
] as const;

export type CredentialType = (typeof CREDENTIAL_TYPES)[number];

export const CREDENTIAL_LABELS: Record<CredentialType, string> = {
  medical: "Medical Certificate",
  mine_induction: "Mine Induction",
  blasting: "Blasting Ticket",
  eye_test: "Eye Test",
  lift_driver: "Forklift Licence",
  plant_operator: "Plant / Machine Operator",
  tmm_licence: "Trackless Mobile Machinery (TMM)",
  crane_operator: "Crane Operator",
  rigging: "Rigging / Slinging",
  drivers_licence: "Driver's Licence",
  prdp: "Professional Driving Permit (PrDP)",
  working_at_heights: "Working at Heights",
  confined_space: "Confined Space Entry",
  scaffolding: "Scaffolding",
  h2s_awareness: "H2S Awareness",
  gas_testing: "Gas Testing",
  first_aid: "First Aid",
  fire_fighting: "Fire Fighting",
  hazmat: "Dangerous Goods / Hazchem",
  welding: "Welding (Coded)",
  other: "Other",
};

export const CREDENTIAL_DESCRIPTIONS: Record<CredentialType, string> = {
  medical:
    'Certificate of Fitness (CoF / "red ticket") confirming you\'re medically fit for the role.',
  mine_induction: "Site-specific safety induction required before entering a mine.",
  blasting: "Authorisation to handle explosives and break rock.",
  eye_test: "Vision screening, often paired with the medical.",
  lift_driver: "Licence to operate a forklift / lift truck.",
  plant_operator: "Earth-moving plant competency (excavator, loader, dozer).",
  tmm_licence: "Licence to operate trackless mobile machinery on a mine.",
  crane_operator: "Mobile or overhead crane operating licence.",
  rigging: "Rigger or slinger competency for lifting loads.",
  drivers_licence: "Code B/C/EC road driving licence.",
  prdp: "Professional Driving Permit for goods, passengers or dangerous goods.",
  working_at_heights: "Fall-protection competency for elevated work.",
  confined_space: "Entry and work in confined spaces.",
  scaffolding: "Scaffold erector / inspector competency.",
  h2s_awareness: "Hydrogen-sulphide gas hazard awareness.",
  gas_testing: "Atmospheric / gas testing competency.",
  first_aid: "First-aid responder certificate (Level 1–3).",
  fire_fighting: "Basic fire-fighting / fire-marshal competency.",
  hazmat: "Handling and transport of dangerous goods.",
  welding: "Coded welder qualification.",
  other: "Any credential not listed here.",
};
