import { API_BASE_URL } from "@/lib/api-config";
import type {
  CallOff,
  CreateRubberProductDto,
  ImportProductRowDto,
  ImportProductsResultDto,
  RubberCompanyDto,
  RubberOrderDto,
  RubberPriceCalculationDto,
  RubberPricingTierDto,
  RubberProductCodingDto,
  RubberProductDto,
} from "./rubberPortalApi";

export type CompoundMovementType = "IN" | "OUT" | "ADJUSTMENT";
export type CompoundMovementReferenceType = "PURCHASE" | "PRODUCTION" | "MANUAL" | "STOCK_TAKE";
export type RubberProductionStatus = "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
export type RubberCompoundOrderStatus =
  | "PENDING"
  | "APPROVED"
  | "ORDERED"
  | "RECEIVED"
  | "CANCELLED";

export interface RubberCompoundStockDto {
  id: number;
  firebaseUid: string;
  compoundCodingId: number;
  compoundName: string | null;
  compoundCode: string | null;
  quantityKg: number;
  minStockLevelKg: number;
  reorderPointKg: number;
  costPerKg: number | null;
  location: string | null;
  batchNumber: string | null;
  isLowStock: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface RubberCompoundMovementDto {
  id: number;
  compoundStockId: number;
  compoundName: string | null;
  movementType: CompoundMovementType;
  quantityKg: number;
  referenceType: CompoundMovementReferenceType;
  referenceId: number | null;
  batchNumber: string | null;
  notes: string | null;
  createdBy: string | null;
  createdAt: string;
}

export interface RubberProductionDto {
  id: number;
  firebaseUid: string;
  productionNumber: string;
  productId: number;
  productTitle: string | null;
  compoundStockId: number;
  compoundName: string | null;
  thicknessMm: number;
  widthMm: number;
  lengthM: number;
  quantity: number;
  compoundRequiredKg: number;
  compoundUsedKg: number | null;
  status: RubberProductionStatus;
  statusLabel: string;
  orderId: number | null;
  notes: string | null;
  createdBy: string | null;
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface RubberCompoundOrderDto {
  id: number;
  firebaseUid: string;
  orderNumber: string;
  compoundStockId: number;
  compoundName: string | null;
  quantityKg: number;
  status: RubberCompoundOrderStatus;
  statusLabel: string;
  isAutoGenerated: boolean;
  supplierName: string | null;
  expectedDelivery: string | null;
  notes: string | null;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CompoundCalculationResultDto {
  productTitle: string | null;
  specificGravity: number;
  compoundRequiredKg: number;
  kgPerUnit: number;
}

export interface ExtractedBrandingDto {
  url: string;
  companyName: string | null;
  tagline: string | null;
  logoUrl: string | null;
  colors: {
    primary: string[];
    background: string[];
    text: string[];
    accent: string[];
  };
  extractedAt: string;
}

export interface AuRubberLoginDto {
  email: string;
  password: string;
  appCode?: string;
}

export interface AuRubberUser {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  roles: string[];
}

export interface AuRubberLoginResponse {
  accessToken: string;
  refreshToken: string;
  user: AuRubberUser;
}

export interface AuRubberUserProfile {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  roles: string[];
  createdAt: string;
  lastActiveAt?: string;
}

const TOKEN_KEYS = {
  accessToken: "auRubberAccessToken",
  refreshToken: "auRubberRefreshToken",
} as const;

class AuRubberApiClient {
  private baseURL: string;
  private accessToken: string | null = null;
  private refreshToken: string | null = null;
  private rememberMe: boolean = true;

  constructor(baseURL: string = API_BASE_URL) {
    this.baseURL = baseURL;

    if (typeof window !== "undefined") {
      this.accessToken =
        localStorage.getItem(TOKEN_KEYS.accessToken) ??
        sessionStorage.getItem(TOKEN_KEYS.accessToken);
      this.refreshToken =
        localStorage.getItem(TOKEN_KEYS.refreshToken) ??
        sessionStorage.getItem(TOKEN_KEYS.refreshToken);
    }
  }

  setRememberMe(remember: boolean) {
    this.rememberMe = remember;
  }

  private headers(): Record<string, string> {
    if (!this.accessToken && typeof window !== "undefined") {
      this.accessToken =
        localStorage.getItem(TOKEN_KEYS.accessToken) ??
        sessionStorage.getItem(TOKEN_KEYS.accessToken);
      this.refreshToken =
        localStorage.getItem(TOKEN_KEYS.refreshToken) ??
        sessionStorage.getItem(TOKEN_KEYS.refreshToken);
    }

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };

    if (this.accessToken) {
      headers["Authorization"] = `Bearer ${this.accessToken}`;
    }

    return headers;
  }

  private setTokens(accessToken: string, refreshToken: string) {
    this.accessToken = accessToken;
    this.refreshToken = refreshToken;
    if (typeof window !== "undefined") {
      const storage = this.rememberMe ? localStorage : sessionStorage;
      storage.setItem(TOKEN_KEYS.accessToken, accessToken);
      storage.setItem(TOKEN_KEYS.refreshToken, refreshToken);
    }
  }

  clearTokens() {
    this.accessToken = null;
    this.refreshToken = null;
    if (typeof window !== "undefined") {
      localStorage.removeItem(TOKEN_KEYS.accessToken);
      localStorage.removeItem(TOKEN_KEYS.refreshToken);
      sessionStorage.removeItem(TOKEN_KEYS.accessToken);
      sessionStorage.removeItem(TOKEN_KEYS.refreshToken);
    }
  }

  isAuthenticated(): boolean {
    if (!this.accessToken && typeof window !== "undefined") {
      this.accessToken =
        localStorage.getItem(TOKEN_KEYS.accessToken) ??
        sessionStorage.getItem(TOKEN_KEYS.accessToken);
      this.refreshToken =
        localStorage.getItem(TOKEN_KEYS.refreshToken) ??
        sessionStorage.getItem(TOKEN_KEYS.refreshToken);
    }
    return !!this.accessToken;
  }

  private async request<T>(endpoint: string, options: RequestInit = {}): Promise<T> {
    const url = `${this.baseURL}${endpoint}`;

    const config: RequestInit = {
      ...options,
      headers: {
        ...this.headers(),
        ...(options.headers as Record<string, string>),
      },
    };

    const response = await fetch(url, config);

    if (response.status === 401 && this.refreshToken) {
      const refreshed = await this.refreshAccessToken();
      if (refreshed) {
        config.headers = {
          ...this.headers(),
          ...(options.headers as Record<string, string>),
        };
        const retryResponse = await fetch(url, config);
        if (!retryResponse.ok) {
          const errorText = await retryResponse.text();
          throw new Error(`API Error (${retryResponse.status}): ${errorText}`);
        }
        return retryResponse.json();
      }
    }

    if (!response.ok) {
      const errorText = await response.text();
      let errorMessage = `API Error (${response.status}): ${errorText}`;

      try {
        const errorData = JSON.parse(errorText);
        if (errorData.message) {
          errorMessage = errorData.message;
        }
      } catch {
        // Use raw error text if not JSON
      }

      throw new Error(errorMessage);
    }

    const text = await response.text();
    if (!text || text.trim() === "") {
      return {} as T;
    }

    return JSON.parse(text) as T;
  }

  private async refreshAccessToken(): Promise<boolean> {
    if (!this.refreshToken) return false;

    try {
      const response = await fetch(`${this.baseURL}/admin/auth/refresh`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ refreshToken: this.refreshToken }),
      });

      if (!response.ok) {
        this.clearTokens();
        return false;
      }

      const data = await response.json();
      this.accessToken = data.accessToken;
      if (typeof window !== "undefined") {
        if (localStorage.getItem(TOKEN_KEYS.refreshToken)) {
          localStorage.setItem(TOKEN_KEYS.accessToken, data.accessToken);
        } else {
          sessionStorage.setItem(TOKEN_KEYS.accessToken, data.accessToken);
        }
      }
      return true;
    } catch {
      this.clearTokens();
      return false;
    }
  }

  async login(dto: AuRubberLoginDto): Promise<AuRubberLoginResponse> {
    const response = await this.request<AuRubberLoginResponse>("/admin/auth/login", {
      method: "POST",
      body: JSON.stringify({ ...dto, appCode: "au-rubber" }),
    });

    this.setTokens(response.accessToken, response.refreshToken);
    return response;
  }

  async logout(): Promise<void> {
    try {
      await this.request("/admin/auth/logout", { method: "POST" });
    } finally {
      this.clearTokens();
    }
  }

  async currentUser(): Promise<AuRubberUserProfile> {
    return this.request<AuRubberUserProfile>("/admin/auth/me");
  }

  async productCodings(codingType?: string): Promise<RubberProductCodingDto[]> {
    const query = codingType ? `?codingType=${codingType}` : "";
    return this.request(`/rubber-lining/portal/product-codings${query}`);
  }

  async productCodingById(id: number): Promise<RubberProductCodingDto> {
    return this.request(`/rubber-lining/portal/product-codings/${id}`);
  }

  async createProductCoding(
    data: Omit<RubberProductCodingDto, "id" | "firebaseUid">,
  ): Promise<RubberProductCodingDto> {
    return this.request("/rubber-lining/portal/product-codings", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async updateProductCoding(
    id: number,
    data: Partial<RubberProductCodingDto>,
  ): Promise<RubberProductCodingDto> {
    return this.request(`/rubber-lining/portal/product-codings/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  }

  async deleteProductCoding(id: number): Promise<void> {
    return this.request(`/rubber-lining/portal/product-codings/${id}`, {
      method: "DELETE",
    });
  }

  async pricingTiers(): Promise<RubberPricingTierDto[]> {
    return this.request("/rubber-lining/portal/pricing-tiers");
  }

  async pricingTierById(id: number): Promise<RubberPricingTierDto> {
    return this.request(`/rubber-lining/portal/pricing-tiers/${id}`);
  }

  async createPricingTier(data: Omit<RubberPricingTierDto, "id">): Promise<RubberPricingTierDto> {
    return this.request("/rubber-lining/portal/pricing-tiers", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async updatePricingTier(
    id: number,
    data: Partial<RubberPricingTierDto>,
  ): Promise<RubberPricingTierDto> {
    return this.request(`/rubber-lining/portal/pricing-tiers/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  }

  async deletePricingTier(id: number): Promise<void> {
    return this.request(`/rubber-lining/portal/pricing-tiers/${id}`, {
      method: "DELETE",
    });
  }

  async companies(): Promise<RubberCompanyDto[]> {
    return this.request("/rubber-lining/portal/companies");
  }

  async companyById(id: number): Promise<RubberCompanyDto> {
    return this.request(`/rubber-lining/portal/companies/${id}`);
  }

  async createCompany(data: {
    name: string;
    code?: string;
    pricingTierId?: number;
    availableProducts?: string[];
    isCompoundOwner?: boolean;
    vatNumber?: string;
    registrationNumber?: string;
    address?: Record<string, string>;
    notes?: string;
  }): Promise<RubberCompanyDto> {
    return this.request("/rubber-lining/portal/companies", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async updateCompany(
    id: number,
    data: Partial<{
      name: string;
      code?: string;
      pricingTierId?: number;
      availableProducts?: string[];
      isCompoundOwner?: boolean;
      vatNumber?: string;
      registrationNumber?: string;
      address?: Record<string, string>;
      notes?: string;
    }>,
  ): Promise<RubberCompanyDto> {
    return this.request(`/rubber-lining/portal/companies/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  }

  async deleteCompany(id: number): Promise<void> {
    return this.request(`/rubber-lining/portal/companies/${id}`, {
      method: "DELETE",
    });
  }

  async products(): Promise<RubberProductDto[]> {
    return this.request("/rubber-lining/portal/products");
  }

  async productById(id: number): Promise<RubberProductDto> {
    return this.request(`/rubber-lining/portal/products/${id}`);
  }

  async createProduct(data: CreateRubberProductDto): Promise<RubberProductDto> {
    return this.request("/rubber-lining/portal/products", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async updateProduct(
    id: number,
    data: Partial<CreateRubberProductDto>,
  ): Promise<RubberProductDto> {
    return this.request(`/rubber-lining/portal/products/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  }

  async deleteProduct(id: number): Promise<void> {
    return this.request(`/rubber-lining/portal/products/${id}`, {
      method: "DELETE",
    });
  }

  async orders(status?: number): Promise<RubberOrderDto[]> {
    const query = status !== undefined ? `?status=${status}` : "";
    return this.request(`/rubber-lining/portal/orders${query}`);
  }

  async orderById(id: number): Promise<RubberOrderDto> {
    return this.request(`/rubber-lining/portal/orders/${id}`);
  }

  async createOrder(data: {
    orderNumber?: string;
    companyOrderNumber?: string;
    companyId?: number;
    items?: {
      productId?: number;
      thickness?: number;
      width?: number;
      length?: number;
      quantity?: number;
      callOffs?: CallOff[];
    }[];
  }): Promise<RubberOrderDto> {
    return this.request("/rubber-lining/portal/orders", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async updateOrder(
    id: number,
    data: {
      companyOrderNumber?: string;
      status?: number;
      companyId?: number;
      items?: {
        productId?: number;
        thickness?: number;
        width?: number;
        length?: number;
        quantity?: number;
        callOffs?: CallOff[];
      }[];
    },
  ): Promise<RubberOrderDto> {
    return this.request(`/rubber-lining/portal/orders/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  }

  async deleteOrder(id: number): Promise<void> {
    return this.request(`/rubber-lining/portal/orders/${id}`, {
      method: "DELETE",
    });
  }

  async orderStatuses(): Promise<{ value: number; label: string }[]> {
    return this.request("/rubber-lining/portal/order-statuses");
  }

  async codingTypes(): Promise<{ value: string; label: string }[]> {
    return this.request("/rubber-lining/portal/coding-types");
  }

  async calculatePrice(data: {
    productId: number;
    companyId: number;
    thickness: number;
    width: number;
    length: number;
    quantity: number;
  }): Promise<RubberPriceCalculationDto> {
    return this.request("/rubber-lining/portal/calculate-price", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async importProducts(data: {
    rows: ImportProductRowDto[];
    updateExisting?: boolean;
  }): Promise<ImportProductsResultDto> {
    return this.request("/rubber-lining/portal/products/import", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async compoundStocks(): Promise<RubberCompoundStockDto[]> {
    return this.request("/rubber-lining/portal/compound-stocks");
  }

  async lowStockCompounds(): Promise<RubberCompoundStockDto[]> {
    return this.request("/rubber-lining/portal/compound-stocks/low-stock");
  }

  async compoundStockById(id: number): Promise<RubberCompoundStockDto> {
    return this.request(`/rubber-lining/portal/compound-stocks/${id}`);
  }

  async createCompoundStock(data: {
    compoundCodingId: number;
    quantityKg?: number;
    minStockLevelKg?: number;
    reorderPointKg?: number;
    costPerKg?: number;
    location?: string;
    batchNumber?: string;
  }): Promise<RubberCompoundStockDto> {
    return this.request("/rubber-lining/portal/compound-stocks", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async updateCompoundStock(
    id: number,
    data: {
      compoundCodingId?: number;
      quantityKg?: number;
      minStockLevelKg?: number;
      reorderPointKg?: number;
      costPerKg?: number;
      location?: string;
      batchNumber?: string;
    },
  ): Promise<RubberCompoundStockDto> {
    return this.request(`/rubber-lining/portal/compound-stocks/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  }

  async deleteCompoundStock(id: number): Promise<void> {
    return this.request(`/rubber-lining/portal/compound-stocks/${id}`, {
      method: "DELETE",
    });
  }

  async compoundMovements(filters?: {
    compoundStockId?: number;
    movementType?: CompoundMovementType;
    referenceType?: CompoundMovementReferenceType;
  }): Promise<RubberCompoundMovementDto[]> {
    const params = new URLSearchParams();
    if (filters?.compoundStockId) params.set("compoundStockId", String(filters.compoundStockId));
    if (filters?.movementType) params.set("movementType", filters.movementType);
    if (filters?.referenceType) params.set("referenceType", filters.referenceType);
    const query = params.toString() ? `?${params.toString()}` : "";
    return this.request(`/rubber-lining/portal/compound-movements${query}`);
  }

  async receiveCompound(data: {
    compoundStockId: number;
    quantityKg: number;
    batchNumber?: string;
    notes?: string;
  }): Promise<RubberCompoundMovementDto> {
    return this.request("/rubber-lining/portal/compound-movements/receive", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async adjustCompound(data: {
    compoundStockId: number;
    quantityKg: number;
    notes?: string;
  }): Promise<RubberCompoundMovementDto> {
    return this.request("/rubber-lining/portal/compound-movements/adjust", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async productions(status?: RubberProductionStatus): Promise<RubberProductionDto[]> {
    const query = status ? `?status=${status}` : "";
    return this.request(`/rubber-lining/portal/productions${query}`);
  }

  async productionById(id: number): Promise<RubberProductionDto> {
    return this.request(`/rubber-lining/portal/productions/${id}`);
  }

  async createProduction(data: {
    productId: number;
    compoundStockId: number;
    thicknessMm: number;
    widthMm: number;
    lengthM: number;
    quantity: number;
    orderId?: number;
    notes?: string;
  }): Promise<RubberProductionDto> {
    return this.request("/rubber-lining/portal/productions", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async startProduction(id: number): Promise<RubberProductionDto> {
    return this.request(`/rubber-lining/portal/productions/${id}/start`, {
      method: "PUT",
    });
  }

  async completeProduction(id: number): Promise<RubberProductionDto> {
    return this.request(`/rubber-lining/portal/productions/${id}/complete`, {
      method: "PUT",
    });
  }

  async cancelProduction(id: number): Promise<RubberProductionDto> {
    return this.request(`/rubber-lining/portal/productions/${id}/cancel`, {
      method: "PUT",
    });
  }

  async calculateCompoundRequired(data: {
    productId: number;
    thicknessMm: number;
    widthMm: number;
    lengthM: number;
    quantity: number;
  }): Promise<CompoundCalculationResultDto> {
    return this.request("/rubber-lining/portal/productions/calculate-compound", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async compoundOrders(status?: RubberCompoundOrderStatus): Promise<RubberCompoundOrderDto[]> {
    const query = status ? `?status=${status}` : "";
    return this.request(`/rubber-lining/portal/compound-orders${query}`);
  }

  async compoundOrderById(id: number): Promise<RubberCompoundOrderDto> {
    return this.request(`/rubber-lining/portal/compound-orders/${id}`);
  }

  async createCompoundOrder(data: {
    compoundStockId: number;
    quantityKg: number;
    supplierName?: string;
    expectedDelivery?: string;
    notes?: string;
  }): Promise<RubberCompoundOrderDto> {
    return this.request("/rubber-lining/portal/compound-orders", {
      method: "POST",
      body: JSON.stringify(data),
    });
  }

  async updateCompoundOrderStatus(
    id: number,
    status: RubberCompoundOrderStatus,
  ): Promise<RubberCompoundOrderDto> {
    return this.request(`/rubber-lining/portal/compound-orders/${id}/status`, {
      method: "PUT",
      body: JSON.stringify({ status }),
    });
  }

  async receiveCompoundOrder(
    id: number,
    data: {
      actualQuantityKg: number;
      batchNumber?: string;
      notes?: string;
    },
  ): Promise<RubberCompoundOrderDto> {
    return this.request(`/rubber-lining/portal/compound-orders/${id}/receive`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
  }

  async productionStatuses(): Promise<{ value: string; label: string }[]> {
    return this.request("/rubber-lining/portal/production-statuses");
  }

  async compoundOrderStatuses(): Promise<{ value: string; label: string }[]> {
    return this.request("/rubber-lining/portal/compound-order-statuses");
  }

  async extractBranding(url: string): Promise<ExtractedBrandingDto> {
    return this.request("/rubber-lining/portal/extract-branding", {
      method: "POST",
      body: JSON.stringify({ url }),
    });
  }
}

export const auRubberApiClient = new AuRubberApiClient();
