import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import type { HydratedDocument } from "mongoose";

export type RubberCompoundOrderDocument = HydratedDocument<RubberCompoundOrder>;

@Schema({
  collection: "rubber_compound_orders",
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true },
})
export class RubberCompoundOrder {
  @Prop({ type: Number })
  _id: number;

  @Prop({ type: String, required: true })
  firebaseUid: string;

  @Prop({ type: String, required: true })
  orderNumber: string;

  @Prop({ type: Number, required: true })
  compoundStockId: number;

  @Prop({ type: Number, required: true })
  quantityKg: number;

  @Prop({ type: String, required: true })
  status: string;

  @Prop({ type: Boolean, required: true })
  isAutoGenerated: boolean;

  @Prop({ type: String, required: false })
  supplierName: string;

  @Prop({ type: Date, required: false })
  expectedDelivery: Date;

  @Prop({ type: String, required: false })
  notes: string;

  @Prop({ type: String, required: false })
  createdBy: string;

  @Prop({ type: String, required: false })
  createdAt: string;

  @Prop({ type: String, required: false })
  updatedAt: string;
}

export const RubberCompoundOrderSchema = SchemaFactory.createForClass(RubberCompoundOrder);

RubberCompoundOrderSchema.virtual("compoundStock", {
  ref: "RubberCompoundStock",
  localField: "compoundStockId",
  foreignField: "_id",
  justOne: true,
});
