import type { mongo } from "mongoose";

interface SaProvinceLocations {
  province: string;
  districts: string[];
  cities: string[];
}

const SA_LOCATIONS: SaProvinceLocations[] = [
  {
    province: "Gauteng",
    districts: ["Johannesburg", "Tshwane", "Ekurhuleni", "Sedibeng", "West Rand"],
    cities: [
      "Johannesburg",
      "Pretoria",
      "Sandton",
      "Midrand",
      "Centurion",
      "Rosebank",
      "Bryanston",
      "Randburg",
      "Roodepoort",
      "Fourways",
      "Kempton Park",
      "Edenvale",
      "Bedfordview",
      "Germiston",
      "Alberton",
      "Boksburg",
      "Benoni",
      "Springs",
      "Brakpan",
      "Nigel",
      "Menlyn",
      "Hatfield",
      "Brooklyn",
      "Irene",
      "Montana",
      "Silverton",
      "Arcadia",
      "Lynnwood",
      "Soweto",
      "Tembisa",
      "Mamelodi",
      "Soshanguve",
      "Atteridgeville",
      "Vanderbijlpark",
      "Vereeniging",
      "Sebokeng",
      "Evaton",
      "Sharpeville",
      "Heidelberg",
      "Meyerton",
      "Krugersdorp",
      "Randfontein",
      "Carletonville",
      "Westonaria",
      "Magaliesburg",
      "Cullinan",
      "Bronkhorstspruit",
      "Emfuleni",
      "Mogale City",
      "Midvaal",
      "Lenasia",
      "Alexandra",
      "Vosloorus",
      "Katlehong",
      "Daveyton",
      "Kagiso",
      "Cosmo City",
      "Fochville",
    ],
  },
  {
    province: "Western Cape",
    districts: [
      "Cape Town",
      "Cape Winelands",
      "Central Karoo",
      "Garden Route",
      "Overberg",
      "West Coast",
    ],
    cities: [
      "Cape Town",
      "Bellville",
      "Durbanville",
      "Goodwood",
      "Parow",
      "Milnerton",
      "Table View",
      "Century City",
      "Constantia",
      "Claremont",
      "Wynberg",
      "Khayelitsha",
      "Mitchells Plain",
      "Somerset West",
      "Strand",
      "Gordon's Bay",
      "Stellenbosch",
      "Franschhoek",
      "Paarl",
      "Wellington",
      "Worcester",
      "Robertson",
      "Ceres",
      "Ashton",
      "Montagu",
      "Tulbagh",
      "George",
      "Knysna",
      "Mossel Bay",
      "Oudtshoorn",
      "Plettenberg Bay",
      "Sedgefield",
      "Wilderness",
      "Hermanus",
      "Gansbaai",
      "Bredasdorp",
      "Caledon",
      "Grabouw",
      "Swellendam",
      "Saldanha",
      "Vredenburg",
      "Langebaan",
      "Hopefield",
      "Malmesbury",
      "Piketberg",
      "Vredendal",
      "Clanwilliam",
      "Citrusdal",
      "Lambert's Bay",
      "Beaufort West",
      "Laingsburg",
      "Prince Albert",
      "Riversdale",
      "Ladismith",
      "Witzenberg",
      "Bergrivier",
      "Riebeek-Kasteel",
      "Kuilsrivier",
    ],
  },
  {
    province: "Eastern Cape",
    districts: [
      "Buffalo City",
      "Nelson Mandela Bay",
      "Alfred Nzo",
      "Amathole",
      "Chris Hani",
      "Joe Gqabi",
      "OR Tambo",
      "Sarah Baartman",
    ],
    cities: [
      "East London",
      "Gqeberha",
      "Port Elizabeth",
      "Uitenhage",
      "Kariega",
      "Despatch",
      "King William's Town",
      "Bhisho",
      "Mthatha",
      "Queenstown",
      "Komani",
      "Graaff-Reinet",
      "Cradock",
      "Grahamstown",
      "Makhanda",
      "Jeffreys Bay",
      "Humansdorp",
      "St Francis Bay",
      "Aliwal North",
      "Butterworth",
      "Gcuwa",
      "Stutterheim",
      "Somerset East",
      "Ngcobo",
      "Lady Frere",
      "Flagstaff",
      "Cofimvaba",
      "Kareedouw",
      "Qumbu",
      "Matatiele",
      "Dutywa",
      "Peddie",
      "Libode",
      "Port St Johns",
      "Alice",
      "Fort Beaufort",
      "Cala",
      "Port Alfred",
      "Kenton-on-Sea",
      "Adelaide",
      "Bedford",
      "Tarkastad",
      "Sterkstroom",
      "Molteno",
      "Indwe",
      "Elliot",
      "Maclear",
      "Mount Fletcher",
      "Mount Frere",
      "Bizana",
      "Lusikisiki",
      "Tsolo",
      "Cradock",
      "Willowmore",
      "Jansenville",
      "Steytlerville",
      "Hankey",
      "Patensie",
    ],
  },
  {
    province: "Free State",
    districts: ["Mangaung", "Fezile Dabi", "Lejweleputswa", "Thabo Mofutsanyana", "Xhariep"],
    cities: [
      "Bloemfontein",
      "Botshabelo",
      "Thaba Nchu",
      "Welkom",
      "Virginia",
      "Odendaalsrus",
      "Allanridge",
      "Ventersburg",
      "Hennenman",
      "Sasolburg",
      "Deneysville",
      "Oranjeville",
      "Kroonstad",
      "Viljoenskroon",
      "Parys",
      "Vredefort",
      "Heilbron",
      "Edenville",
      "Bethlehem",
      "Clarens",
      "Phuthaditjhaba",
      "Harrismith",
      "Kestell",
      "Reitz",
      "Vrede",
      "Memel",
      "Warden",
      "Tweeling",
      "Cornelia",
      "Frankfort",
      "Villiers",
      "Trompsburg",
      "Koffiefontein",
      "Theunissen",
      "Ladybrand",
      "Ficksburg",
      "Senekal",
      "Clocolan",
      "Marquard",
      "Winburg",
      "Brandfort",
      "Bothaville",
      "Hoopstad",
      "Bultfontein",
      "Dewetsdorp",
      "Wepener",
      "Zastron",
      "Smithfield",
      "Rouxville",
      "Jagersfontein",
      "Fauresmith",
      "Petrusburg",
      "Jacobsdal",
      "Boshof",
      "Hertzogville",
      "Reddersburg",
      "Edenburg",
      "Excelsior",
      "Tweespruit",
      "Hobhouse",
    ],
  },
  {
    province: "KwaZulu-Natal",
    districts: [
      "eThekwini",
      "Amajuba",
      "Harry Gwala",
      "iLembe",
      "King Cetshwayo",
      "Umkhanyakude",
      "Umzinyathi",
      "Uthukela",
      "Ugu",
      "Zululand",
    ],
    cities: [
      "Durban",
      "Pinetown",
      "Westville",
      "Chatsworth",
      "Phoenix",
      "Umhlanga",
      "Kloof",
      "Gillitts",
      "Hillcrest",
      "Amanzimtoti",
      "Cato Ridge",
      "Hammarsdale",
      "Pietermaritzburg",
      "Howick",
      "Hilton",
      "Newcastle",
      "Madadeni",
      "Richards Bay",
      "Empangeni",
      "eShowe",
      "Mtunzini",
      "Ballito",
      "KwaDukuza",
      "Stanger",
      "Salt Rock",
      "Tongaat",
      "Verulam",
      "Mandeni",
      "Maphumulo",
      "Port Shepstone",
      "Margate",
      "Shelly Beach",
      "Uvongo",
      "Ramsgate",
      "Pennington",
      "Scottburgh",
      "Hibberdene",
      "Kokstad",
      "Ixopo",
      "Creighton",
      "Underberg",
      "Himeville",
      "Bulwer",
      "Estcourt",
      "Mooi River",
      "Bergville",
      "Winterton",
      "Colenso",
      "Ladysmith",
      "Dundee",
      "Glencoe",
      "Greytown",
      "Kranskop",
      "Vryheid",
      "Paulpietersburg",
      "Pongola",
      "Ulundi",
      "Nongoma",
      "Nkandla",
      "Melmoth",
      "Babanango",
      "Nquthu",
      "Tugela Ferry",
      "Mtubatuba",
      "St Lucia",
      "Hluhluwe",
      "Mkuze",
      "Jozini",
      "Ubombo",
      "Manguzi",
      "Hlabisa",
      "Richmond",
      "Camperdown",
      "Wartburg",
      "New Hanover",
      "Ndwedwe",
      "Impendle",
    ],
  },
  {
    province: "Limpopo",
    districts: ["Capricorn", "Mopani", "Sekhukhune", "Vhembe", "Waterberg"],
    cities: [
      "Polokwane",
      "Seshego",
      "Mankweng",
      "Lebowakgomo",
      "Tzaneen",
      "Modjadjiskloof",
      "Letsitele",
      "Haenertsburg",
      "Phalaborwa",
      "Hoedspruit",
      "Giyani",
      "Mokopane",
      "Marble Hall",
      "Groblersdal",
      "Burgersfort",
      "Steelpoort",
      "Ohrigstad",
      "Jane Furse",
      "Apel",
      "Musina",
      "Louis Trichardt",
      "Makhado",
      "Thohoyandou",
      "Malamulele",
      "Elim",
      "Bela-Bela",
      "Modimolle",
      "Mookgophong",
      "Naboomspruit",
      "Nylstroom",
      "Lephalale",
      "Ellisras",
      "Vaalwater",
      "Thabazimbi",
      "Northam",
      "Senwabarwana",
      "Dendron",
      "Chuniespoort",
      "Roedtan",
      "Zebediela",
      "Gravelotte",
      "Mooketsi",
      "Duiwelskloof",
      "Warmbaths",
    ],
  },
  {
    province: "Mpumalanga",
    districts: ["Ehlanzeni", "Gert Sibande", "Nkangala"],
    cities: [
      "Nelspruit",
      "Mbombela",
      "White River",
      "Hazyview",
      "Sabie",
      "Graskop",
      "Pilgrim's Rest",
      "Barberton",
      "Malalane",
      "Komatipoort",
      "Marloth Park",
      "Skukuza",
      "KaNyamazane",
      "Kabokweni",
      "Bushbuckridge",
      "Witbank",
      "eMalahleni",
      "Middelburg",
      "Hendrina",
      "Kriel",
      "Belfast",
      "Machadodorp",
      "Waterval Boven",
      "Dullstroom",
      "Lydenburg",
      "Mashishing",
      "Delmas",
      "Secunda",
      "Evander",
      "Kinross",
      "Trichardt",
      "Bethal",
      "Standerton",
      "Ermelo",
      "Breyten",
      "Carolina",
      "Volksrust",
      "Wakkerstroom",
      "Amsterdam",
      "Piet Retief",
      "Balfour",
      "Siyabuswa",
      "Nkomazi",
      "Barberton",
    ],
  },
  {
    province: "Northern Cape",
    districts: ["Frances Baard", "John Taolo Gaetsewe", "Namakwa", "Pixley ka Seme", "ZF Mgcawu"],
    cities: [
      "Kimberley",
      "Warrenton",
      "Barkly West",
      "Hartswater",
      "Jan Kempdorp",
      "Ritchie",
      "Modder River",
      "Upington",
      "Kakamas",
      "Keimoes",
      "Kenhardt",
      "Groblershoop",
      "Augrabies",
      "Springbok",
      "Port Nolloth",
      "Nababeep",
      "Concordia",
      "Steinkopf",
      "Aggeneys",
      "Pofadder",
      "Garies",
      "Kamieskroon",
      "Kuruman",
      "Kathu",
      "Postmasburg",
      "Olifantshoek",
      "Daniëlskuil",
      "Mothibistad",
      "Ganyesa",
      "De Aar",
      "Colesberg",
      "Britstown",
      "Hanover",
      "Noupoort",
      "Richmond",
      "Victoria West",
      "Calvinia",
      "Williston",
      "Carnarvon",
      "Sutherland",
      "Fraserburg",
      "Loxton",
      "Brandvlei",
      "Vanwyksvlei",
      "Prieska",
      "Douglas",
      "Hopetown",
      "Griekwastad",
      "Petrusville",
      "Marydale",
    ],
  },
  {
    province: "North West",
    districts: [
      "Bojanala",
      "Dr Kenneth Kaunda",
      "Dr Ruth Segomotsi Mompati",
      "Ngaka Modiri Molema",
    ],
    cities: [
      "Rustenburg",
      "Phokeng",
      "Marikana",
      "Boshoek",
      "Mogwase",
      "Brits",
      "Hartbeespoort",
      "Madibeng",
      "Koster",
      "Swartruggens",
      "Groot Marico",
      "Klerksdorp",
      "Stilfontein",
      "Orkney",
      "Potchefstroom",
      "Ventersdorp",
      "Mahikeng",
      "Mafikeng",
      "Zeerust",
      "Lichtenburg",
      "Coligny",
      "Delareyville",
      "Sannieshof",
      "Ottosdal",
      "Vryburg",
      "Taung",
      "Christiana",
      "Bloemhof",
      "Schweizer-Reneke",
      "Wolmaransstad",
      "Makwassie",
      "Leeudoringstad",
      "Ganyesa",
      "Reivilo",
      "Pomfret",
      "Setlagole",
      "Makapanstad",
    ],
  },
];

function citiesForProvince(province: string | null): string[] {
  if (!province) return [];
  const match = SA_LOCATIONS.find((p) => p.province.toLowerCase() === province.toLowerCase());
  return match ? [...match.cities] : [];
}

function containsTerm(haystackLower: string, termLower: string): boolean {
  let from = 0;
  for (;;) {
    const idx = haystackLower.indexOf(termLower, from);
    if (idx === -1) return false;
    const before = idx === 0 ? "" : haystackLower[idx - 1];
    const afterIdx = idx + termLower.length;
    const after = afterIdx >= haystackLower.length ? "" : haystackLower[afterIdx];
    const isBoundary = (ch: string) => ch === "" || !/[a-z]/i.test(ch);
    if (isBoundary(before) && isBoundary(after)) return true;
    from = idx + 1;
  }
}

function resolveProvince(locationText: string | null): string | null {
  if (!locationText) return null;
  const hay = locationText.toLowerCase();

  for (const p of SA_LOCATIONS) {
    if (containsTerm(hay, p.province.toLowerCase())) return p.province;
  }
  for (const p of SA_LOCATIONS) {
    if (p.districts.some((d) => containsTerm(hay, d.toLowerCase()))) return p.province;
  }
  let best: { province: string; len: number } | null = null;
  for (const p of SA_LOCATIONS) {
    for (const city of p.cities) {
      const cl = city.toLowerCase();
      if (containsTerm(hay, cl) && (best === null || cl.length > best.len)) {
        best = { province: p.province, len: cl.length };
      }
    }
  }
  return best ? best.province : null;
}

function resolveCity(locationText: string | null, province: string | null): string | null {
  if (!locationText) return null;
  const hay = locationText.toLowerCase();
  const pools = province ? [citiesForProvince(province)] : SA_LOCATIONS.map((p) => p.cities);
  let best: { city: string; len: number } | null = null;
  for (const pool of pools) {
    for (const city of pool) {
      const cl = city.toLowerCase();
      if (containsTerm(hay, cl) && (best === null || cl.length > best.len)) {
        best = { city, len: cl.length };
      }
    }
  }
  return best ? best.city : null;
}

function resolveLocation(locationText: string | null): {
  province: string | null;
  city: string | null;
} {
  const province = resolveProvince(locationText);
  return { province, city: resolveCity(locationText, province) };
}

const COLLECTION = "cv_assistant_external_jobs";
const BATCH = 500;

export async function up(db: mongo.Db): Promise<void> {
  const jobs = db.collection(COLLECTION);
  const cursor = jobs.find({}, { projection: { locationArea: 1, locationRaw: 1 } });

  let ops: mongo.AnyBulkWriteOperation[] = [];
  for await (const job of cursor) {
    const area = typeof job.locationArea === "string" ? job.locationArea : "";
    const raw = typeof job.locationRaw === "string" ? job.locationRaw : "";
    const { province, city } = resolveLocation(`${area} ${raw}`);
    ops.push({
      updateOne: {
        filter: { _id: job._id },
        update: { $set: { canonicalProvince: province, canonicalCity: city } },
      },
    });
    if (ops.length >= BATCH) {
      await jobs.bulkWrite(ops);
      ops = [];
    }
  }
  if (ops.length > 0) {
    await jobs.bulkWrite(ops);
  }
}

export async function down(): Promise<void> {
  // Forward-only: derived location data, recomputed on next ingest/backfill.
}
