import { Module } from "@nestjs/common";
import { ScheduleModule } from "@nestjs/schedule";
import { TypeOrmModule } from "@nestjs/typeorm";
import { AdminModule } from "../admin/admin.module";
import { EmailModule } from "../email/email.module";
import { StorageModule } from "../storage/storage.module";
import { User } from "../user/entities/user.entity";
import { AnnixRepAuthModule } from "./auth";
import {
  AnalyticsController,
  BookingController,
  CalendarController,
  CrmController,
  CustomFieldController,
  GoalsController,
  ManagerDashboardController,
  MeetingController,
  MeetingPlatformController,
  OrganizationController,
  PlatformWebhookController,
  ProspectController,
  ProspectHandoffController,
  PublicBookingController,
  RecordingController,
  ReportsController,
  RouteController,
  SummaryController,
  TeamActivityController,
  TeamController,
  TeamInvitationController,
  TeamsBotController,
  TeamsBotWebhookController,
  TerritoryController,
  TranscriptController,
  VisitController,
} from "./controllers";
import { DiscoveryModule } from "./discovery";
import {
  BookingLink,
  CalendarColor,
  CalendarConnection,
  CalendarEvent,
  CrmConfig,
  CrmSyncLog,
  CustomFieldDefinition,
  Meeting,
  MeetingPlatformConnection,
  MeetingRecording,
  MeetingTranscript,
  Organization,
  PlatformMeetingRecord,
  Prospect,
  ProspectActivity,
  SalesGoal,
  SyncConflict,
  TeamActivity,
  TeamInvitation,
  TeamMember,
  TeamsBotSession,
  Territory,
  Visit,
} from "./entities";
import { TeamsBotGateway } from "./gateways/teams-bot.gateway";
import {
  CaldavCalendarProvider,
  GoogleCalendarProvider,
  GoogleMeetProvider,
  HubSpotOAuthProvider,
  OutlookCalendarProvider,
  PipedriveOAuthProvider,
  SalesforceOAuthProvider,
  TeamsBotProvider,
  TeamsMeetingProvider,
  ZoomMeetingProvider,
} from "./providers";
import { RepProfileModule } from "./rep-profile";
import {
  AnalyticsService,
  BookingService,
  CalendarColorService,
  CalendarService,
  CalendarSyncService,
  CalendarWebhookService,
  CrmService,
  CrmSyncService,
  CustomFieldService,
  FollowUpReminderService,
  GoalsService,
  MeetingPlatformService,
  MeetingSchedulerService,
  MeetingService,
  MeetingSummaryService,
  OrganizationService,
  PdfGenerationService,
  PlatformRecordingService,
  ProspectActivityService,
  ProspectHandoffService,
  ProspectService,
  RecordingService,
  RecurringMeetingService,
  ReportsService,
  RoutePlanningService,
  SpeakerDiarizationService,
  TeamActivityService,
  TeamAnalyticsService,
  TeamInvitationService,
  TeamsBotAudioService,
  TeamsBotService,
  TeamService,
  TerritoryService,
  TranscriptionService,
  VisitService,
} from "./services";

@Module({
  imports: [
    TypeOrmModule.forFeature([
      BookingLink,
      Prospect,
      ProspectActivity,
      CustomFieldDefinition,
      Visit,
      Meeting,
      MeetingRecording,
      MeetingTranscript,
      MeetingPlatformConnection,
      PlatformMeetingRecord,
      CalendarColor,
      CalendarConnection,
      CalendarEvent,
      CrmConfig,
      CrmSyncLog,
      SalesGoal,
      SyncConflict,
      User,
      Organization,
      TeamMember,
      Territory,
      TeamInvitation,
      TeamActivity,
      TeamsBotSession,
    ]),
    StorageModule,
    ScheduleModule.forRoot(),
    AdminModule,
    EmailModule,
    RepProfileModule,
    AnnixRepAuthModule,
    DiscoveryModule,
  ],
  controllers: [
    AnalyticsController,
    BookingController,
    GoalsController,
    ProspectController,
    CustomFieldController,
    VisitController,
    MeetingController,
    MeetingPlatformController,
    CalendarController,
    PublicBookingController,
    RecordingController,
    TranscriptController,
    SummaryController,
    CrmController,
    RouteController,
    ReportsController,
    OrganizationController,
    TeamController,
    TeamInvitationController,
    TerritoryController,
    ProspectHandoffController,
    TeamActivityController,
    ManagerDashboardController,
    PlatformWebhookController,
    TeamsBotController,
    TeamsBotWebhookController,
    TeamsBotGateway,
  ],
  providers: [
    AnalyticsService,
    BookingService,
    CalendarColorService,
    CalendarWebhookService,
    FollowUpReminderService,
    GoalsService,
    MeetingPlatformService,
    MeetingSchedulerService,
    PlatformRecordingService,
    ProspectActivityService,
    ProspectService,
    CustomFieldService,
    VisitService,
    MeetingService,
    RecurringMeetingService,
    CalendarService,
    CalendarSyncService,
    RecordingService,
    SpeakerDiarizationService,
    TranscriptionService,
    MeetingSummaryService,
    CrmService,
    CrmSyncService,
    RoutePlanningService,
    ReportsService,
    PdfGenerationService,
    GoogleCalendarProvider,
    GoogleMeetProvider,
    OutlookCalendarProvider,
    CaldavCalendarProvider,
    SalesforceOAuthProvider,
    HubSpotOAuthProvider,
    PipedriveOAuthProvider,
    ZoomMeetingProvider,
    TeamsMeetingProvider,
    TeamsBotProvider,
    TeamsBotService,
    TeamsBotAudioService,
    TeamsBotGateway,
    OrganizationService,
    TeamService,
    TerritoryService,
    TeamInvitationService,
    TeamActivityService,
    ProspectHandoffService,
    TeamAnalyticsService,
  ],
  exports: [
    ProspectService,
    VisitService,
    MeetingService,
    MeetingPlatformService,
    PlatformRecordingService,
    CalendarService,
    RecordingService,
    TranscriptionService,
    MeetingSummaryService,
    CrmService,
    RepProfileModule,
    AnnixRepAuthModule,
  ],
})
export class AnnixRepModule {}
