import { Module } from "@nestjs/common";
import { ScheduleModule } from "@nestjs/schedule";
import { TypeOrmModule } from "@nestjs/typeorm";
import { AdminModule } from "../admin/admin.module";
import { AnnixRepAuthModule } from "./auth";
import {
  AnalyticsController,
  CalendarController,
  CrmController,
  CustomFieldController,
  GoalsController,
  MeetingController,
  ProspectController,
  RecordingController,
  RouteController,
  SummaryController,
  TranscriptController,
  VisitController,
} from "./controllers";
import {
  CalendarConnection,
  CalendarEvent,
  CrmConfig,
  CustomFieldDefinition,
  Meeting,
  MeetingRecording,
  MeetingTranscript,
  Prospect,
  ProspectActivity,
  SalesGoal,
  Visit,
} from "./entities";
import {
  CaldavCalendarProvider,
  GoogleCalendarProvider,
  OutlookCalendarProvider,
} from "./providers";
import { RepProfileModule } from "./rep-profile";
import {
  AnalyticsService,
  CalendarService,
  CalendarSyncService,
  CrmService,
  CustomFieldService,
  GoalsService,
  MeetingService,
  MeetingSummaryService,
  ProspectActivityService,
  ProspectService,
  RecordingService,
  RoutePlanningService,
  SpeakerDiarizationService,
  TranscriptionService,
  VisitService,
} from "./services";

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Prospect,
      ProspectActivity,
      CustomFieldDefinition,
      Visit,
      Meeting,
      MeetingRecording,
      MeetingTranscript,
      CalendarConnection,
      CalendarEvent,
      CrmConfig,
      SalesGoal,
    ]),
    ScheduleModule.forRoot(),
    AdminModule,
    RepProfileModule,
    AnnixRepAuthModule,
  ],
  controllers: [
    AnalyticsController,
    GoalsController,
    ProspectController,
    CustomFieldController,
    VisitController,
    MeetingController,
    CalendarController,
    RecordingController,
    TranscriptController,
    SummaryController,
    CrmController,
    RouteController,
  ],
  providers: [
    AnalyticsService,
    GoalsService,
    ProspectActivityService,
    ProspectService,
    CustomFieldService,
    VisitService,
    MeetingService,
    CalendarService,
    CalendarSyncService,
    RecordingService,
    SpeakerDiarizationService,
    TranscriptionService,
    MeetingSummaryService,
    CrmService,
    RoutePlanningService,
    GoogleCalendarProvider,
    OutlookCalendarProvider,
    CaldavCalendarProvider,
  ],
  exports: [
    ProspectService,
    VisitService,
    MeetingService,
    CalendarService,
    RecordingService,
    TranscriptionService,
    MeetingSummaryService,
    CrmService,
    RepProfileModule,
    AnnixRepAuthModule,
  ],
})
export class AnnixRepModule {}
