export interface Currency {
  code: string;
  name: string;
  symbol: string;
  country: string;
}

const TOP_CURRENCIES: Currency[] = [
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', country: 'South Africa' },
  { code: 'USD', name: 'US Dollar', symbol: '$', country: 'United States' },
  { code: 'EUR', name: 'Euro', symbol: '€', country: 'European Union' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', country: 'Japan' },
  { code: 'GBP', name: 'British Pound', symbol: '£', country: 'United Kingdom' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', country: 'China' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', country: 'Australia' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', country: 'Canada' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', country: 'Switzerland' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', country: 'Hong Kong' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', country: 'Singapore' },
];

const OTHER_CURRENCIES: Currency[] = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', country: 'United Arab Emirates' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', country: 'Afghanistan' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', country: 'Albania' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', country: 'Armenia' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', country: 'Curaçao' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', country: 'Angola' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', country: 'Argentina' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', country: 'Aruba' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', country: 'Azerbaijan' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', country: 'Bosnia and Herzegovina' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', country: 'Barbados' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', country: 'Bangladesh' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', country: 'Bulgaria' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', country: 'Bahrain' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', country: 'Burundi' },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', country: 'Bermuda' },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', country: 'Brunei' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', country: 'Bolivia' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', country: 'Brazil' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', country: 'Bahamas' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', country: 'Bhutan' },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', country: 'Botswana' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', country: 'Belarus' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', country: 'Belize' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', country: 'Democratic Republic of the Congo' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', country: 'Chile' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', country: 'Colombia' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', country: 'Costa Rica' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱', country: 'Cuba' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', country: 'Cape Verde' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', country: 'Czech Republic' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', country: 'Djibouti' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', country: 'Denmark' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', country: 'Dominican Republic' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', country: 'Algeria' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£', country: 'Egypt' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', country: 'Eritrea' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', country: 'Ethiopia' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', country: 'Fiji' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', country: 'Falkland Islands' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', country: 'Georgia' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', country: 'Ghana' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', country: 'Gibraltar' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', country: 'Gambia' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', country: 'Guinea' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', country: 'Guatemala' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', country: 'Guyana' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', country: 'Honduras' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', country: 'Croatia' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', country: 'Haiti' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', country: 'Hungary' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', country: 'Indonesia' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', country: 'Israel' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', country: 'India' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', country: 'Iraq' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', country: 'Iran' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', country: 'Iceland' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', country: 'Jamaica' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', country: 'Jordan' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', country: 'Kenya' },
  { code: 'KGS', name: 'Kyrgystani Som', symbol: 'лв', country: 'Kyrgyzstan' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', country: 'Cambodia' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', country: 'Comoros' },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩', country: 'North Korea' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', country: 'South Korea' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', country: 'Kuwait' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', country: 'Cayman Islands' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', country: 'Kazakhstan' },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', country: 'Laos' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', country: 'Lebanon' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', country: 'Sri Lanka' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', country: 'Liberia' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', country: 'Lesotho' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', country: 'Libya' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', country: 'Morocco' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', country: 'Moldova' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', country: 'Madagascar' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', country: 'North Macedonia' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', country: 'Myanmar' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', country: 'Mongolia' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', country: 'Macau' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', country: 'Mauritania' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', country: 'Mauritius' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', country: 'Maldives' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', country: 'Malawi' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', country: 'Mexico' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', country: 'Malaysia' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', country: 'Mozambique' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', country: 'Namibia' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', country: 'Nigeria' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', country: 'Nicaragua' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', country: 'Norway' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', country: 'Nepal' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', country: 'New Zealand' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', country: 'Oman' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', country: 'Panama' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', country: 'Peru' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', country: 'Papua New Guinea' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', country: 'Philippines' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', country: 'Pakistan' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', country: 'Poland' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', country: 'Paraguay' },
  { code: 'QAR', name: 'Qatari Rial', symbol: 'ر.ق', country: 'Qatar' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', country: 'Romania' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', country: 'Serbia' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', country: 'Russia' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', country: 'Rwanda' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', country: 'Saudi Arabia' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', country: 'Solomon Islands' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', country: 'Seychelles' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', country: 'Sudan' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', country: 'Sweden' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', country: 'Saint Helena' },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', country: 'Sierra Leone' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', country: 'Somalia' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', country: 'Suriname' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', country: 'South Sudan' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', country: 'São Tomé and Príncipe' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', country: 'Syria' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', country: 'Eswatini' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', country: 'Thailand' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', country: 'Tajikistan' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', country: 'Turkmenistan' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', country: 'Tunisia' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', country: 'Tonga' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', country: 'Turkey' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', country: 'Trinidad and Tobago' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', country: 'Taiwan' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', country: 'Tanzania' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', country: 'Ukraine' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', country: 'Uganda' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', country: 'Uruguay' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв', country: 'Uzbekistan' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.', country: 'Venezuela' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', country: 'Vietnam' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', country: 'Vanuatu' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', country: 'Samoa' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', country: 'Central African States' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', country: 'East Caribbean' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', country: 'West African States' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', country: 'French Pacific' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', country: 'Yemen' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', country: 'Zambia' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$', country: 'Zimbabwe' },
];

const sortedOtherCurrencies = OTHER_CURRENCIES.sort((a, b) => a.country.localeCompare(b.country));

export const CURRENCIES: Currency[] = [...TOP_CURRENCIES, ...sortedOtherCurrencies];

export const DEFAULT_CURRENCY = 'ZAR';

export function currencyByCode(code: string): Currency | null {
  return CURRENCIES.find((c) => c.code === code) ?? null;
}

export function formatCurrencyLabel(currency: Currency): string {
  return `${currency.code} - ${currency.name}`;
}

export function filterCurrencies(searchTerm: string): Currency[] {
  if (!searchTerm.trim()) {
    return CURRENCIES;
  }

  const term = searchTerm.toLowerCase();
  return CURRENCIES.filter(
    (currency) =>
      currency.code.toLowerCase().includes(term) ||
      currency.name.toLowerCase().includes(term) ||
      currency.country.toLowerCase().includes(term)
  );
}

const COUNTRY_TO_CURRENCY: Record<string, string> = {
  'south africa': 'ZAR',
  'united states': 'USD',
  'usa': 'USD',
  'us': 'USD',
  'america': 'USD',
  'united kingdom': 'GBP',
  'uk': 'GBP',
  'great britain': 'GBP',
  'britain': 'GBP',
  'england': 'GBP',
  'scotland': 'GBP',
  'wales': 'GBP',
  'northern ireland': 'GBP',
  'european union': 'EUR',
  'eu': 'EUR',
  'germany': 'EUR',
  'france': 'EUR',
  'italy': 'EUR',
  'spain': 'EUR',
  'netherlands': 'EUR',
  'belgium': 'EUR',
  'austria': 'EUR',
  'ireland': 'EUR',
  'portugal': 'EUR',
  'greece': 'EUR',
  'finland': 'EUR',
  'slovakia': 'EUR',
  'slovenia': 'EUR',
  'estonia': 'EUR',
  'latvia': 'EUR',
  'lithuania': 'EUR',
  'cyprus': 'EUR',
  'malta': 'EUR',
  'luxembourg': 'EUR',
  'japan': 'JPY',
  'china': 'CNY',
  'australia': 'AUD',
  'canada': 'CAD',
  'switzerland': 'CHF',
  'hong kong': 'HKD',
  'singapore': 'SGD',
  'united arab emirates': 'AED',
  'uae': 'AED',
  'dubai': 'AED',
  'afghanistan': 'AFN',
  'albania': 'ALL',
  'armenia': 'AMD',
  'angola': 'AOA',
  'argentina': 'ARS',
  'azerbaijan': 'AZN',
  'bosnia and herzegovina': 'BAM',
  'bosnia': 'BAM',
  'barbados': 'BBD',
  'bangladesh': 'BDT',
  'bulgaria': 'BGN',
  'bahrain': 'BHD',
  'burundi': 'BIF',
  'bermuda': 'BMD',
  'brunei': 'BND',
  'bolivia': 'BOB',
  'brazil': 'BRL',
  'bahamas': 'BSD',
  'bhutan': 'BTN',
  'botswana': 'BWP',
  'belarus': 'BYN',
  'belize': 'BZD',
  'democratic republic of the congo': 'CDF',
  'congo': 'CDF',
  'drc': 'CDF',
  'chile': 'CLP',
  'colombia': 'COP',
  'costa rica': 'CRC',
  'cuba': 'CUP',
  'cape verde': 'CVE',
  'czech republic': 'CZK',
  'czechia': 'CZK',
  'djibouti': 'DJF',
  'denmark': 'DKK',
  'dominican republic': 'DOP',
  'algeria': 'DZD',
  'egypt': 'EGP',
  'eritrea': 'ERN',
  'ethiopia': 'ETB',
  'fiji': 'FJD',
  'falkland islands': 'FKP',
  'georgia': 'GEL',
  'ghana': 'GHS',
  'gibraltar': 'GIP',
  'gambia': 'GMD',
  'guinea': 'GNF',
  'guatemala': 'GTQ',
  'guyana': 'GYD',
  'honduras': 'HNL',
  'croatia': 'HRK',
  'haiti': 'HTG',
  'hungary': 'HUF',
  'indonesia': 'IDR',
  'israel': 'ILS',
  'india': 'INR',
  'iraq': 'IQD',
  'iran': 'IRR',
  'iceland': 'ISK',
  'jamaica': 'JMD',
  'jordan': 'JOD',
  'kenya': 'KES',
  'kyrgyzstan': 'KGS',
  'cambodia': 'KHR',
  'comoros': 'KMF',
  'north korea': 'KPW',
  'south korea': 'KRW',
  'korea': 'KRW',
  'kuwait': 'KWD',
  'cayman islands': 'KYD',
  'kazakhstan': 'KZT',
  'laos': 'LAK',
  'lebanon': 'LBP',
  'sri lanka': 'LKR',
  'liberia': 'LRD',
  'lesotho': 'LSL',
  'libya': 'LYD',
  'morocco': 'MAD',
  'moldova': 'MDL',
  'madagascar': 'MGA',
  'north macedonia': 'MKD',
  'macedonia': 'MKD',
  'myanmar': 'MMK',
  'burma': 'MMK',
  'mongolia': 'MNT',
  'macau': 'MOP',
  'mauritania': 'MRU',
  'mauritius': 'MUR',
  'maldives': 'MVR',
  'malawi': 'MWK',
  'mexico': 'MXN',
  'malaysia': 'MYR',
  'mozambique': 'MZN',
  'namibia': 'NAD',
  'nigeria': 'NGN',
  'nicaragua': 'NIO',
  'norway': 'NOK',
  'nepal': 'NPR',
  'new zealand': 'NZD',
  'oman': 'OMR',
  'panama': 'PAB',
  'peru': 'PEN',
  'papua new guinea': 'PGK',
  'philippines': 'PHP',
  'pakistan': 'PKR',
  'poland': 'PLN',
  'paraguay': 'PYG',
  'qatar': 'QAR',
  'romania': 'RON',
  'serbia': 'RSD',
  'russia': 'RUB',
  'rwanda': 'RWF',
  'saudi arabia': 'SAR',
  'solomon islands': 'SBD',
  'seychelles': 'SCR',
  'sudan': 'SDG',
  'sweden': 'SEK',
  'saint helena': 'SHP',
  'sierra leone': 'SLE',
  'somalia': 'SOS',
  'suriname': 'SRD',
  'south sudan': 'SSP',
  'sao tome and principe': 'STN',
  'syria': 'SYP',
  'eswatini': 'SZL',
  'swaziland': 'SZL',
  'thailand': 'THB',
  'tajikistan': 'TJS',
  'turkmenistan': 'TMT',
  'tunisia': 'TND',
  'tonga': 'TOP',
  'turkey': 'TRY',
  'trinidad and tobago': 'TTD',
  'trinidad': 'TTD',
  'taiwan': 'TWD',
  'tanzania': 'TZS',
  'ukraine': 'UAH',
  'uganda': 'UGX',
  'uruguay': 'UYU',
  'uzbekistan': 'UZS',
  'venezuela': 'VES',
  'vietnam': 'VND',
  'vanuatu': 'VUV',
  'samoa': 'WST',
  'yemen': 'YER',
  'zambia': 'ZMW',
  'zimbabwe': 'ZWL',
};

export function currencyCodeForCountry(countryName: string): string | null {
  if (!countryName) return null;
  const normalized = countryName.toLowerCase().trim();
  return COUNTRY_TO_CURRENCY[normalized] ?? null;
}

const CURRENCY_VAT_RATES: Record<string, number> = {
  ZAR: 15,
  GBP: 20,
  EUR: 20,
  USD: 0,
  JPY: 10,
  CNY: 13,
  AUD: 10,
  CAD: 5,
  CHF: 8.1,
  HKD: 0,
  SGD: 9,
  AED: 5,
  INR: 18,
  BRL: 17,
  MXN: 16,
  KRW: 10,
  RUB: 20,
  TRY: 20,
  PLN: 23,
  SEK: 25,
  NOK: 25,
  DKK: 25,
  NZD: 15,
  THB: 7,
  MYR: 6,
  IDR: 11,
  PHP: 12,
  VND: 10,
  NGN: 7.5,
  KES: 16,
  EGP: 14,
  PKR: 18,
  BDT: 15,
  CZK: 21,
  HUF: 27,
  RON: 19,
  BGN: 20,
  HRK: 25,
  ILS: 17,
  CLP: 19,
  COP: 19,
  PEN: 18,
  ARS: 21,
  SAR: 15,
  QAR: 0,
  KWD: 0,
  OMR: 5,
  BHD: 10,
  JOD: 16,
  LBP: 11,
  MAD: 20,
  TND: 19,
  DZD: 19,
  GHS: 15,
  TZS: 18,
  UGX: 18,
  ZMW: 16,
  BWP: 14,
  NAD: 15,
  MUR: 15,
  MZN: 17,
};

export function vatRateForCurrency(currencyCode: string): number {
  return CURRENCY_VAT_RATES[currencyCode] ?? 0;
}
