import { Injectable, Logger } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { RfqSurfaceProtection } from "./entities/rfq-surface-protection.entity";

export interface SpDocumentData {
  projectName: string;
  customerName: string;
  rfqNumber: string;
  revision: string;
  date: string;
  surfaceProtection: RfqSurfaceProtection;
  items?: SpLineItem[];
}

export interface SpLineItem {
  itemNumber: number;
  description: string;
  nominalBoreMm: number;
  lengthM: number;
  quantity: number;
  internalAreaM2: number;
  externalAreaM2: number;
}

export interface SpQuantitySummary {
  totalInternalAreaM2: number;
  totalExternalAreaM2: number;
  totalAreaM2: number;
  totalPaintLiters: number;
  totalRubberM2: number;
  totalCeramicTiles: number;
  itemCount: number;
  systemDescriptions: string[];
}

@Injectable()
export class SpDocumentGenerationService {
  private readonly logger = new Logger(SpDocumentGenerationService.name);

  constructor(
    @InjectRepository(RfqSurfaceProtection)
    private readonly rfqSpRepo: Repository<RfqSurfaceProtection>,
  ) {}

  generateCoatingScheduleHtml(data: SpDocumentData): string {
    const sp = data.surfaceProtection;

    return `
<!DOCTYPE html>
<html>
<head>
  <title>Coating Schedule - ${data.projectName}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 900px; margin: 0 auto; font-size: 11pt; }
    h1 { color: #1a1a1a; border-bottom: 3px solid #2563eb; padding-bottom: 10px; font-size: 18pt; }
    h2 { color: #374151; margin-top: 25px; font-size: 14pt; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
    h3 { color: #4b5563; margin-top: 18px; font-size: 12pt; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border: 1px solid #d1d5db; padding: 8px 10px; text-align: left; }
    th { background-color: #f3f4f6; font-weight: 600; }
    .header-table { border: none; margin-bottom: 25px; }
    .header-table td { border: none; padding: 3px 10px; }
    .header-table .label { font-weight: 600; width: 120px; }
    .total-row { background-color: #dbeafe; font-weight: bold; }
    .section { margin-bottom: 25px; }
    .note { font-size: 10pt; color: #6b7280; margin-top: 15px; padding: 12px; background: #f9fafb; border-radius: 4px; }
    .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 9pt; border-top: 1px solid #e5e7eb; padding-top: 15px; }
    .coat-row td:first-child { width: 25%; }
    .coat-row td:nth-child(2) { width: 45%; }
    .coat-row td:nth-child(3) { width: 15%; text-align: center; }
    .coat-row td:nth-child(4) { width: 15%; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Coating Specification Schedule</h1>

  <table class="header-table">
    <tr><td class="label">Project:</td><td>${data.projectName}</td><td class="label">Date:</td><td>${data.date}</td></tr>
    <tr><td class="label">Customer:</td><td>${data.customerName}</td><td class="label">Rev:</td><td>${data.revision}</td></tr>
    <tr><td class="label">RFQ No:</td><td>${data.rfqNumber}</td><td class="label">Document:</td><td>Coating Schedule</td></tr>
  </table>

  ${this.renderExternalCoatingSection(sp)}

  ${this.renderInternalLiningSection(sp)}

  ${this.renderSurfaceAreaSummary(sp)}

  <div class="note">
    <strong>General Notes:</strong>
    <ul>
      <li>All coatings to be applied in accordance with manufacturer's Technical Data Sheets (TDS)</li>
      <li>Surface preparation to be verified by certified inspector before coating application</li>
      <li>DFT measurements to be recorded as per ISO 2808</li>
      <li>Environmental conditions during application: RH <85%, Steel temp min 3 deg C above dew point</li>
      <li>Overcoating intervals per manufacturer specifications</li>
      ${sp.notes ? `<li>${sp.notes}</li>` : ""}
    </ul>
  </div>

  <div class="footer">
    Generated by Annix RFQ System | ${data.date}
  </div>
</body>
</html>
    `;
  }

  generateApplicationProcedureHtml(data: SpDocumentData): string {
    const sp = data.surfaceProtection;

    return `
<!DOCTYPE html>
<html>
<head>
  <title>Application Procedure - ${data.projectName}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 900px; margin: 0 auto; font-size: 11pt; }
    h1 { color: #1a1a1a; border-bottom: 3px solid #2563eb; padding-bottom: 10px; font-size: 18pt; }
    h2 { color: #374151; margin-top: 25px; font-size: 14pt; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
    h3 { color: #4b5563; margin-top: 18px; font-size: 12pt; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border: 1px solid #d1d5db; padding: 8px 10px; text-align: left; }
    th { background-color: #f3f4f6; font-weight: 600; }
    .header-table { border: none; margin-bottom: 25px; }
    .header-table td { border: none; padding: 3px 10px; }
    .header-table .label { font-weight: 600; width: 120px; }
    .procedure-step { margin: 15px 0; padding: 12px; background: #f9fafb; border-left: 4px solid #2563eb; }
    .procedure-step h4 { margin: 0 0 8px 0; color: #1e40af; }
    .procedure-step p { margin: 5px 0; }
    .warning { background: #fef3c7; border-left-color: #d97706; }
    .warning h4 { color: #92400e; }
    .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 9pt; border-top: 1px solid #e5e7eb; padding-top: 15px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Application Procedure</h1>

  <table class="header-table">
    <tr><td class="label">Project:</td><td>${data.projectName}</td><td class="label">Date:</td><td>${data.date}</td></tr>
    <tr><td class="label">Customer:</td><td>${data.customerName}</td><td class="label">Rev:</td><td>${data.revision}</td></tr>
    <tr><td class="label">RFQ No:</td><td>${data.rfqNumber}</td><td class="label">Document:</td><td>Application Procedure</td></tr>
  </table>

  <h2>1. Pre-Application Requirements</h2>

  <div class="procedure-step">
    <h4>1.1 Material Verification</h4>
    <p>Verify all coating/lining materials match specification requirements</p>
    <p>Check batch numbers, expiry dates, and storage conditions</p>
    <p>Ensure mixing ratios and pot life are understood</p>
  </div>

  <div class="procedure-step">
    <h4>1.2 Environmental Conditions</h4>
    <p>Ambient Temperature: ${sp.applicationTempC || "15-35"} deg C</p>
    <p>Relative Humidity: Max ${sp.applicationHumidityPercent || "85"}%</p>
    <p>Steel temperature must be minimum 3 deg C above dew point</p>
    <p>No application during rain, fog, or high wind conditions</p>
  </div>

  <div class="procedure-step warning">
    <h4>1.3 Safety Requirements</h4>
    <p>PPE: Safety glasses, gloves, respirator as per MSDS</p>
    <p>Adequate ventilation required for enclosed spaces</p>
    <p>Fire extinguisher and first aid kit must be available</p>
  </div>

  <h2>2. Surface Preparation</h2>

  <div class="procedure-step">
    <h4>2.1 Blast Cleaning</h4>
    <p>Standard: ${sp.surfacePrepStandard || "ISO 8501-1 Sa 2.5"}</p>
    <p>Profile: 40-75 microns (depending on system requirements)</p>
    <p>Inspect for oil, grease, mill scale, rust, and other contaminants</p>
    <p>All sharp edges to be rounded to minimum 2mm radius</p>
  </div>

  <div class="procedure-step">
    <h4>2.2 Dust and Debris Removal</h4>
    <p>Use clean, dry compressed air or vacuum</p>
    <p>Dust rating per ISO 8502-3: Maximum Rating 2</p>
    <p>Apply coating within 4 hours of blast cleaning (or before flash rust)</p>
  </div>

  ${sp.externalCoatingRequired ? this.renderExternalCoatingProcedure(sp) : ""}

  ${sp.internalLiningRequired ? this.renderInternalLiningProcedure(sp) : ""}

  <h2>4. Post-Application</h2>

  <div class="procedure-step">
    <h4>4.1 Curing</h4>
    <p>Allow minimum cure time per TDS before handling</p>
    <p>Protect from mechanical damage during cure</p>
    <p>Maintain environmental conditions during full cure</p>
  </div>

  <div class="procedure-step">
    <h4>4.2 Final Inspection</h4>
    <p>DFT verification per ISO 2808</p>
    <p>Holiday detection where specified</p>
    <p>Visual inspection for defects, runs, sags</p>
    <p>Documentation and sign-off</p>
  </div>

  <div class="footer">
    Generated by Annix RFQ System | ${data.date}
  </div>
</body>
</html>
    `;
  }

  generateInspectionChecklistHtml(data: SpDocumentData): string {
    const sp = data.surfaceProtection;

    return `
<!DOCTYPE html>
<html>
<head>
  <title>Inspection Checklist - ${data.projectName}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 900px; margin: 0 auto; font-size: 11pt; }
    h1 { color: #1a1a1a; border-bottom: 3px solid #2563eb; padding-bottom: 10px; font-size: 18pt; }
    h2 { color: #374151; margin-top: 25px; font-size: 14pt; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border: 1px solid #d1d5db; padding: 8px 10px; text-align: left; }
    th { background-color: #f3f4f6; font-weight: 600; }
    .header-table { border: none; margin-bottom: 25px; }
    .header-table td { border: none; padding: 3px 10px; }
    .header-table .label { font-weight: 600; width: 120px; }
    .check-col { width: 60px; text-align: center; }
    .init-col { width: 60px; text-align: center; }
    .checkbox { width: 18px; height: 18px; border: 2px solid #374151; display: inline-block; }
    .section-header { background: #1e40af; color: white; }
    .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 9pt; border-top: 1px solid #e5e7eb; padding-top: 15px; }
    .signature-block { margin-top: 40px; display: flex; justify-content: space-between; }
    .signature-line { width: 200px; border-top: 1px solid #374151; padding-top: 5px; text-align: center; }
    @media print { body { padding: 20px; } .checkbox { border: 2px solid black; } }
  </style>
</head>
<body>
  <h1>Surface Protection Inspection Checklist</h1>

  <table class="header-table">
    <tr><td class="label">Project:</td><td>${data.projectName}</td><td class="label">Date:</td><td>${data.date}</td></tr>
    <tr><td class="label">Customer:</td><td>${data.customerName}</td><td class="label">Rev:</td><td>${data.revision}</td></tr>
    <tr><td class="label">RFQ No:</td><td>${data.rfqNumber}</td><td class="label">Document:</td><td>QC Inspection Checklist</td></tr>
  </table>

  <h2>Pre-Application Inspection</h2>
  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Requirement</th>
        <th class="check-col">Pass</th>
        <th class="check-col">Fail</th>
        <th class="init-col">Initials</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Material Certificates</td>
        <td>Batch certificates available and verified</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Material Condition</td>
        <td>Within shelf life, properly stored</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Ambient Temperature</td>
        <td>${sp.applicationTempC || "15-35"} deg C</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Relative Humidity</td>
        <td>Max ${sp.applicationHumidityPercent || "85"}%</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Dew Point Margin</td>
        <td>Steel temp min 3 deg C above dew point</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
    </tbody>
  </table>

  <h2>Surface Preparation Inspection</h2>
  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Requirement</th>
        <th class="check-col">Pass</th>
        <th class="check-col">Fail</th>
        <th class="init-col">Initials</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Surface Cleanliness</td>
        <td>${sp.surfacePrepStandard || "ISO 8501-1 Sa 2.5"}</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Surface Profile</td>
        <td>40-75 microns (per system requirements)</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Dust Level</td>
        <td>ISO 8502-3 Rating 2 or better</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Edge Preparation</td>
        <td>Sharp edges rounded to min 2mm radius</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Weld Preparation</td>
        <td>Welds ground smooth, spatter removed</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
    </tbody>
  </table>

  ${this.renderCoatingInspectionTable(sp)}

  <h2>Final Inspection</h2>
  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Requirement</th>
        <th class="check-col">Pass</th>
        <th class="check-col">Fail</th>
        <th class="init-col">Initials</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Total DFT</td>
        <td>${sp.externalTotalDftUm || "As specified"} microns (external)</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Visual Appearance</td>
        <td>No runs, sags, or defects</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Holiday Detection</td>
        <td>No holidays detected (where applicable)</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Adhesion Test</td>
        <td>Per ISO 4624 or ASTM D3359</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
      <tr>
        <td>Documentation</td>
        <td>All records complete and signed</td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="check-col"><span class="checkbox"></span></td>
        <td class="init-col"></td>
      </tr>
    </tbody>
  </table>

  <div class="signature-block">
    <div>
      <div class="signature-line">Inspector Name / Signature</div>
    </div>
    <div>
      <div class="signature-line">Date</div>
    </div>
    <div>
      <div class="signature-line">Client Representative</div>
    </div>
  </div>

  <div class="footer">
    Generated by Annix RFQ System | ${data.date}
  </div>
</body>
</html>
    `;
  }

  generateItpHtml(data: SpDocumentData): string {
    const sp = data.surfaceProtection;

    return `
<!DOCTYPE html>
<html>
<head>
  <title>ITP - ${data.projectName}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 30px; max-width: 1000px; margin: 0 auto; font-size: 10pt; }
    h1 { color: #1a1a1a; border-bottom: 3px solid #2563eb; padding-bottom: 10px; font-size: 16pt; }
    h2 { color: #374151; margin-top: 20px; font-size: 13pt; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 9pt; }
    th, td { border: 1px solid #374151; padding: 6px 8px; text-align: left; vertical-align: top; }
    th { background-color: #1e40af; color: white; font-weight: 600; }
    .header-table { border: none; margin-bottom: 20px; }
    .header-table td { border: none; padding: 2px 8px; }
    .header-table .label { font-weight: 600; width: 100px; }
    .activity-col { width: 18%; }
    .ref-col { width: 15%; }
    .acceptance-col { width: 20%; }
    .method-col { width: 15%; }
    .frequency-col { width: 10%; }
    .signoff-col { width: 7%; text-align: center; }
    .legend { margin-top: 20px; font-size: 9pt; }
    .legend td { padding: 4px 8px; }
    .footer { margin-top: 30px; text-align: center; color: #9ca3af; font-size: 8pt; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    .section-row { background: #dbeafe; font-weight: 600; }
    @media print {
      body { padding: 15px; font-size: 9pt; }
      table { font-size: 8pt; }
      th { background: #1e40af !important; -webkit-print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  <h1>Inspection and Test Plan (ITP)</h1>
  <h2>Surface Protection Application</h2>

  <table class="header-table">
    <tr><td class="label">Project:</td><td>${data.projectName}</td><td class="label">Date:</td><td>${data.date}</td></tr>
    <tr><td class="label">Customer:</td><td>${data.customerName}</td><td class="label">Rev:</td><td>${data.revision}</td></tr>
    <tr><td class="label">RFQ No:</td><td>${data.rfqNumber}</td><td class="label">System:</td><td>${sp.externalCoatingType || "Per Specification"}</td></tr>
  </table>

  <table>
    <thead>
      <tr>
        <th class="activity-col">Activity / Test Point</th>
        <th class="ref-col">Reference Standard</th>
        <th class="acceptance-col">Acceptance Criteria</th>
        <th class="method-col">Method / Equipment</th>
        <th class="frequency-col">Frequency</th>
        <th class="signoff-col">C</th>
        <th class="signoff-col">H</th>
        <th class="signoff-col">W</th>
        <th class="signoff-col">R</th>
      </tr>
    </thead>
    <tbody>
      <tr class="section-row">
        <td colspan="9">1.0 PRE-APPLICATION</td>
      </tr>
      <tr>
        <td>1.1 Material Receipt Inspection</td>
        <td>ISO 12944-5</td>
        <td>Correct materials, valid shelf life, undamaged packaging</td>
        <td>Visual, Certificate Review</td>
        <td>Each batch</td>
        <td>H</td>
        <td>H</td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>1.2 Environmental Conditions</td>
        <td>ISO 12944-5</td>
        <td>Temp: ${sp.applicationTempC || "15-35"}C, RH: <${sp.applicationHumidityPercent || "85"}%, Steel 3C > dew point</td>
        <td>Hygrometer, Thermometer, Dew Point Calculator</td>
        <td>Continuous</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>1.3 Equipment Calibration</td>
        <td>Manufacturer specs</td>
        <td>Valid calibration certificates</td>
        <td>Certificate Review</td>
        <td>Per equipment</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>

      <tr class="section-row">
        <td colspan="9">2.0 SURFACE PREPARATION</td>
      </tr>
      <tr>
        <td>2.1 Pre-cleaning</td>
        <td>SSPC-SP1</td>
        <td>Free from oil, grease, and soluble contaminants</td>
        <td>Visual, Water Break Test</td>
        <td>100%</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>2.2 Abrasive Quality</td>
        <td>ISO 11126</td>
        <td>Clean, dry, angular abrasive, max 0.25% chloride</td>
        <td>Conductivity Test, Visual</td>
        <td>Each batch</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>2.3 Surface Cleanliness</td>
        <td>ISO 8501-1</td>
        <td>${sp.surfacePrepStandard || "Sa 2.5"}</td>
        <td>Visual Comparator</td>
        <td>100%</td>
        <td>W</td>
        <td>H</td>
        <td>W</td>
        <td>R</td>
      </tr>
      <tr>
        <td>2.4 Surface Profile</td>
        <td>ISO 8503-4</td>
        <td>40-75 microns</td>
        <td>Replica Tape / Surface Comparator</td>
        <td>Min 3 per item</td>
        <td>H</td>
        <td>H</td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>2.5 Dust Assessment</td>
        <td>ISO 8502-3</td>
        <td>Rating 2 or better</td>
        <td>Pressure-sensitive tape</td>
        <td>100%</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>2.6 Salt Contamination</td>
        <td>ISO 8502-6</td>
        <td><20 mg/m2 chloride</td>
        <td>Bresle Test</td>
        <td>Per batch</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>

      <tr class="section-row">
        <td colspan="9">3.0 COATING APPLICATION</td>
      </tr>
      <tr>
        <td>3.1 Mixing</td>
        <td>Manufacturer TDS</td>
        <td>Correct ratio, proper mixing time</td>
        <td>Visual, Mixing Records</td>
        <td>Each batch</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>3.2 Primer Application</td>
        <td>ISO 12944-5</td>
        <td>Per TDS, uniform coverage</td>
        <td>Visual</td>
        <td>100%</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>3.3 Primer WFT/DFT</td>
        <td>ISO 2808</td>
        <td>Per specification</td>
        <td>WFT Gauge / DFT Gauge</td>
        <td>Min 5 per m2</td>
        <td>H</td>
        <td>H</td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>3.4 Intermediate Coat</td>
        <td>ISO 12944-5</td>
        <td>Per TDS, uniform coverage</td>
        <td>Visual</td>
        <td>100%</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>3.5 Intermediate WFT/DFT</td>
        <td>ISO 2808</td>
        <td>Per specification</td>
        <td>WFT Gauge / DFT Gauge</td>
        <td>Min 5 per m2</td>
        <td>H</td>
        <td>H</td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>3.6 Topcoat Application</td>
        <td>ISO 12944-5</td>
        <td>Per TDS, uniform coverage</td>
        <td>Visual</td>
        <td>100%</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>3.7 Topcoat WFT/DFT</td>
        <td>ISO 2808</td>
        <td>Per specification</td>
        <td>WFT Gauge / DFT Gauge</td>
        <td>Min 5 per m2</td>
        <td>H</td>
        <td>H</td>
        <td></td>
        <td>R</td>
      </tr>

      <tr class="section-row">
        <td colspan="9">4.0 FINAL INSPECTION</td>
      </tr>
      <tr>
        <td>4.1 Total DFT</td>
        <td>ISO 2808</td>
        <td>${sp.externalTotalDftUm || "Per specification"} microns</td>
        <td>Elcometer/DFT Gauge</td>
        <td>Per ISO 19840</td>
        <td>W</td>
        <td>H</td>
        <td>W</td>
        <td>R</td>
      </tr>
      <tr>
        <td>4.2 Visual Inspection</td>
        <td>ISO 12944-5</td>
        <td>No runs, sags, holidays, or defects</td>
        <td>Visual</td>
        <td>100%</td>
        <td>W</td>
        <td>H</td>
        <td>W</td>
        <td>R</td>
      </tr>
      <tr>
        <td>4.3 Holiday Detection</td>
        <td>NACE SP0188</td>
        <td>No holidays at specified voltage</td>
        <td>Low/High voltage detector</td>
        <td>100% (where spec)</td>
        <td>W</td>
        <td>H</td>
        <td>W</td>
        <td>R</td>
      </tr>
      <tr>
        <td>4.4 Adhesion Test</td>
        <td>ISO 4624/ASTM D3359</td>
        <td>Rating 4 or better</td>
        <td>Cross-cut/Pull-off test</td>
        <td>Per batch</td>
        <td>W</td>
        <td>H</td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>4.5 Cure Verification</td>
        <td>Manufacturer TDS</td>
        <td>Full cure achieved</td>
        <td>MEK rub test (where applicable)</td>
        <td>Per batch</td>
        <td>H</td>
        <td></td>
        <td></td>
        <td>R</td>
      </tr>
      <tr>
        <td>4.6 Documentation</td>
        <td>Project Spec</td>
        <td>All records complete, signed, filed</td>
        <td>Document Review</td>
        <td>100%</td>
        <td>H</td>
        <td>H</td>
        <td></td>
        <td>R</td>
      </tr>
    </tbody>
  </table>

  <table class="legend">
    <tr>
      <th colspan="2">Legend</th>
    </tr>
    <tr>
      <td><strong>C</strong> - Contractor</td>
      <td><strong>H</strong> - Hold Point (mandatory witness)</td>
    </tr>
    <tr>
      <td><strong>W</strong> - Witness Point (24hr notice)</td>
      <td><strong>R</strong> - Review Point (records review)</td>
    </tr>
  </table>

  <div class="footer">
    Generated by Annix RFQ System | ${data.date}
  </div>
</body>
</html>
    `;
  }

  async generatePdf(html: string): Promise<Buffer> {
    let puppeteer: typeof import("puppeteer");
    try {
      puppeteer = await import("puppeteer");
    } catch (importError) {
      this.logger.error("Failed to import puppeteer", importError);
      throw new Error("PDF generation is not available");
    }

    let browser: Awaited<ReturnType<typeof puppeteer.launch>> | null = null;
    let page: Awaited<ReturnType<Awaited<ReturnType<typeof puppeteer.launch>>["newPage"]>> | null =
      null;
    try {
      browser = await puppeteer.launch({
        headless: true,
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-gpu",
        ],
      });

      page = await browser.newPage();
      await page.setContent(html, {
        waitUntil: "networkidle0",
      });

      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: {
          top: "15mm",
          bottom: "15mm",
          left: "12mm",
          right: "12mm",
        },
      });

      return Buffer.from(pdfBuffer);
    } catch (error) {
      this.logger.error("Failed to generate PDF", error);
      throw new Error("Failed to generate PDF");
    } finally {
      if (page) {
        try {
          await page.close();
        } catch {
          this.logger.warn("Page close failed");
        }
      }
      if (browser) {
        try {
          await browser.close();
        } catch {
          this.logger.warn("Browser close failed");
        }
      }
    }
  }

  calculateQuantitySummary(sp: RfqSurfaceProtection, items?: SpLineItem[]): SpQuantitySummary {
    const totalInternalAreaM2 = Number(sp.totalInternalAreaM2) || 0;
    const totalExternalAreaM2 = Number(sp.totalExternalAreaM2) || 0;
    const totalAreaM2 = totalInternalAreaM2 + totalExternalAreaM2;

    const systemDescriptions: string[] = [];
    if (sp.externalCoatingRequired && sp.externalSystemDescription) {
      systemDescriptions.push(`External: ${sp.externalSystemDescription}`);
    }
    if (sp.internalLiningRequired && sp.internalLiningDescription) {
      systemDescriptions.push(`Internal: ${sp.internalLiningDescription}`);
    }

    return {
      totalInternalAreaM2,
      totalExternalAreaM2,
      totalAreaM2,
      totalPaintLiters: Number(sp.totalPaintLiters) || 0,
      totalRubberM2: Number(sp.totalRubberM2) || 0,
      totalCeramicTiles: sp.totalCeramicTiles || 0,
      itemCount: items?.length || 0,
      systemDescriptions,
    };
  }

  private renderExternalCoatingSection(sp: RfqSurfaceProtection): string {
    if (!sp.externalCoatingRequired) {
      return `<div class="section"><h2>External Coating</h2><p>Not required for this project</p></div>`;
    }

    return `
    <div class="section">
      <h2>External Coating Specification</h2>
      <table>
        <tr>
          <th>Coating System</th>
          <td colspan="3">${sp.externalCoatingType || "Per manufacturer"}</td>
        </tr>
        <tr>
          <th>System Code</th>
          <td>${sp.externalSystemCode || "N/A"}</td>
          <th>ISO 12944</th>
          <td>${sp.iso12944Category || "N/A"} / ${sp.iso12944Durability || "N/A"}</td>
        </tr>
        <tr>
          <th>Surface Preparation</th>
          <td colspan="3">${sp.surfacePrepStandard || "Sa 2.5 per ISO 8501-1"}</td>
        </tr>
      </table>

      <h3>Coating Schedule</h3>
      <table>
        <thead>
          <tr>
            <th>Coat</th>
            <th>Product</th>
            <th>DFT (um)</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          <tr class="coat-row">
            <td>Primer</td>
            <td>Per TDS</td>
            <td>75-100</td>
            <td>Apply within 4 hours of blast</td>
          </tr>
          <tr class="coat-row">
            <td>Intermediate</td>
            <td>Per TDS</td>
            <td>100-150</td>
            <td>Within overcoat interval</td>
          </tr>
          <tr class="coat-row">
            <td>Topcoat</td>
            <td>Per TDS</td>
            <td>50-75</td>
            <td>Final finish coat</td>
          </tr>
          <tr class="total-row">
            <td colspan="2">Total System DFT</td>
            <td>${sp.externalTotalDftUm || "250-350"}</td>
            <td>Minimum specified</td>
          </tr>
        </tbody>
      </table>
    </div>
    `;
  }

  private renderInternalLiningSection(sp: RfqSurfaceProtection): string {
    if (!sp.internalLiningRequired) {
      return `<div class="section"><h2>Internal Lining</h2><p>Not required for this project</p></div>`;
    }

    const liningDetails = this.buildInternalLiningDetails(sp);

    return `
    <div class="section">
      <h2>Internal Lining Specification</h2>
      <table>
        <tr>
          <th>Lining Type</th>
          <td colspan="3">${sp.internalLiningType || "Per specification"}</td>
        </tr>
        ${liningDetails}
        <tr>
          <th>Application</th>
          <td colspan="3">${sp.applicationLocation || "Shop"}</td>
        </tr>
      </table>
    </div>
    `;
  }

  private buildInternalLiningDetails(sp: RfqSurfaceProtection): string {
    const rows: string[] = [];

    if (sp.rubberGrade) {
      rows.push(`
        <tr>
          <th>Rubber Grade</th>
          <td>${sp.rubberGrade}</td>
          <th>Hardness</th>
          <td>${sp.rubberHardnessIrhd || "60-70"} IRHD</td>
        </tr>
        <tr>
          <th>Thickness</th>
          <td colspan="3">${sp.internalLiningThicknessMm || "6"}mm</td>
        </tr>
      `);
    }

    if (sp.ceramicTileType) {
      rows.push(`
        <tr>
          <th>Ceramic Type</th>
          <td colspan="3">${sp.ceramicTileType}</td>
        </tr>
      `);
    }

    if (sp.internalLiningThicknessMm && !sp.rubberGrade) {
      rows.push(`
        <tr>
          <th>Lining Thickness</th>
          <td colspan="3">${sp.internalLiningThicknessMm}mm</td>
        </tr>
      `);
    }

    return rows.join("");
  }

  private renderSurfaceAreaSummary(sp: RfqSurfaceProtection): string {
    const hasAreas = sp.totalInternalAreaM2 || sp.totalExternalAreaM2;

    if (!hasAreas) {
      return "";
    }

    return `
    <div class="section">
      <h2>Surface Area Summary</h2>
      <table>
        <tr>
          <th>Internal Area</th>
          <td>${Number(sp.totalInternalAreaM2)?.toFixed(2) || "0.00"} m2</td>
          <th>Wastage</th>
          <td>${sp.wastagePercent || "15"}%</td>
        </tr>
        <tr>
          <th>External Area</th>
          <td>${Number(sp.totalExternalAreaM2)?.toFixed(2) || "0.00"} m2</td>
          <th>Total with Wastage</th>
          <td>${((Number(sp.totalInternalAreaM2) || 0) + (Number(sp.totalExternalAreaM2) || 0)) * (1 + (Number(sp.wastagePercent) || 15) / 100)} m2</td>
        </tr>
      </table>
    </div>
    `;
  }

  private renderExternalCoatingProcedure(sp: RfqSurfaceProtection): string {
    return `
    <h2>3. External Coating Application</h2>

    <div class="procedure-step">
      <h4>3.1 Primer Application</h4>
      <p>Product: Per TDS specification</p>
      <p>Apply first coat within 4 hours of blast cleaning</p>
      <p>Ensure complete coverage including edges and welds</p>
      <p>Minimum DFT: 75 microns</p>
    </div>

    <div class="procedure-step">
      <h4>3.2 Intermediate Coat</h4>
      <p>Apply within overcoating window per TDS</p>
      <p>Allow flash-off before additional coats</p>
      <p>Minimum DFT: 100-150 microns</p>
    </div>

    <div class="procedure-step">
      <h4>3.3 Topcoat Application</h4>
      <p>Final aesthetic and protective coat</p>
      <p>Uniform colour and gloss</p>
      <p>Minimum DFT: 50-75 microns</p>
      <p>Total System DFT: ${sp.externalTotalDftUm || "250-350"} microns</p>
    </div>
    `;
  }

  private renderInternalLiningProcedure(sp: RfqSurfaceProtection): string {
    if (sp.rubberGrade) {
      return `
      <h2>3. Internal Rubber Lining Application</h2>

      <div class="procedure-step">
        <h4>3.1 Substrate Preparation</h4>
        <p>Blast clean to Sa 2.5 minimum</p>
        <p>Apply adhesive system per manufacturer instructions</p>
        <p>Ensure pot life is not exceeded</p>
      </div>

      <div class="procedure-step">
        <h4>3.2 Rubber Application</h4>
        <p>Rubber Grade: ${sp.rubberGrade}</p>
        <p>Thickness: ${sp.internalLiningThicknessMm || "6"}mm</p>
        <p>Apply rubber sheets ensuring no air entrapment</p>
        <p>Roll out all bubbles and ensure full adhesion</p>
      </div>

      <div class="procedure-step">
        <h4>3.3 Vulcanization</h4>
        <p>Autoclave cure where specified</p>
        <p>Temperature and time per rubber grade requirements</p>
        <p>Cool down gradually to prevent thermal shock</p>
      </div>
      `;
    }

    if (sp.ceramicTileType) {
      return `
      <h2>3. Internal Ceramic Lining Application</h2>

      <div class="procedure-step">
        <h4>3.1 Substrate Preparation</h4>
        <p>Blast clean to Sa 2.5 minimum</p>
        <p>Apply primer/adhesion coat if specified</p>
      </div>

      <div class="procedure-step">
        <h4>3.2 Tile Installation</h4>
        <p>Ceramic Type: ${sp.ceramicTileType}</p>
        <p>Apply epoxy adhesive to substrate and tile back</p>
        <p>Position tiles ensuring consistent gap spacing</p>
        <p>Use temporary supports during cure</p>
      </div>

      <div class="procedure-step">
        <h4>3.3 Grouting</h4>
        <p>Allow adhesive to cure per manufacturer TDS</p>
        <p>Apply epoxy grout to all joints</p>
        <p>Ensure complete filling with no voids</p>
        <p>Clean excess grout before cure</p>
      </div>
      `;
    }

    return `
    <h2>3. Internal Lining Application</h2>

    <div class="procedure-step">
      <h4>3.1 Lining Application</h4>
      <p>Lining Type: ${sp.internalLiningType || "Per specification"}</p>
      <p>Apply per manufacturer TDS requirements</p>
      <p>Thickness: ${sp.internalLiningThicknessMm || "As specified"}mm</p>
    </div>
    `;
  }

  private renderCoatingInspectionTable(sp: RfqSurfaceProtection): string {
    if (!sp.externalCoatingRequired && !sp.internalLiningRequired) {
      return "";
    }

    return `
    <h2>Coating/Lining Application Inspection</h2>
    <table>
      <thead>
        <tr>
          <th>Item</th>
          <th>Requirement</th>
          <th class="check-col">Pass</th>
          <th class="check-col">Fail</th>
          <th class="init-col">Initials</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Mixing Ratio</td>
          <td>Per manufacturer TDS</td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="init-col"></td>
        </tr>
        <tr>
          <td>Pot Life</td>
          <td>Material used within pot life</td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="init-col"></td>
        </tr>
        <tr>
          <td>WFT During Application</td>
          <td>Within specified range</td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="init-col"></td>
        </tr>
        <tr>
          <td>Stripe Coating</td>
          <td>Edges, welds, and corners coated</td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="init-col"></td>
        </tr>
        <tr>
          <td>Overcoat Interval</td>
          <td>Within manufacturer window</td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="init-col"></td>
        </tr>
        <tr>
          <td>DFT per Coat</td>
          <td>Per specification</td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="check-col"><span class="checkbox"></span></td>
          <td class="init-col"></td>
        </tr>
      </tbody>
    </table>
    `;
  }
}
