export type {
  CorrosivityCategory,
  CuringTime,
  GenericType,
  OvercoatInterval,
  PaintProduct,
  PaintSupplier,
  ProductRole,
} from "./paintProducts";

export {
  compatiblePrimers,
  compatibleTopcoats,
  paintProducts,
  primersForEnvironment,
  productsByGenericType,
  productsByRole,
  productsBySupplier,
  productsForCorrosivity,
  productsForTemperature,
  surfaceTolerantProducts,
  topcoatsForEnvironment,
} from "./paintProducts";

export type {
  CoatingSystemRequirements,
  RecommendedCoatingSystem,
} from "./paintSystemRecommendations";

export {
  highTempSystemRecommendation,
  recommendCoatingSystem,
  recommendPrimersForCategory,
  recommendTopcoatsForPrimer,
  systemDftSummary,
} from "./paintSystemRecommendations";

export type {
  ASNZS2312Result,
  ASNZS4680Result,
  ASTMStandard,
  CathodicProtectionCompatibility,
  FireProtectionRequirement,
  FoodContactCompliance,
  ISO8501ValidationResult,
  ISO12944Part,
  ISO12944Part2Environment,
  ISO12944Part3Design,
  ISO12944Part4Surface,
  ISO12944Part5System,
  ISO12944Part6TestResult,
  ISO12944Part7Execution,
  ISO12944Part8NewWork,
  ISO12944Part9Maintenance,
  ISO12944Validation,
  PotableWaterCompliance,
  VOCLimit,
} from "./standardsValidation";

export {
  allASNZS2312Systems,
  allASNZS4680Grades,
  allASTMStandards,
  allPotableWaterStandards,
  allVOCLimits,
  astmEquivalentForTest,
  astmStandardsByCategory,
  calculateFireProtectionDft,
  checkCathodicProtectionCompatibility,
  checkFoodContactSuitability,
  checkVOCCompliance,
  findRelatedASTM,
  foodContactComplianceForRegion,
  potableWaterStandardsForRegion,
  recommendASNZS2312System,
  recommendASNZS4680Grade,
  recommendCPCompatibleCoatings,
  recommendISO8501Grade,
  recommendLowVOCAlternatives,
  validateFireProtectionSystem,
  validateGalvanizingThickness,
  validateISO8501Grade,
  validateISO12944Part1Scope,
  validateISO12944Part2,
  validateISO12944Part3,
  validateISO12944Part4,
  validateISO12944Part5,
  validateISO12944Part6Tests,
  validateISO12944Part7,
  validateISO12944Part8,
  validateISO12944Part9,
  validatePotableWaterCompliance,
  vocLimitsForRegion,
} from "./standardsValidation";
