#!/usr/bin/env node

const { execSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const readline = require("node:readline");

const configsDir = path.resolve(__dirname, "..", "annix-backend", "configs");
const configName = process.argv[2];

if (!configName) {
  console.error("\x1b[31mUsage: node scripts/setup-config.js <config-name>\x1b[0m");
  console.error("Example: node scripts/setup-config.js prod");
  console.error("         node scripts/setup-config.js staging");
  console.error("");

  if (fs.existsSync(configsDir)) {
    const existing = fs
      .readdirSync(configsDir)
      .filter((f) => f.endsWith(".env"))
      .map((f) => f.replace(".env", ""));
    if (existing.length > 0) {
      console.error(`Existing configs: ${existing.join(", ")}`);
    }
  }
  process.exit(1);
}

if (!fs.existsSync(configsDir)) {
  fs.mkdirSync(configsDir, { recursive: true });
}

const configFile = path.join(configsDir, `${configName}.env`);

function extractValue(output) {
  const lines = output
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.match(/^(Connecting|Warning|Error|info:)/i));
  return lines.length > 0 ? lines[0] : null;
}

function fetchFromFly(envVar, appName) {
  try {
    const output = execSync(`fly ssh console -a ${appName} -C "printenv ${envVar}"`, {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    return extractValue(output);
  } catch (err) {
    const output = (err.stdout || "").toString();
    if (output) {
      return extractValue(output);
    }
    return null;
  }
}

function promptUser(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function main() {
  const flyApp = process.argv[3] || "annix-app";

  console.log(`\x1b[36mFetching secrets from Fly.io app '${flyApp}'...\x1b[0m`);
  console.log("");

  const secrets = [
    "DATABASE_HOST",
    "DATABASE_PORT",
    "DATABASE_USERNAME",
    "DATABASE_PASSWORD",
    "DATABASE_NAME",
    "DATABASE_SSL",
    "JWT_SECRET",
    "DOCUMENT_ENCRYPTION_KEY",
    "AWS_S3_BUCKET",
    "GEMINI_API_KEY",
    "ANTHROPIC_API_KEY",
    "TOKEN_ENCRYPTION_KEY",
  ];

  const values = {};
  let failures = [];

  for (const secret of secrets) {
    process.stdout.write(`  Fetching ${secret}... `);
    const value = fetchFromFly(secret, flyApp);
    if (value) {
      values[secret] = value;
      const display =
        secret.includes("PASSWORD") || secret.includes("SECRET") || secret.includes("KEY")
          ? `${value.slice(0, 6)}...`
          : value;
      console.log(`\x1b[32m${display}\x1b[0m`);
    } else {
      failures = [...failures, secret];
      console.log("\x1b[33mskipped\x1b[0m");
    }
  }

  console.log("");

  if (!values.DATABASE_PASSWORD) {
    console.error(
      "\x1b[31mFailed to fetch DATABASE_PASSWORD. Make sure you are authenticated with 'fly auth login'.\x1b[0m",
    );
    process.exit(1);
  }

  const lines = [
    `# Config: ${configName} (auto-generated by setup-config.js)`,
    `# Source: fly app '${flyApp}'`,
    "# WARNING: This connects to a LIVE environment. Be careful!",
    `# Generated: ${new Date().toISOString()}`,
    "",
  ];

  const sections = {
    Database: [
      "DATABASE_HOST",
      "DATABASE_PORT",
      "DATABASE_USERNAME",
      "DATABASE_PASSWORD",
      "DATABASE_NAME",
      "DATABASE_SSL",
    ],
    Auth: ["JWT_SECRET", "TOKEN_ENCRYPTION_KEY"],
    Encryption: ["DOCUMENT_ENCRYPTION_KEY"],
    Storage: ["AWS_S3_BUCKET"],
    AI: ["GEMINI_API_KEY", "ANTHROPIC_API_KEY"],
  };

  Object.entries(sections).forEach(([sectionName, keys]) => {
    const sectionValues = keys.filter((k) => values[k]);
    if (sectionValues.length > 0) {
      lines.push(`# ${sectionName}`);
      sectionValues.forEach((k) => lines.push(`${k}=${values[k]}`));
      lines.push("");
    }
  });

  lines.push("# App (local dev overrides)");
  lines.push("FRONTEND_URL=http://localhost:3000");
  lines.push("CORS_ORIGINS=http://localhost:3000");
  lines.push("");

  fs.writeFileSync(configFile, lines.join("\n"), "utf-8");

  console.log(
    `\x1b[32mConfig '${configName}' written to annix-backend/configs/${configName}.env\x1b[0m`,
  );
  if (failures.length > 0) {
    console.log(`\x1b[33mSkipped (not set on server): ${failures.join(", ")}\x1b[0m`);
  }
  console.log("");
  console.log("To use this config:");
  console.log(`  node scripts/start-with-config.js ${configName}`);
  console.log(`  pnpm start:dev:config ${configName}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
