import type { SaMine } from "@/app/lib/api/client";

export const fallbackMines: SaMine[] = [
  {
    id: 18,
    mineName: "Amandelbult Mine",
    operatingCompany: "Anglo American Platinum",
    commodityId: 3,
    commodityName: "PGM",
    province: "Limpopo",
    district: "Waterberg",
    physicalAddress: "Thabazimbi, Limpopo",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -24.8167,
    longitude: 27.3667,
  },
  {
    id: 23,
    mineName: "Bathopele Mine",
    operatingCompany: "Anglo American Platinum",
    commodityId: 3,
    commodityName: "PGM",
    province: "North West",
    district: "Bojanala",
    physicalAddress: "Rustenburg, North West",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -25.6333,
    longitude: 27.3,
  },
  {
    id: 14,
    mineName: "Beatrix Mine",
    operatingCompany: "Sibanye-Stillwater",
    commodityId: 2,
    commodityName: "Gold",
    province: "Free State",
    district: "Lejweleputswa",
    physicalAddress: "Welkom, Free State",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -28.0,
    longitude: 26.75,
  },
  {
    id: 29,
    mineName: "Beeshoek Mine",
    operatingCompany: "Assmang",
    commodityId: 4,
    commodityName: "Iron Ore",
    province: "Northern Cape",
    district: "Siyanda",
    physicalAddress: "Postmasburg, Northern Cape",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -28.4333,
    longitude: 23.15,
  },
  {
    id: 32,
    mineName: "Black Mountain Mine",
    operatingCompany: "Vedanta Zinc",
    commodityId: 5,
    commodityName: "Copper/Base Metals",
    province: "Northern Cape",
    district: "Namakwa",
    physicalAddress: "Aggeneys, Northern Cape",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -29.2333,
    longitude: 18.8167,
  },
  {
    id: 38,
    mineName: "Cullinan Mine",
    operatingCompany: "Petra Diamonds",
    commodityId: 6,
    commodityName: "Diamonds",
    province: "Gauteng",
    district: "Tshwane",
    physicalAddress: "Cullinan, Gauteng",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -25.6833,
    longitude: 28.5167,
  },
  {
    id: 15,
    mineName: "Driefontein Mine",
    operatingCompany: "Sibanye-Stillwater",
    commodityId: 2,
    commodityName: "Gold",
    province: "Gauteng",
    district: "West Rand",
    physicalAddress: "Carletonville, Gauteng",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -26.3833,
    longitude: 27.5167,
  },
  {
    id: 37,
    mineName: "Finsch Mine",
    operatingCompany: "Petra Diamonds",
    commodityId: 6,
    commodityName: "Diamonds",
    province: "Northern Cape",
    district: "Frances Baard",
    physicalAddress: "Lime Acres, Northern Cape",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -28.3833,
    longitude: 23.45,
  },
  {
    id: 33,
    mineName: "Gamsberg Mine",
    operatingCompany: "Vedanta Zinc",
    commodityId: 5,
    commodityName: "Copper/Base Metals",
    province: "Northern Cape",
    district: "Namakwa",
    physicalAddress: "Aggeneys, Northern Cape",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -29.25,
    longitude: 18.9333,
  },
  {
    id: 3,
    mineName: "Goedehoop Colliery",
    operatingCompany: "Anglo American",
    commodityId: 1,
    commodityName: "Coal",
    province: "Mpumalanga",
    district: "Nkangala",
    physicalAddress: "Middelburg, Mpumalanga",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -25.77,
    longitude: 29.47,
  },
  {
    id: 4,
    mineName: "Greenside Colliery",
    operatingCompany: "Anglo American",
    commodityId: 1,
    commodityName: "Coal",
    province: "Mpumalanga",
    district: "Nkangala",
    physicalAddress: "Witbank, Mpumalanga",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -25.89,
    longitude: 29.16,
  },
  {
    id: 6,
    mineName: "Grootegeluk Mine",
    operatingCompany: "Exxaro",
    commodityId: 1,
    commodityName: "Coal",
    province: "Limpopo",
    district: "Waterberg",
    physicalAddress: "Lephalale, Limpopo",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -23.65,
    longitude: 27.7,
  },
  {
    id: 20,
    mineName: "Impala Rustenburg",
    operatingCompany: "Impala Platinum",
    commodityId: 3,
    commodityName: "PGM",
    province: "North West",
    district: "Bojanala",
    physicalAddress: "Rustenburg, North West",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -25.6667,
    longitude: 27.25,
  },
  {
    id: 1,
    mineName: "Isibonelo Colliery",
    operatingCompany: "Anglo American",
    commodityId: 1,
    commodityName: "Coal",
    province: "Mpumalanga",
    district: "Nkangala",
    physicalAddress: "Ogies, Mpumalanga",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -26.0167,
    longitude: 29.05,
  },
  {
    id: 30,
    mineName: "Khumani Mine",
    operatingCompany: "Assmang",
    commodityId: 4,
    commodityName: "Iron Ore",
    province: "Northern Cape",
    district: "John Taolo Gaetsewe",
    physicalAddress: "Kathu, Northern Cape",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -27.2167,
    longitude: 22.95,
  },
  {
    id: 2,
    mineName: "Khwezela Colliery",
    operatingCompany: "Anglo American",
    commodityId: 1,
    commodityName: "Coal",
    province: "Mpumalanga",
    district: "Nkangala",
    physicalAddress: "Emalahleni, Mpumalanga",
    mineType: "Both",
    operationalStatus: "Active",
    latitude: -25.87,
    longitude: 29.21,
  },
  {
    id: 16,
    mineName: "Kloof Mine",
    operatingCompany: "Sibanye-Stillwater",
    commodityId: 2,
    commodityName: "Gold",
    province: "Gauteng",
    district: "West Rand",
    physicalAddress: "Westonaria, Gauteng",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -26.4,
    longitude: 27.5833,
  },
  {
    id: 39,
    mineName: "Koffiefontein Mine",
    operatingCompany: "Petra Diamonds",
    commodityId: 6,
    commodityName: "Diamonds",
    province: "Free State",
    district: "Xhariep",
    physicalAddress: "Koffiefontein, Free State",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -29.4167,
    longitude: 25.0,
  },
  {
    id: 27,
    mineName: "Kolomela Mine",
    operatingCompany: "Kumba Iron Ore",
    commodityId: 4,
    commodityName: "Iron Ore",
    province: "Northern Cape",
    district: "Siyanda",
    physicalAddress: "Postmasburg, Northern Cape",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -28.3333,
    longitude: 23.0833,
  },
  {
    id: 24,
    mineName: "Kroondal Mine",
    operatingCompany: "Sibanye-Stillwater",
    commodityId: 3,
    commodityName: "PGM",
    province: "North West",
    district: "Bojanala",
    physicalAddress: "Rustenburg, North West",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -25.65,
    longitude: 27.3167,
  },
  {
    id: 12,
    mineName: "Kusasalethu Mine",
    operatingCompany: "Harmony Gold",
    commodityId: 2,
    commodityName: "Gold",
    province: "Gauteng",
    district: "West Rand",
    physicalAddress: "Carletonville, Gauteng",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -26.3667,
    longitude: 27.3833,
  },
  {
    id: 5,
    mineName: "Mafube Colliery",
    operatingCompany: "Exxaro",
    commodityId: 1,
    commodityName: "Coal",
    province: "Mpumalanga",
    district: "Nkangala",
    physicalAddress: "Belfast, Mpumalanga",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -25.68,
    longitude: 30.04,
  },
  {
    id: 25,
    mineName: "Marikana Mine",
    operatingCompany: "Sibanye-Stillwater",
    commodityId: 3,
    commodityName: "PGM",
    province: "North West",
    district: "Bojanala",
    physicalAddress: "Marikana, North West",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -25.7,
    longitude: 27.4833,
  },
  {
    id: 21,
    mineName: "Marula Mine",
    operatingCompany: "Impala Platinum",
    commodityId: 3,
    commodityName: "PGM",
    province: "Limpopo",
    district: "Sekhukhune",
    physicalAddress: "Burgersfort, Limpopo",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -24.5,
    longitude: 30.15,
  },
  {
    id: 7,
    mineName: "Matla Colliery",
    operatingCompany: "Eskom",
    commodityId: 1,
    commodityName: "Coal",
    province: "Mpumalanga",
    district: "Nkangala",
    physicalAddress: "Kriel, Mpumalanga",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -26.25,
    longitude: 29.25,
  },
  {
    id: 11,
    mineName: "Moab Khotsong Mine",
    operatingCompany: "Harmony Gold",
    commodityId: 2,
    commodityName: "Gold",
    province: "North West",
    district: "Dr Kenneth Kaunda",
    physicalAddress: "Orkney, North West",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -26.9833,
    longitude: 26.6667,
  },
  {
    id: 17,
    mineName: "Mogalakwena Mine",
    operatingCompany: "Anglo American Platinum",
    commodityId: 3,
    commodityName: "PGM",
    province: "Limpopo",
    district: "Waterberg",
    physicalAddress: "Mokopane, Limpopo",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -23.9333,
    longitude: 28.7667,
  },
  {
    id: 10,
    mineName: "Mponeng Mine",
    operatingCompany: "Harmony Gold",
    commodityId: 2,
    commodityName: "Gold",
    province: "Gauteng",
    district: "West Rand",
    physicalAddress: "Carletonville, Gauteng",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -26.4,
    longitude: 27.3833,
  },
  {
    id: 8,
    mineName: "New Denmark Colliery",
    operatingCompany: "Eskom",
    commodityId: 1,
    commodityName: "Coal",
    province: "Mpumalanga",
    district: "Gert Sibande",
    physicalAddress: "Standerton, Mpumalanga",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -26.93,
    longitude: 29.24,
  },
  {
    id: 31,
    mineName: "Palabora Mining Company",
    operatingCompany: "Palabora Mining Company",
    commodityId: 5,
    commodityName: "Copper/Base Metals",
    province: "Limpopo",
    district: "Mopani",
    physicalAddress: "Phalaborwa, Limpopo",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -23.9667,
    longitude: 31.1333,
  },
  {
    id: 34,
    mineName: "Prieska Zinc-Copper",
    operatingCompany: "Orion Minerals",
    commodityId: 5,
    commodityName: "Copper/Base Metals",
    province: "Northern Cape",
    district: "Siyanda",
    physicalAddress: "Prieska, Northern Cape",
    mineType: "Underground",
    operationalStatus: "Care and Maintenance",
    latitude: -29.6667,
    longitude: 22.75,
  },
  {
    id: 26,
    mineName: "Sishen Mine",
    operatingCompany: "Kumba Iron Ore",
    commodityId: 4,
    commodityName: "Iron Ore",
    province: "Northern Cape",
    district: "John Taolo Gaetsewe",
    physicalAddress: "Kathu, Northern Cape",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -27.2,
    longitude: 23.0,
  },
  {
    id: 9,
    mineName: "South Deep Mine",
    operatingCompany: "Gold Fields",
    commodityId: 2,
    commodityName: "Gold",
    province: "Gauteng",
    district: "West Rand",
    physicalAddress: "Westonaria, Gauteng",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -26.4167,
    longitude: 27.6667,
  },
  {
    id: 13,
    mineName: "Target Mine",
    operatingCompany: "Harmony Gold",
    commodityId: 2,
    commodityName: "Gold",
    province: "Free State",
    district: "Lejweleputswa",
    physicalAddress: "Allanridge, Free State",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -27.7667,
    longitude: 26.6333,
  },
  {
    id: 28,
    mineName: "Thabazimbi Mine",
    operatingCompany: "Kumba Iron Ore",
    commodityId: 4,
    commodityName: "Iron Ore",
    province: "Limpopo",
    district: "Waterberg",
    physicalAddress: "Thabazimbi, Limpopo",
    mineType: "Both",
    operationalStatus: "Care and Maintenance",
    latitude: -24.5833,
    longitude: 27.4,
  },
  {
    id: 22,
    mineName: "Two Rivers Mine",
    operatingCompany: "Impala Platinum",
    commodityId: 3,
    commodityName: "PGM",
    province: "Limpopo",
    district: "Sekhukhune",
    physicalAddress: "Steelpoort, Limpopo",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -24.6833,
    longitude: 30.1,
  },
  {
    id: 19,
    mineName: "Unki Mine",
    operatingCompany: "Anglo American Platinum",
    commodityId: 3,
    commodityName: "PGM",
    province: "Limpopo",
    district: "Capricorn",
    physicalAddress: "Polokwane, Limpopo",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -23.9,
    longitude: 29.45,
  },
  {
    id: 35,
    mineName: "Venetia Mine",
    operatingCompany: "De Beers",
    commodityId: 6,
    commodityName: "Diamonds",
    province: "Limpopo",
    district: "Vhembe",
    physicalAddress: "Musina, Limpopo",
    mineType: "Underground",
    operationalStatus: "Active",
    latitude: -22.45,
    longitude: 29.3167,
  },
  {
    id: 36,
    mineName: "Voorspoed Mine",
    operatingCompany: "De Beers",
    commodityId: 6,
    commodityName: "Diamonds",
    province: "Free State",
    district: "Lejweleputswa",
    physicalAddress: "Kroonstad, Free State",
    mineType: "Open Cast",
    operationalStatus: "Active",
    latitude: -27.7667,
    longitude: 27.2333,
  },
  {
    id: 40,
    mineName: "Williamson Mine",
    operatingCompany: "Petra Diamonds",
    commodityId: 6,
    commodityName: "Diamonds",
    province: "Free State",
    district: "Xhariep",
    physicalAddress: "Jagersfontein, Free State",
    mineType: "Open Cast",
    operationalStatus: "Care and Maintenance",
    latitude: -29.7667,
    longitude: 25.4333,
  },
];

export const fallbackSlurryProfiles: Record<string, any> = {
  Coal: {
    phMin: 6.5,
    phMax: 8.5,
    typicalSgMin: 1.1,
    typicalSgMax: 1.35,
    solidsConcentrationMin: 20,
    solidsConcentrationMax: 45,
    tempMin: 15,
    tempMax: 45,
    abrasionRisk: "Medium",
    corrosionRisk: "Low",
    primaryFailureMode: "Abrasion",
  },
  Gold: {
    phMin: 10.0,
    phMax: 11.5,
    typicalSgMin: 1.3,
    typicalSgMax: 1.5,
    solidsConcentrationMin: 40,
    solidsConcentrationMax: 55,
    tempMin: 20,
    tempMax: 60,
    abrasionRisk: "Very High",
    corrosionRisk: "High",
    primaryFailureMode: "Abrasion",
  },
  PGM: {
    phMin: 8.0,
    phMax: 10.0,
    typicalSgMin: 1.25,
    typicalSgMax: 1.45,
    solidsConcentrationMin: 35,
    solidsConcentrationMax: 50,
    tempMin: 20,
    tempMax: 55,
    abrasionRisk: "Very High",
    corrosionRisk: "Medium",
    primaryFailureMode: "Abrasion",
  },
  "Iron Ore": {
    phMin: 6.5,
    phMax: 8.0,
    typicalSgMin: 1.5,
    typicalSgMax: 2.0,
    solidsConcentrationMin: 50,
    solidsConcentrationMax: 70,
    tempMin: 15,
    tempMax: 40,
    abrasionRisk: "Very High",
    corrosionRisk: "Low",
    primaryFailureMode: "Abrasion",
  },
  "Copper/Base Metals": {
    phMin: 1.5,
    phMax: 4.0,
    typicalSgMin: 1.2,
    typicalSgMax: 1.4,
    solidsConcentrationMin: 25,
    solidsConcentrationMax: 45,
    tempMin: 25,
    tempMax: 65,
    abrasionRisk: "High",
    corrosionRisk: "Very High",
    primaryFailureMode: "Corrosion",
  },
  Diamonds: {
    phMin: 6.5,
    phMax: 8.0,
    typicalSgMin: 1.4,
    typicalSgMax: 1.8,
    solidsConcentrationMin: 30,
    solidsConcentrationMax: 50,
    tempMin: 15,
    tempMax: 35,
    abrasionRisk: "Medium",
    corrosionRisk: "Low",
    primaryFailureMode: "Abrasion",
  },
};

export const fallbackEnvironmentalByProvince: Record<string, any> = {
  Mpumalanga: {
    tempMin: 8,
    tempMax: 28,
    tempMean: 18,
    humidityMin: 45,
    humidityMax: 85,
    humidityMean: 65,
    annualRainfall: "500-1000",
    ecpMarineInfluence: "None",
    ecpIso12944Category: "C3",
    ecpIndustrialPollution: "Moderate",
    soilType: "Ferralsols",
    soilTexture: "Clay Loam",
    soilMoisture: "25%",
    soilMoistureClass: "Moderate",
    soilDrainage: "Moderate",
    distanceToCoastFormatted: "350 km",
    detailedMarineInfluence: "Low / Non-Marine",
    floodRisk: "Moderate",
    uvExposure: "High",
    windSpeed: 3.5,
    airSaltContent: { level: "Very Low", isoCategory: "S0" },
    timeOfWetness: { level: "Medium", isoCategory: "T3" },
  },
  Limpopo: {
    tempMin: 10,
    tempMax: 32,
    tempMean: 22,
    humidityMin: 35,
    humidityMax: 75,
    humidityMean: 55,
    annualRainfall: "250-500",
    ecpMarineInfluence: "None",
    ecpIso12944Category: "C2",
    ecpIndustrialPollution: "Low",
    soilType: "Lixisols",
    soilTexture: "Sandy Clay Loam",
    soilMoisture: "18%",
    soilMoistureClass: "Low",
    soilDrainage: "Well",
    distanceToCoastFormatted: "400 km",
    detailedMarineInfluence: "Low / Non-Marine",
    floodRisk: "Low",
    uvExposure: "Very High",
    windSpeed: 2.8,
    airSaltContent: { level: "Very Low", isoCategory: "S0" },
    timeOfWetness: { level: "Low", isoCategory: "T2" },
  },
  Gauteng: {
    tempMin: 5,
    tempMax: 28,
    tempMean: 16,
    humidityMin: 40,
    humidityMax: 80,
    humidityMean: 60,
    annualRainfall: "500-1000",
    ecpMarineInfluence: "None",
    ecpIso12944Category: "C3",
    ecpIndustrialPollution: "High",
    soilType: "Acrisols",
    soilTexture: "Clay Loam",
    soilMoisture: "22%",
    soilMoistureClass: "Moderate",
    soilDrainage: "Moderate",
    distanceToCoastFormatted: "500 km",
    detailedMarineInfluence: "Low / Non-Marine",
    floodRisk: "Moderate",
    uvExposure: "High",
    windSpeed: 4.2,
    airSaltContent: { level: "Very Low", isoCategory: "S0" },
    timeOfWetness: { level: "Medium", isoCategory: "T3" },
  },
  "North West": {
    tempMin: 3,
    tempMax: 32,
    tempMean: 18,
    humidityMin: 30,
    humidityMax: 70,
    humidityMean: 50,
    annualRainfall: "250-500",
    ecpMarineInfluence: "None",
    ecpIso12944Category: "C2",
    ecpIndustrialPollution: "Moderate",
    soilType: "Luvisols",
    soilTexture: "Sandy Loam",
    soilMoisture: "15%",
    soilMoistureClass: "Low",
    soilDrainage: "Well",
    distanceToCoastFormatted: "450 km",
    detailedMarineInfluence: "Low / Non-Marine",
    floodRisk: "Low",
    uvExposure: "High",
    windSpeed: 3.8,
    airSaltContent: { level: "Very Low", isoCategory: "S0" },
    timeOfWetness: { level: "Low", isoCategory: "T2" },
  },
  "Northern Cape": {
    tempMin: 2,
    tempMax: 35,
    tempMean: 19,
    humidityMin: 20,
    humidityMax: 60,
    humidityMean: 40,
    annualRainfall: "<250",
    ecpMarineInfluence: "None",
    ecpIso12944Category: "C2",
    ecpIndustrialPollution: "Low",
    soilType: "Calcisols",
    soilTexture: "Sandy Loam",
    soilMoisture: "10%",
    soilMoistureClass: "Low",
    soilDrainage: "Well",
    distanceToCoastFormatted: "300 km",
    detailedMarineInfluence: "Low / Non-Marine",
    floodRisk: "None",
    uvExposure: "Very High",
    windSpeed: 4.5,
    airSaltContent: { level: "Very Low", isoCategory: "S0" },
    timeOfWetness: { level: "Very Low", isoCategory: "T1" },
  },
  "Free State": {
    tempMin: 0,
    tempMax: 30,
    tempMean: 15,
    humidityMin: 35,
    humidityMax: 75,
    humidityMean: 55,
    annualRainfall: "500-1000",
    ecpMarineInfluence: "None",
    ecpIso12944Category: "C2",
    ecpIndustrialPollution: "Low",
    soilType: "Vertisols",
    soilTexture: "Clay",
    soilMoisture: "20%",
    soilMoistureClass: "Moderate",
    soilDrainage: "Moderate",
    distanceToCoastFormatted: "400 km",
    detailedMarineInfluence: "Low / Non-Marine",
    floodRisk: "Moderate",
    uvExposure: "High",
    windSpeed: 4.0,
    airSaltContent: { level: "Very Low", isoCategory: "S0" },
    timeOfWetness: { level: "Medium", isoCategory: "T3" },
  },
  "KwaZulu-Natal": {
    tempMin: 12,
    tempMax: 28,
    tempMean: 20,
    humidityMin: 60,
    humidityMax: 90,
    humidityMean: 75,
    annualRainfall: "1000-2000",
    ecpMarineInfluence: "Coastal",
    ecpIso12944Category: "C4",
    ecpIndustrialPollution: "Moderate",
    soilType: "Nitisols",
    soilTexture: "Clay",
    soilMoisture: "35%",
    soilMoistureClass: "High",
    soilDrainage: "Moderate",
    distanceToCoastFormatted: "50 km",
    detailedMarineInfluence: "Moderate Marine",
    floodRisk: "High",
    uvExposure: "High",
    windSpeed: 3.2,
    airSaltContent: { level: "Medium", isoCategory: "S2" },
    timeOfWetness: { level: "High", isoCategory: "T4" },
  },
  "Eastern Cape": {
    tempMin: 8,
    tempMax: 26,
    tempMean: 17,
    humidityMin: 55,
    humidityMax: 85,
    humidityMean: 70,
    annualRainfall: "500-1000",
    ecpMarineInfluence: "Coastal",
    ecpIso12944Category: "C3",
    ecpIndustrialPollution: "Low",
    soilType: "Cambisols",
    soilTexture: "Loam",
    soilMoisture: "28%",
    soilMoistureClass: "Moderate",
    soilDrainage: "Well",
    distanceToCoastFormatted: "100 km",
    detailedMarineInfluence: "Low / Non-Marine",
    floodRisk: "Moderate",
    uvExposure: "High",
    windSpeed: 4.8,
    airSaltContent: { level: "Low", isoCategory: "S1" },
    timeOfWetness: { level: "Medium", isoCategory: "T3" },
  },
  "Western Cape": {
    tempMin: 7,
    tempMax: 26,
    tempMean: 16,
    humidityMin: 50,
    humidityMax: 85,
    humidityMean: 68,
    annualRainfall: "500-1000",
    ecpMarineInfluence: "Coastal",
    ecpIso12944Category: "C4",
    ecpIndustrialPollution: "Low",
    soilType: "Arenosols",
    soilTexture: "Sandy Loam",
    soilMoisture: "18%",
    soilMoistureClass: "Low",
    soilDrainage: "Well",
    distanceToCoastFormatted: "30 km",
    detailedMarineInfluence: "High Marine",
    floodRisk: "Moderate",
    uvExposure: "High",
    windSpeed: 5.2,
    airSaltContent: { level: "High", isoCategory: "S3" },
    timeOfWetness: { level: "Medium", isoCategory: "T3" },
  },
};

export const fallbackEnvironmentalData = (province: string) => {
  const rawProvince = fallbackEnvironmentalByProvince[province];
  return rawProvince || fallbackEnvironmentalByProvince["Gauteng"];
};

export const FALLBACK_ENVIRONMENTAL_AUTO_FILLED_FIELDS = [
  "tempMin",
  "tempMax",
  "tempMean",
  "humidityMin",
  "humidityMax",
  "humidityMean",
  "annualRainfall",
  "ecpMarineInfluence",
  "ecpIso12944Category",
  "ecpIndustrialPollution",
  "soilType",
  "soilTexture",
  "soilMoisture",
  "soilMoistureClass",
  "soilDrainage",
  "distanceToCoast",
  "distanceToCoastFormatted",
  "detailedMarineInfluence",
  "uvExposure",
  "windSpeed",
  "floodRisk",
  "airSaltContent",
  "timeOfWetness",
] as const;

export const buildFallbackEnvironmentalSpecs = (fallbackMine: SaMine, existingSpecs: any): any => {
  const slurryProfile = fallbackMine.commodityName
    ? fallbackSlurryProfiles[fallbackMine.commodityName]
    : null;
  const rawProvince = fallbackMine.province;
  const province = rawProvince || "Gauteng";
  const envData = fallbackEnvironmentalData(province);
  const liningRec = slurryProfile
    ? fallbackLiningRecommendation(slurryProfile.abrasionRisk, slurryProfile.corrosionRisk)
    : null;

  const specs: any = {
    ...existingSpecs,
    mineSelected: fallbackMine.mineName,
    mineCommodity: fallbackMine.commodityName,
    tempMin: envData.tempMin,
    tempMax: envData.tempMax,
    tempMean: envData.tempMean,
    humidityMin: envData.humidityMin,
    humidityMax: envData.humidityMax,
    humidityMean: envData.humidityMean,
    annualRainfall: envData.annualRainfall,
    ecpMarineInfluence: envData.ecpMarineInfluence,
    ecpIso12944Category: envData.ecpIso12944Category,
    ecpIndustrialPollution: envData.ecpIndustrialPollution,
    soilType: envData.soilType,
    soilTexture: envData.soilTexture,
    soilMoisture: envData.soilMoisture,
    soilMoistureClass: envData.soilMoistureClass,
    soilDrainage: envData.soilDrainage,
    distanceToCoastFormatted: envData.distanceToCoastFormatted,
    detailedMarineInfluence: envData.detailedMarineInfluence,
    floodRisk: envData.floodRisk,
    uvExposure: envData.uvExposure,
    windSpeed: envData.windSpeed,
    airSaltContent: envData.airSaltContent,
    timeOfWetness: envData.timeOfWetness,
  };

  if (slurryProfile) {
    specs.slurryPHMin = slurryProfile.phMin;
    specs.slurryPHMax = slurryProfile.phMax;
    specs.slurrySGMin = slurryProfile.typicalSgMin;
    specs.slurrySGMax = slurryProfile.typicalSgMax;
    specs.slurrySolidsMin = slurryProfile.solidsConcentrationMin;
    specs.slurrySolidsMax = slurryProfile.solidsConcentrationMax;
    specs.slurryTempMin = slurryProfile.tempMin;
    specs.slurryTempMax = slurryProfile.tempMax;
    specs.abrasionRisk = slurryProfile.abrasionRisk;
    specs.corrosionRisk = slurryProfile.corrosionRisk;
    specs.primaryFailureMode = slurryProfile.primaryFailureMode;
  }

  if (liningRec) {
    specs.recommendedLining = liningRec.recommendedLining;
    specs.recommendedCoating = liningRec.recommendedCoating;
  }

  return specs;
};

export const fallbackLiningRecommendation = (abrasionRisk: string, corrosionRisk: string) => {
  if (abrasionRisk === "Very High" && corrosionRisk === "Low")
    return { recommendedLining: "Ceramic Tile (95% Al2O3)", recommendedCoating: "None" };
  if (abrasionRisk === "Very High" && corrosionRisk === "Medium")
    return {
      recommendedLining: "Ceramic + Rubber Composite",
      recommendedCoating: "Rubber Backing",
    };
  if (abrasionRisk === "High" && corrosionRisk === "Very High")
    return {
      recommendedLining: "Rubber + Ceramic Composite",
      recommendedCoating: "Rubber Backed Ceramic",
    };
  if (corrosionRisk === "Very High")
    return {
      recommendedLining: "HDPE/UHMWPE Lining",
      recommendedCoating: "N/A - Self Protecting",
    };
  if (abrasionRisk === "High")
    return { recommendedLining: "Ceramic Tile Lining", recommendedCoating: "None" };
  if (abrasionRisk === "Medium")
    return { recommendedLining: "Rubber Lining (Hard)", recommendedCoating: "Epoxy Coating" };
  return { recommendedLining: "Standard Steel", recommendedCoating: "Epoxy Paint" };
};
