export type {
  MarketingAbout,
  MarketingAboutValue,
  MarketingCta,
  MarketingCtaBand,
  MarketingEcosystem,
  MarketingFooter,
  MarketingFooterColumn,
  MarketingGlobalPresence,
  MarketingHero,
  MarketingHighlight,
  MarketingIndustries,
  MarketingIndustry,
  MarketingLabs,
  MarketingLabsItem,
  MarketingPartner,
  MarketingPartners,
  MarketingPresenceItem,
  MarketingProduct,
  MarketingProductFeature,
  MarketingProductPage,
  MarketingProductRoi,
  MarketingResource,
  MarketingResourceCategory,
  MarketingResources,
  MarketingSite,
  MarketingSiteContent,
  MarketingSiteStatus,
  MarketingSocialLink,
} from "./content";
export { RESOURCE_CATEGORIES } from "./content";
export { defaultMarketingContent } from "./defaults";
