export type {
  MarketingAbout,
  MarketingAboutValue,
  MarketingCta,
  MarketingCtaBand,
  MarketingEcosystem,
  MarketingFooter,
  MarketingFooterColumn,
  MarketingGlobalPresence,
  MarketingHero,
  MarketingHighlight,
  MarketingIndustries,
  MarketingIndustry,
  MarketingLabs,
  MarketingLabsItem,
  MarketingLegal,
  MarketingLegalDoc,
  MarketingPartner,
  MarketingPartners,
  MarketingPresenceItem,
  MarketingProduct,
  MarketingProductFeature,
  MarketingProductPage,
  MarketingProductRoi,
  MarketingResource,
  MarketingResourceCategory,
  MarketingResources,
  MarketingSite,
  MarketingSiteContent,
  MarketingSiteStatus,
  MarketingSocialLink,
} from "./content";
export { RESOURCE_CATEGORIES } from "./content";
export { defaultMarketingContent } from "./defaults";
export type { MarketingLocale, MarketingLocaleMeta } from "./locales";
export {
  DEFAULT_MARKETING_LOCALE,
  isMarketingLocale,
  MARKETING_LOCALE_META,
  MARKETING_LOCALES,
  marketingLocaleMeta,
  normaliseMarketingLocale,
} from "./locales";
