export type {
  AdhesiveConditions,
  AdhesiveRecommendation,
  CeramicLiningRequirements,
  CompositeSystemConfig,
  CompositeSystemRecommendation,
  EquipmentGeometryType,
  ImpactZoneDefinition,
  ImpactZoneRecommendation,
  RecommendedCeramicLining,
  ThermalCyclingConditions,
  ThermalCyclingResult,
  TileLayoutGeometry,
  TileLayoutResult,
} from "./ceramicLiningRecommendations";
export {
  allCeramicProducts,
  buildCompositeSystem,
  calculateTileLayout,
  ceramicProductById,
  checkThermalCycling,
  compareCeramicMaterials,
  identifyImpactZones,
  recommendCeramicLining,
  recommendForChutes,
  recommendForCyclones,
  recommendForHighTemperature,
  recommendForImpactZones,
  recommendForSlidingAbrasion,
  selectCeramicAdhesive,
} from "./ceramicLiningRecommendations";
export type {
  ApplicationType,
  CeramicMaterial,
  CeramicProduct,
  CeramicSupplier,
  TileShape,
} from "./ceramicProducts";
export {
  bestCeramicForImpactZones,
  bestCeramicForSlidingAbrasion,
  ceramicProducts,
  ceramicProductsByAluminaContent,
  ceramicProductsByMaterial,
  ceramicProductsBySupplier,
  ceramicProductsByWearRating,
  ceramicProductsForApplication,
  ceramicProductsForTemperature,
  highImpactCeramicProducts,
} from "./ceramicProducts";
