// Comprehensive South African geography table used to resolve a free-text job
// location to its province. Each province lists its districts/metros and a broad
// set of cities, towns and major suburbs (every metro + district municipality,
// every local-municipality seat, plus notable additional towns/suburbs). A
// location "belongs" to a province if it names the province, any of its districts,
// or any of its cities/towns — so "Benoni, Ekurhuleni" correctly resolves to
// Gauteng even though the word "Gauteng" never appears.
//
// Source: SA municipal demarcation (8 metropolitan + 44 district municipalities,
// ~205 local municipalities). Kept backend-side so it hot-reloads with the app.

export interface SaProvinceLocations {
  province: string;
  districts: string[];
  cities: string[];
}

export const SA_LOCATIONS: SaProvinceLocations[] = [
  {
    province: "Gauteng",
    districts: ["Johannesburg", "Tshwane", "Ekurhuleni", "Sedibeng", "West Rand"],
    cities: [
      "Johannesburg",
      "Pretoria",
      "Sandton",
      "Midrand",
      "Centurion",
      "Rosebank",
      "Bryanston",
      "Randburg",
      "Roodepoort",
      "Fourways",
      "Kempton Park",
      "Edenvale",
      "Bedfordview",
      "Germiston",
      "Alberton",
      "Boksburg",
      "Benoni",
      "Springs",
      "Brakpan",
      "Nigel",
      "Menlyn",
      "Hatfield",
      "Brooklyn",
      "Irene",
      "Montana",
      "Silverton",
      "Arcadia",
      "Lynnwood",
      "Soweto",
      "Tembisa",
      "Mamelodi",
      "Soshanguve",
      "Atteridgeville",
      "Vanderbijlpark",
      "Vereeniging",
      "Sebokeng",
      "Evaton",
      "Sharpeville",
      "Heidelberg",
      "Meyerton",
      "Krugersdorp",
      "Randfontein",
      "Carletonville",
      "Westonaria",
      "Magaliesburg",
      "Cullinan",
      "Bronkhorstspruit",
      "Emfuleni",
      "Mogale City",
      "Midvaal",
      "Lenasia",
      "Alexandra",
      "Vosloorus",
      "Katlehong",
      "Daveyton",
      "Kagiso",
      "Cosmo City",
      "Fochville",
    ],
  },
  {
    province: "Western Cape",
    districts: [
      "Cape Town",
      "Cape Winelands",
      "Central Karoo",
      "Garden Route",
      "Overberg",
      "West Coast",
    ],
    cities: [
      "Cape Town",
      "Bellville",
      "Durbanville",
      "Goodwood",
      "Parow",
      "Milnerton",
      "Table View",
      "Century City",
      "Constantia",
      "Claremont",
      "Wynberg",
      "Khayelitsha",
      "Mitchells Plain",
      "Somerset West",
      "Strand",
      "Gordon's Bay",
      "Stellenbosch",
      "Franschhoek",
      "Paarl",
      "Wellington",
      "Worcester",
      "Robertson",
      "Ceres",
      "Ashton",
      "Montagu",
      "Tulbagh",
      "George",
      "Knysna",
      "Mossel Bay",
      "Oudtshoorn",
      "Plettenberg Bay",
      "Sedgefield",
      "Wilderness",
      "Hermanus",
      "Gansbaai",
      "Bredasdorp",
      "Caledon",
      "Grabouw",
      "Swellendam",
      "Saldanha",
      "Vredenburg",
      "Langebaan",
      "Hopefield",
      "Malmesbury",
      "Piketberg",
      "Vredendal",
      "Clanwilliam",
      "Citrusdal",
      "Lambert's Bay",
      "Beaufort West",
      "Laingsburg",
      "Prince Albert",
      "Riversdale",
      "Ladismith",
      "Witzenberg",
      "Bergrivier",
      "Riebeek-Kasteel",
      "Kuilsrivier",
    ],
  },
  {
    province: "Eastern Cape",
    districts: [
      "Buffalo City",
      "Nelson Mandela Bay",
      "Alfred Nzo",
      "Amathole",
      "Chris Hani",
      "Joe Gqabi",
      "OR Tambo",
      "Sarah Baartman",
    ],
    cities: [
      "East London",
      "Gqeberha",
      "Port Elizabeth",
      "Uitenhage",
      "Kariega",
      "Despatch",
      "King William's Town",
      "Bhisho",
      "Mthatha",
      "Queenstown",
      "Komani",
      "Graaff-Reinet",
      "Cradock",
      "Grahamstown",
      "Makhanda",
      "Jeffreys Bay",
      "Humansdorp",
      "St Francis Bay",
      "Aliwal North",
      "Butterworth",
      "Gcuwa",
      "Stutterheim",
      "Somerset East",
      "Ngcobo",
      "Lady Frere",
      "Flagstaff",
      "Cofimvaba",
      "Kareedouw",
      "Qumbu",
      "Matatiele",
      "Dutywa",
      "Peddie",
      "Libode",
      "Port St Johns",
      "Alice",
      "Fort Beaufort",
      "Cala",
      "Port Alfred",
      "Kenton-on-Sea",
      "Adelaide",
      "Bedford",
      "Tarkastad",
      "Sterkstroom",
      "Molteno",
      "Indwe",
      "Elliot",
      "Maclear",
      "Mount Fletcher",
      "Mount Frere",
      "Bizana",
      "Lusikisiki",
      "Tsolo",
      "Cradock",
      "Willowmore",
      "Jansenville",
      "Steytlerville",
      "Hankey",
      "Patensie",
    ],
  },
  {
    province: "Free State",
    districts: ["Mangaung", "Fezile Dabi", "Lejweleputswa", "Thabo Mofutsanyana", "Xhariep"],
    cities: [
      "Bloemfontein",
      "Botshabelo",
      "Thaba Nchu",
      "Welkom",
      "Virginia",
      "Odendaalsrus",
      "Allanridge",
      "Ventersburg",
      "Hennenman",
      "Sasolburg",
      "Deneysville",
      "Oranjeville",
      "Kroonstad",
      "Viljoenskroon",
      "Parys",
      "Vredefort",
      "Heilbron",
      "Edenville",
      "Bethlehem",
      "Clarens",
      "Phuthaditjhaba",
      "Harrismith",
      "Kestell",
      "Reitz",
      "Vrede",
      "Memel",
      "Warden",
      "Tweeling",
      "Cornelia",
      "Frankfort",
      "Villiers",
      "Trompsburg",
      "Koffiefontein",
      "Theunissen",
      "Ladybrand",
      "Ficksburg",
      "Senekal",
      "Clocolan",
      "Marquard",
      "Winburg",
      "Brandfort",
      "Bothaville",
      "Hoopstad",
      "Bultfontein",
      "Dewetsdorp",
      "Wepener",
      "Zastron",
      "Smithfield",
      "Rouxville",
      "Jagersfontein",
      "Fauresmith",
      "Petrusburg",
      "Jacobsdal",
      "Boshof",
      "Hertzogville",
      "Reddersburg",
      "Edenburg",
      "Excelsior",
      "Tweespruit",
      "Hobhouse",
    ],
  },
  {
    province: "KwaZulu-Natal",
    districts: [
      "eThekwini",
      "Amajuba",
      "Harry Gwala",
      "iLembe",
      "King Cetshwayo",
      "Umkhanyakude",
      "Umzinyathi",
      "Uthukela",
      "Ugu",
      "Zululand",
    ],
    cities: [
      "Durban",
      "Pinetown",
      "Westville",
      "Chatsworth",
      "Phoenix",
      "Umhlanga",
      "Kloof",
      "Gillitts",
      "Hillcrest",
      "Amanzimtoti",
      "Cato Ridge",
      "Hammarsdale",
      "Pietermaritzburg",
      "Howick",
      "Hilton",
      "Newcastle",
      "Madadeni",
      "Richards Bay",
      "Empangeni",
      "eShowe",
      "Mtunzini",
      "Ballito",
      "KwaDukuza",
      "Stanger",
      "Salt Rock",
      "Tongaat",
      "Verulam",
      "Mandeni",
      "Maphumulo",
      "Port Shepstone",
      "Margate",
      "Shelly Beach",
      "Uvongo",
      "Ramsgate",
      "Pennington",
      "Scottburgh",
      "Hibberdene",
      "Kokstad",
      "Ixopo",
      "Creighton",
      "Underberg",
      "Himeville",
      "Bulwer",
      "Estcourt",
      "Mooi River",
      "Bergville",
      "Winterton",
      "Colenso",
      "Ladysmith",
      "Dundee",
      "Glencoe",
      "Greytown",
      "Kranskop",
      "Vryheid",
      "Paulpietersburg",
      "Pongola",
      "Ulundi",
      "Nongoma",
      "Nkandla",
      "Melmoth",
      "Babanango",
      "Nquthu",
      "Tugela Ferry",
      "Mtubatuba",
      "St Lucia",
      "Hluhluwe",
      "Mkuze",
      "Jozini",
      "Ubombo",
      "Manguzi",
      "Hlabisa",
      "Richmond",
      "Camperdown",
      "Wartburg",
      "New Hanover",
      "Ndwedwe",
      "Impendle",
    ],
  },
  {
    province: "Limpopo",
    districts: ["Capricorn", "Mopani", "Sekhukhune", "Vhembe", "Waterberg"],
    cities: [
      "Polokwane",
      "Seshego",
      "Mankweng",
      "Lebowakgomo",
      "Tzaneen",
      "Modjadjiskloof",
      "Letsitele",
      "Haenertsburg",
      "Phalaborwa",
      "Hoedspruit",
      "Giyani",
      "Mokopane",
      "Marble Hall",
      "Groblersdal",
      "Burgersfort",
      "Steelpoort",
      "Ohrigstad",
      "Jane Furse",
      "Apel",
      "Musina",
      "Louis Trichardt",
      "Makhado",
      "Thohoyandou",
      "Malamulele",
      "Elim",
      "Bela-Bela",
      "Modimolle",
      "Mookgophong",
      "Naboomspruit",
      "Nylstroom",
      "Lephalale",
      "Ellisras",
      "Vaalwater",
      "Thabazimbi",
      "Northam",
      "Senwabarwana",
      "Dendron",
      "Chuniespoort",
      "Roedtan",
      "Zebediela",
      "Gravelotte",
      "Mooketsi",
      "Duiwelskloof",
      "Warmbaths",
    ],
  },
  {
    province: "Mpumalanga",
    districts: ["Ehlanzeni", "Gert Sibande", "Nkangala"],
    cities: [
      "Nelspruit",
      "Mbombela",
      "White River",
      "Hazyview",
      "Sabie",
      "Graskop",
      "Pilgrim's Rest",
      "Barberton",
      "Malalane",
      "Komatipoort",
      "Marloth Park",
      "Skukuza",
      "KaNyamazane",
      "Kabokweni",
      "Bushbuckridge",
      "Witbank",
      "eMalahleni",
      "Middelburg",
      "Hendrina",
      "Kriel",
      "Belfast",
      "Machadodorp",
      "Waterval Boven",
      "Dullstroom",
      "Lydenburg",
      "Mashishing",
      "Delmas",
      "Secunda",
      "Evander",
      "Kinross",
      "Trichardt",
      "Bethal",
      "Standerton",
      "Ermelo",
      "Breyten",
      "Carolina",
      "Volksrust",
      "Wakkerstroom",
      "Amsterdam",
      "Piet Retief",
      "Balfour",
      "Siyabuswa",
      "Nkomazi",
      "Barberton",
    ],
  },
  {
    province: "Northern Cape",
    districts: ["Frances Baard", "John Taolo Gaetsewe", "Namakwa", "Pixley ka Seme", "ZF Mgcawu"],
    cities: [
      "Kimberley",
      "Warrenton",
      "Barkly West",
      "Hartswater",
      "Jan Kempdorp",
      "Ritchie",
      "Modder River",
      "Upington",
      "Kakamas",
      "Keimoes",
      "Kenhardt",
      "Groblershoop",
      "Augrabies",
      "Springbok",
      "Port Nolloth",
      "Nababeep",
      "Concordia",
      "Steinkopf",
      "Aggeneys",
      "Pofadder",
      "Garies",
      "Kamieskroon",
      "Kuruman",
      "Kathu",
      "Postmasburg",
      "Olifantshoek",
      "Daniëlskuil",
      "Mothibistad",
      "Ganyesa",
      "De Aar",
      "Colesberg",
      "Britstown",
      "Hanover",
      "Noupoort",
      "Richmond",
      "Victoria West",
      "Calvinia",
      "Williston",
      "Carnarvon",
      "Sutherland",
      "Fraserburg",
      "Loxton",
      "Brandvlei",
      "Vanwyksvlei",
      "Prieska",
      "Douglas",
      "Hopetown",
      "Griekwastad",
      "Petrusville",
      "Marydale",
    ],
  },
  {
    province: "North West",
    districts: [
      "Bojanala",
      "Dr Kenneth Kaunda",
      "Dr Ruth Segomotsi Mompati",
      "Ngaka Modiri Molema",
    ],
    cities: [
      "Rustenburg",
      "Phokeng",
      "Marikana",
      "Boshoek",
      "Mogwase",
      "Brits",
      "Hartbeespoort",
      "Madibeng",
      "Koster",
      "Swartruggens",
      "Groot Marico",
      "Klerksdorp",
      "Stilfontein",
      "Orkney",
      "Potchefstroom",
      "Ventersdorp",
      "Mahikeng",
      "Mafikeng",
      "Zeerust",
      "Lichtenburg",
      "Coligny",
      "Delareyville",
      "Sannieshof",
      "Ottosdal",
      "Vryburg",
      "Taung",
      "Christiana",
      "Bloemhof",
      "Schweizer-Reneke",
      "Wolmaransstad",
      "Makwassie",
      "Leeudoringstad",
      "Ganyesa",
      "Reivilo",
      "Pomfret",
      "Setlagole",
      "Makapanstad",
    ],
  },
];

const PROVINCE_BY_NAME = new Map(SA_LOCATIONS.map((p) => [p.province.toLowerCase(), p]));

export interface Coordinates {
  lat: number;
  lon: number;
}

// Province centroids (main-metro leaning) for when a location resolves to a
// province but no known city. Coarse by design — they feed the matcher's wide
// 150/400km distance bands, not its <25km band.
const PROVINCE_COORDS: Record<string, Coordinates> = {
  gauteng: { lat: -26.1, lon: 28.1 },
  "western cape": { lat: -33.93, lon: 18.86 },
  "eastern cape": { lat: -33.3, lon: 26.5 },
  "free state": { lat: -28.8, lon: 26.8 },
  "kwazulu-natal": { lat: -29.3, lon: 30.8 },
  limpopo: { lat: -23.9, lon: 29.45 },
  mpumalanga: { lat: -25.7, lon: 30.2 },
  "northern cape": { lat: -28.74, lon: 24.76 },
  "north west": { lat: -26.0, lon: 26.5 },
};

// City/town centroids (~1km) for the common case where a job or CV names a place,
// keyed by the lowercased city name exactly as it appears in SA_LOCATIONS. Towns
// not listed here fall back to their province centroid in coordsForLocation().
// Cross-province ambiguous names (e.g. Richmond, Ganyesa) are intentionally left
// out so they resolve via the province centroid rather than guessing the wrong one.
const CITY_COORDS: Record<string, Coordinates> = {
  johannesburg: { lat: -26.2, lon: 28.05 },
  pretoria: { lat: -25.75, lon: 28.19 },
  sandton: { lat: -26.11, lon: 28.05 },
  midrand: { lat: -25.99, lon: 28.13 },
  centurion: { lat: -25.86, lon: 28.19 },
  rosebank: { lat: -26.14, lon: 28.04 },
  bryanston: { lat: -26.05, lon: 28.02 },
  randburg: { lat: -26.1, lon: 28.0 },
  roodepoort: { lat: -26.16, lon: 27.87 },
  fourways: { lat: -26.01, lon: 28.01 },
  "kempton park": { lat: -26.1, lon: 28.23 },
  edenvale: { lat: -26.14, lon: 28.15 },
  bedfordview: { lat: -26.18, lon: 28.13 },
  germiston: { lat: -26.22, lon: 28.17 },
  alberton: { lat: -26.27, lon: 28.12 },
  boksburg: { lat: -26.21, lon: 28.26 },
  benoni: { lat: -26.19, lon: 28.32 },
  springs: { lat: -26.25, lon: 28.4 },
  brakpan: { lat: -26.24, lon: 28.37 },
  nigel: { lat: -26.42, lon: 28.47 },
  menlyn: { lat: -25.78, lon: 28.28 },
  hatfield: { lat: -25.75, lon: 28.24 },
  brooklyn: { lat: -25.77, lon: 28.24 },
  irene: { lat: -25.88, lon: 28.21 },
  montana: { lat: -25.68, lon: 28.27 },
  silverton: { lat: -25.73, lon: 28.32 },
  arcadia: { lat: -25.74, lon: 28.21 },
  lynnwood: { lat: -25.77, lon: 28.28 },
  soweto: { lat: -26.27, lon: 27.86 },
  tembisa: { lat: -25.99, lon: 28.23 },
  mamelodi: { lat: -25.71, lon: 28.39 },
  soshanguve: { lat: -25.52, lon: 28.11 },
  atteridgeville: { lat: -25.77, lon: 28.07 },
  vanderbijlpark: { lat: -26.71, lon: 27.84 },
  vereeniging: { lat: -26.67, lon: 27.93 },
  sebokeng: { lat: -26.62, lon: 27.84 },
  evaton: { lat: -26.53, lon: 27.86 },
  sharpeville: { lat: -26.69, lon: 27.87 },
  heidelberg: { lat: -26.5, lon: 28.36 },
  meyerton: { lat: -26.56, lon: 28.02 },
  krugersdorp: { lat: -26.1, lon: 27.77 },
  randfontein: { lat: -26.18, lon: 27.7 },
  carletonville: { lat: -26.36, lon: 27.4 },
  westonaria: { lat: -26.32, lon: 27.65 },
  magaliesburg: { lat: -25.99, lon: 27.55 },
  cullinan: { lat: -25.67, lon: 28.52 },
  bronkhorstspruit: { lat: -25.81, lon: 28.74 },
  "mogale city": { lat: -26.1, lon: 27.77 },
  lenasia: { lat: -26.32, lon: 27.83 },
  alexandra: { lat: -26.1, lon: 28.1 },
  vosloorus: { lat: -26.34, lon: 28.2 },
  katlehong: { lat: -26.34, lon: 28.15 },
  daveyton: { lat: -26.15, lon: 28.4 },
  kagiso: { lat: -26.16, lon: 27.77 },
  "cosmo city": { lat: -26.02, lon: 27.93 },
  fochville: { lat: -26.48, lon: 27.49 },
  "cape town": { lat: -33.92, lon: 18.42 },
  bellville: { lat: -33.9, lon: 18.63 },
  durbanville: { lat: -33.83, lon: 18.65 },
  goodwood: { lat: -33.9, lon: 18.55 },
  parow: { lat: -33.9, lon: 18.59 },
  milnerton: { lat: -33.87, lon: 18.49 },
  "table view": { lat: -33.82, lon: 18.49 },
  "century city": { lat: -33.89, lon: 18.51 },
  constantia: { lat: -34.02, lon: 18.42 },
  claremont: { lat: -33.98, lon: 18.47 },
  wynberg: { lat: -34.0, lon: 18.47 },
  khayelitsha: { lat: -34.04, lon: 18.68 },
  "mitchells plain": { lat: -34.05, lon: 18.62 },
  "somerset west": { lat: -34.08, lon: 18.85 },
  strand: { lat: -34.12, lon: 18.83 },
  "gordon's bay": { lat: -34.16, lon: 18.87 },
  kuilsrivier: { lat: -33.93, lon: 18.69 },
  stellenbosch: { lat: -33.93, lon: 18.86 },
  franschhoek: { lat: -33.91, lon: 19.12 },
  paarl: { lat: -33.73, lon: 18.96 },
  wellington: { lat: -33.64, lon: 19.01 },
  worcester: { lat: -33.65, lon: 19.45 },
  robertson: { lat: -33.8, lon: 19.88 },
  ceres: { lat: -33.37, lon: 19.31 },
  george: { lat: -33.96, lon: 22.46 },
  knysna: { lat: -34.04, lon: 23.05 },
  "mossel bay": { lat: -34.18, lon: 22.13 },
  oudtshoorn: { lat: -33.59, lon: 22.2 },
  "plettenberg bay": { lat: -34.05, lon: 23.37 },
  hermanus: { lat: -34.42, lon: 19.23 },
  swellendam: { lat: -34.02, lon: 20.44 },
  saldanha: { lat: -33.01, lon: 17.94 },
  vredenburg: { lat: -32.91, lon: 17.99 },
  langebaan: { lat: -33.09, lon: 18.03 },
  malmesbury: { lat: -33.46, lon: 18.73 },
  vredendal: { lat: -31.66, lon: 18.5 },
  clanwilliam: { lat: -32.18, lon: 18.89 },
  "beaufort west": { lat: -32.36, lon: 22.58 },
  caledon: { lat: -34.23, lon: 19.43 },
  grabouw: { lat: -34.15, lon: 19.02 },
  gansbaai: { lat: -34.58, lon: 19.35 },
  bredasdorp: { lat: -34.53, lon: 20.04 },
  riversdale: { lat: -34.09, lon: 21.26 },
  "east london": { lat: -33.02, lon: 27.91 },
  gqeberha: { lat: -33.96, lon: 25.61 },
  "port elizabeth": { lat: -33.96, lon: 25.61 },
  uitenhage: { lat: -33.76, lon: 25.4 },
  kariega: { lat: -33.76, lon: 25.4 },
  despatch: { lat: -33.79, lon: 25.48 },
  "king william's town": { lat: -32.88, lon: 27.39 },
  bhisho: { lat: -32.85, lon: 27.44 },
  mthatha: { lat: -31.59, lon: 28.78 },
  queenstown: { lat: -31.9, lon: 26.88 },
  komani: { lat: -31.9, lon: 26.88 },
  "graaff-reinet": { lat: -32.25, lon: 24.54 },
  cradock: { lat: -32.16, lon: 25.62 },
  grahamstown: { lat: -33.3, lon: 26.53 },
  makhanda: { lat: -33.3, lon: 26.53 },
  "jeffreys bay": { lat: -34.05, lon: 24.91 },
  humansdorp: { lat: -34.03, lon: 24.77 },
  butterworth: { lat: -32.33, lon: 28.15 },
  "aliwal north": { lat: -30.69, lon: 26.71 },
  "port alfred": { lat: -33.59, lon: 26.89 },
  alice: { lat: -32.79, lon: 26.84 },
  "fort beaufort": { lat: -32.78, lon: 26.63 },
  matatiele: { lat: -30.34, lon: 28.81 },
  bizana: { lat: -30.86, lon: 29.85 },
  lusikisiki: { lat: -31.37, lon: 29.57 },
  "port st johns": { lat: -31.63, lon: 29.54 },
  bloemfontein: { lat: -29.12, lon: 26.21 },
  botshabelo: { lat: -29.27, lon: 26.71 },
  "thaba nchu": { lat: -29.21, lon: 26.83 },
  welkom: { lat: -27.98, lon: 26.73 },
  virginia: { lat: -28.1, lon: 26.86 },
  odendaalsrus: { lat: -27.87, lon: 26.68 },
  sasolburg: { lat: -26.81, lon: 27.82 },
  kroonstad: { lat: -27.65, lon: 27.23 },
  parys: { lat: -26.9, lon: 27.46 },
  bethlehem: { lat: -28.23, lon: 28.31 },
  clarens: { lat: -28.52, lon: 28.42 },
  phuthaditjhaba: { lat: -28.53, lon: 28.81 },
  harrismith: { lat: -28.27, lon: 29.13 },
  ficksburg: { lat: -28.86, lon: 27.88 },
  senekal: { lat: -28.32, lon: 27.62 },
  bothaville: { lat: -27.39, lon: 26.62 },
  durban: { lat: -29.86, lon: 31.02 },
  pinetown: { lat: -29.81, lon: 30.86 },
  westville: { lat: -29.83, lon: 30.92 },
  chatsworth: { lat: -29.91, lon: 30.88 },
  phoenix: { lat: -29.7, lon: 30.97 },
  umhlanga: { lat: -29.73, lon: 31.08 },
  kloof: { lat: -29.78, lon: 30.83 },
  hillcrest: { lat: -29.78, lon: 30.76 },
  amanzimtoti: { lat: -30.05, lon: 30.88 },
  pietermaritzburg: { lat: -29.6, lon: 30.38 },
  howick: { lat: -29.49, lon: 30.23 },
  hilton: { lat: -29.55, lon: 30.3 },
  newcastle: { lat: -27.76, lon: 29.93 },
  "richards bay": { lat: -28.78, lon: 32.04 },
  empangeni: { lat: -28.75, lon: 31.89 },
  eshowe: { lat: -28.89, lon: 31.47 },
  ballito: { lat: -29.54, lon: 31.21 },
  kwadukuza: { lat: -29.34, lon: 31.29 },
  stanger: { lat: -29.34, lon: 31.29 },
  tongaat: { lat: -29.58, lon: 31.12 },
  verulam: { lat: -29.65, lon: 31.05 },
  "port shepstone": { lat: -30.74, lon: 30.45 },
  margate: { lat: -30.86, lon: 30.37 },
  kokstad: { lat: -30.55, lon: 29.42 },
  ladysmith: { lat: -28.56, lon: 29.78 },
  dundee: { lat: -28.17, lon: 30.23 },
  vryheid: { lat: -27.77, lon: 30.79 },
  ulundi: { lat: -28.34, lon: 31.42 },
  estcourt: { lat: -29.01, lon: 29.87 },
  mtubatuba: { lat: -28.42, lon: 32.18 },
  polokwane: { lat: -23.9, lon: 29.45 },
  seshego: { lat: -23.85, lon: 29.39 },
  mankweng: { lat: -23.88, lon: 29.73 },
  lebowakgomo: { lat: -24.2, lon: 29.55 },
  tzaneen: { lat: -23.83, lon: 30.16 },
  phalaborwa: { lat: -23.94, lon: 31.14 },
  hoedspruit: { lat: -24.35, lon: 30.95 },
  giyani: { lat: -23.31, lon: 30.72 },
  mokopane: { lat: -24.19, lon: 29.01 },
  groblersdal: { lat: -25.17, lon: 29.4 },
  burgersfort: { lat: -24.68, lon: 30.33 },
  musina: { lat: -22.34, lon: 30.04 },
  "louis trichardt": { lat: -23.05, lon: 29.91 },
  makhado: { lat: -23.05, lon: 29.91 },
  thohoyandou: { lat: -22.95, lon: 30.48 },
  "bela-bela": { lat: -24.88, lon: 28.29 },
  modimolle: { lat: -24.7, lon: 28.41 },
  nylstroom: { lat: -24.7, lon: 28.41 },
  lephalale: { lat: -23.67, lon: 27.7 },
  thabazimbi: { lat: -24.59, lon: 27.41 },
  nelspruit: { lat: -25.47, lon: 30.97 },
  mbombela: { lat: -25.47, lon: 30.97 },
  "white river": { lat: -25.33, lon: 31.01 },
  hazyview: { lat: -25.05, lon: 31.13 },
  sabie: { lat: -25.1, lon: 30.78 },
  graskop: { lat: -24.93, lon: 30.84 },
  barberton: { lat: -25.79, lon: 31.05 },
  malalane: { lat: -25.43, lon: 31.52 },
  komatipoort: { lat: -25.43, lon: 31.95 },
  witbank: { lat: -25.87, lon: 29.23 },
  emalahleni: { lat: -25.87, lon: 29.23 },
  middelburg: { lat: -25.77, lon: 29.46 },
  lydenburg: { lat: -25.1, lon: 30.45 },
  mashishing: { lat: -25.1, lon: 30.45 },
  secunda: { lat: -26.51, lon: 29.2 },
  bethal: { lat: -26.45, lon: 29.46 },
  standerton: { lat: -26.93, lon: 29.24 },
  ermelo: { lat: -26.53, lon: 29.99 },
  "piet retief": { lat: -27.0, lon: 30.8 },
  delmas: { lat: -26.15, lon: 28.68 },
  volksrust: { lat: -27.37, lon: 29.88 },
  kimberley: { lat: -28.74, lon: 24.76 },
  upington: { lat: -28.46, lon: 21.26 },
  springbok: { lat: -29.66, lon: 17.89 },
  "port nolloth": { lat: -29.25, lon: 16.87 },
  kuruman: { lat: -27.45, lon: 23.43 },
  kathu: { lat: -27.7, lon: 23.05 },
  postmasburg: { lat: -28.33, lon: 23.07 },
  "de aar": { lat: -30.65, lon: 24.01 },
  colesberg: { lat: -30.72, lon: 25.1 },
  calvinia: { lat: -31.47, lon: 19.77 },
  sutherland: { lat: -32.4, lon: 20.67 },
  prieska: { lat: -29.66, lon: 22.74 },
  douglas: { lat: -29.06, lon: 23.77 },
  hopetown: { lat: -29.62, lon: 24.09 },
  "victoria west": { lat: -31.4, lon: 23.12 },
  warrenton: { lat: -28.11, lon: 24.85 },
  hartswater: { lat: -27.76, lon: 24.81 },
  rustenburg: { lat: -25.67, lon: 27.24 },
  phokeng: { lat: -25.58, lon: 27.13 },
  marikana: { lat: -25.7, lon: 27.48 },
  brits: { lat: -25.63, lon: 27.78 },
  hartbeespoort: { lat: -25.75, lon: 27.85 },
  madibeng: { lat: -25.63, lon: 27.78 },
  klerksdorp: { lat: -26.85, lon: 26.67 },
  stilfontein: { lat: -26.84, lon: 26.77 },
  orkney: { lat: -26.98, lon: 26.67 },
  potchefstroom: { lat: -26.72, lon: 27.1 },
  mahikeng: { lat: -25.86, lon: 25.64 },
  mafikeng: { lat: -25.86, lon: 25.64 },
  zeerust: { lat: -25.54, lon: 26.08 },
  lichtenburg: { lat: -26.15, lon: 26.16 },
  vryburg: { lat: -26.96, lon: 24.73 },
  taung: { lat: -27.54, lon: 24.78 },
  ventersdorp: { lat: -26.31, lon: 26.81 },
  coligny: { lat: -26.33, lon: 26.32 },
  "schweizer-reneke": { lat: -27.19, lon: 25.33 },
  wolmaransstad: { lat: -27.2, lon: 25.97 },
  christiana: { lat: -27.91, lon: 25.16 },
  bloemhof: { lat: -27.65, lon: 25.6 },
};

export const SA_PROVINCES: string[] = SA_LOCATIONS.map((p) => p.province);

export function districtsForProvince(province: string | null): string[] {
  if (!province) return [];
  const match = PROVINCE_BY_NAME.get(province.toLowerCase());
  return match ? [...match.districts] : [];
}

export function citiesForProvince(province: string | null): string[] {
  if (!province) return [];
  const match = PROVINCE_BY_NAME.get(province.toLowerCase());
  return match ? [...match.cities] : [];
}

// Every term whose presence in a free-text location means the location is in this
// province: the province name, its districts, and its cities/towns — lowercased.
export function provinceMatchTerms(province: string): string[] {
  const match = PROVINCE_BY_NAME.get(province.toLowerCase());
  if (!match) return [province.toLowerCase()];
  return [match.province, ...match.districts, ...match.cities].map((term) => term.toLowerCase());
}

export function locationInProvince(locationHaystackLower: string, province: string): boolean {
  return provinceMatchTerms(province).some((term) => locationHaystackLower.includes(term));
}

// Whole-word/phrase containment so "Alice" doesn't match inside "Malice" and
// "George" doesn't match inside "Georgetown".
function containsTerm(haystackLower: string, termLower: string): boolean {
  let from = 0;
  for (;;) {
    const idx = haystackLower.indexOf(termLower, from);
    if (idx === -1) return false;
    const before = idx === 0 ? "" : haystackLower[idx - 1];
    const afterIdx = idx + termLower.length;
    const after = afterIdx >= haystackLower.length ? "" : haystackLower[afterIdx];
    const isBoundary = (ch: string) => ch === "" || !/[a-z]/i.test(ch);
    if (isBoundary(before) && isBoundary(after)) return true;
    from = idx + 1;
  }
}

// Resolve a free-text job location to a single canonical province. The strongest
// signal wins so same-named towns disambiguate: an explicit province name, then a
// district/metro, then the most specific (longest) town name. "Middelburg,
// Mpumalanga" -> Mpumalanga; "Benoni, Ekurhuleni" -> Gauteng (via the district).
export function resolveProvince(locationText: string | null): string | null {
  if (!locationText) return null;
  const hay = locationText.toLowerCase();

  for (const p of SA_LOCATIONS) {
    if (containsTerm(hay, p.province.toLowerCase())) return p.province;
  }
  for (const p of SA_LOCATIONS) {
    if (p.districts.some((d) => containsTerm(hay, d.toLowerCase()))) return p.province;
  }
  let best: { province: string; len: number } | null = null;
  for (const p of SA_LOCATIONS) {
    for (const city of p.cities) {
      const cl = city.toLowerCase();
      if (containsTerm(hay, cl) && (best === null || cl.length > best.len)) {
        best = { province: p.province, len: cl.length };
      }
    }
  }
  return best ? best.province : null;
}

// The most specific known town/city in the location, preferring one inside the
// resolved province so same-named towns map to the right place.
export function resolveCity(locationText: string | null, province: string | null): string | null {
  if (!locationText) return null;
  const hay = locationText.toLowerCase();
  const pools = province ? [citiesForProvince(province)] : SA_LOCATIONS.map((p) => p.cities);
  let best: { city: string; len: number } | null = null;
  for (const pool of pools) {
    for (const city of pool) {
      const cl = city.toLowerCase();
      if (containsTerm(hay, cl) && (best === null || cl.length > best.len)) {
        best = { city, len: cl.length };
      }
    }
  }
  return best ? best.city : null;
}

export function resolveLocation(locationText: string | null): {
  province: string | null;
  city: string | null;
} {
  const province = resolveProvince(locationText);
  return { province, city: resolveCity(locationText, province) };
}

// Free, in-process geocoding of a SA free-text location to coordinates: the named
// city's centroid if known, else the resolved province's centroid, else null.
// City-level accuracy, which is all the matcher's distance bands need. A null
// result (unknown/foreign/remote) is the caller's cue to fall back to a paid
// geocoder, if one is configured.
export function coordsForLocation(locationText: string | null): Coordinates | null {
  const { province, city } = resolveLocation(locationText);
  const cityCoords = city ? CITY_COORDS[city.toLowerCase()] : null;
  if (cityCoords) {
    return cityCoords;
  }
  const provinceCoords = province ? PROVINCE_COORDS[province.toLowerCase()] : null;
  return provinceCoords ?? null;
}
